### ISSUE TITLE
Mark Core Module as Signed or Unsigned

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#1002]
When loading modules we know if they have been signed i.e. retrieved from the store, we should add a boolean into the Module object so that we can display this information in the UI.

**Comment by Puckfist** [comment]
I do not believe the Core bears any signature even if gotten from the store

**Comment by terrypacker** [comment]
It is hard coded in the ModuleRegistry getCoreModule() which we should change to check one of the signed files within the core.  I think there is another issue around this exact thing.

**Comment by terrypacker** [comment]
Put logic into ModuleRegistry around line 155 to check if the file release.properties is signed i.e. release.signed.

**Comment by terrypacker** [comment]
Confirmed this is working in 3.3.0, downloaded from test store and saw the signed indication on the modules page.
