### ISSUE TITLE
ModuleRestController NPE on /rest/v1/modules/upgrade-status

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#1004]
Stack trace attached:
[npe-upgrade-status.txt](https://github.com/infiniteautomation/ma-core-public/files/1012310/npe-upgrade-status.txt)

**Comment by terrypacker** [comment]
Fixed.

**Comment by terrypacker** [comment]
I've implemented some dummy tests in the modules.spec.js tests.
