### ISSUE TITLE
Test REST CRUD for Event Detectors

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#1007]
All the event detector models have been implemented a spec.js file should be created to test adding/modifying/deleting each type of detector.

**Comment by Puckfist** [comment]
The POST endpoint /v2/event-detectors calls this.dao.getByXid(xid); which throws a ShouldNeverHappen exception in the EventDetectorDao every time.

**Comment by Puckfist** [comment]
Also GET and PUT /v2/event-detectors/{xid} have the same problem

**Comment by terrypacker** [comment]
This is being fixed and added to the eventDetector.spec.js file in the mango-node-client

**Comment by terrypacker** [comment]
Appears fixed via test spec but could use better test cases in the spec to be sure.

**Comment by terrypacker** [comment]
Has test spec, will create new issues if we find problems when we write the UI for this.
