### ISSUE TITLE
Lots of noise and warnings building due to snapshot maven repos

### ISSUE THREAD

**Issue by jazdw** [infiniteautomation/ma-core-public#1015]
See logs here - https://gist.github.com/jazdw/7d2e90374e2cf5e2ea7ad322f23aeb62

I think this is caused by dependencies defining repositories in their pom.xml files. Maven seems to check all repos for the latest snapshot versions once a day.

In particular we should find the dependency which is defining the codehaus-snapshots repository and upgrade it as the codehaus-snapshots repo does not exist any more. It is probably one of the codehaus plugins we are using in the build process.

**Comment by terrypacker** [comment]
This has been fixed for 3.4, all maven-local repos are removed and any deps were added to maven.mangoautomation.net
