### ISSUE TITLE
Timer Tasks/High Priority Tasks that reference Common.runtimeManager can fail

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#1016]
Due to the order of the lifecycle the Real Time Timer is shutdown after the RuntimeManager.  This means that any scheduled or submitted tasks to the High Priority Pool will be able to access the RuntimeManager after it is terminated.  I have removed the de-reference code that sets Common.runtimeManager = null; after terminating it.  The correct way to use the RuntimeManger in a Task is to check its state first:

`Common.runtimeManager.getState() != RuntimeManager.RUNNING`

Note that there is no restrictions on the calling any of the other methods after it has been terminated and the results of these calls are undefined.  Basically don't do it.

Here is a list of all Tasks that reference the Runtime Manager that should be reviewed:

- [x] DelayedSetTask
- [x] PidPwm
- [x] PurgeAllPointValuesAction
- [x] DataPurge
- [x] SetPointWorkItem
- [x] DataPointImporter
- [x] DataSourceImporter
- [x] PublisherImporter

**Comment by terrypacker** [comment]
Adding this check to all above code:

		if(Common.runtimeManager.getState() != RuntimeManager.RUNNING)
			return;

**Comment by jazdw** [comment]
While doing an update, my backup failed resulting in an active task stuck in the queue on shutdown.
https://gist.github.com/jazdw/fd011758f85001a39672da8d2a658c3a

The process exited after the last log entry.

**Comment by jazdw** [comment]
I had a failed upgrade that caused mango to fail starting, afterwards there were stuck threads -
https://gist.github.com/jazdw/6642ef98de125e61b662a4a69a375bee
![image](https://user-images.githubusercontent.com/3579645/26940080-97d1c074-4c36-11e7-855f-2d0cb6f9befc.png)

**Comment by terrypacker** [comment]
I've fixed the problem with the extra threads hanging around on a bad startup, there was a problem with the lifecycle terminating various subsystems if exceptions were thrown.

**Comment by terrypacker** [comment]
Confirmed that a failed DB Upgrade check will result in a clean shutdown with no remaining threads as per comment by @jazdw
