### ISSUE TITLE
Upgrade H2 User Comments Table

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#1021]
Make the ID column a PK as it now is in the create tables script.

**Comment by Puckfist** [comment]
The other tables types got this in upgrade14

**Comment by Puckfist** [comment]
If (SELECT SQL 
FROM INFORMATION_SCHEMA.CONSTRAINTS
WHERE TABLE_NAME = 'USERCOMMENTS' AND SQL LIKE '%PRIMARY KEY%').resultSize == 0 then
ALTER TABLE userComments ADD PRIMARY KEY (id);

**Comment by terrypacker** [comment]
Tested with fresh H2 install so it doesn't execute the SQL.  Need to test on existing system with comments and no index.  Also it would be good to test MsSQL as that syntax is unfamiliar.

**Comment by Puckfist** [comment]
It was RFC -12 Pseudocode syntax, it seems.
