### ISSUE TITLE
Graphical Views data point drop down list does not use searchable lists for "Simple Compound"

### ISSUE THREAD

**Issue by resotek** [infiniteautomation/ma-core-public#103]
The [core-2.1.0 changes page](http://store.infiniteautomation.com/core/2.1.0) states: 

> Updated all data point drop down list throughout Mango to use searchable lists

However, this update was not made to "Graphical Views" (views.shtm).

I have over 500 data points, so I was really looking forward to this update.

**Comment by terrypacker** [comment]
This will require a re-write of how the CompoundEditor works.  It currently rebuilds the select drop downs every time the widget is opened.  This becomes troublesome with dojo widgets as you have to destroy() them and rebuild them each time.  The ideal solution will have a way to dynamically place() pre-created hidden divs the the location of the selects.  Pushing this off till next minor release.

**Comment by terrypacker** [comment]
The drop downs work but I think there may be a legacy bug in this component that needs review.  The lead point is always shown when viewing but none of the sub points are...

**Comment by Puckfist** [comment]
That should perhaps be its own issue? Either that or resolved as not getting fixed. Cannot close this, even though the dropdowns are totally searchable!

**Comment by terrypacker** [comment]
I am closing this as the bug listed above for not showing the sub points only happens in the edit view, plus we have a new UI with dashboard designer to replace this module.
