### ISSUE TITLE
Log files are created in working directory rather than MA_HOME

### ISSUE THREAD

**Issue by jazdw** [infiniteautomation/ma-core-public#1031]
I believe this happened when we upgraded Log4j

**Comment by terrypacker** [comment]
I'm not seeing this when using the ma.sh start command from any directory on my system.  Is the potentially a windows issue?  

The log files have always been written to a path relative to the working directory like this "logs/ma.log"  

Log4j2 does support property substitution so we should fix this up to use MA_HOME in the log file path in the log4j2.xml configuration file.
