### ISSUE TITLE
Event Manager Return To Normal for Ignore Level Events is wasteful

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#1032]
We are locking, iterating over and then unlocking the activeEvents list in search of an event that is not going to be in the list.

The fix will require a core change that requires the Alarm Level to be passing into the EventManager.returnToNormal() method.

**Comment by Puckfist** [comment]
https://github.com/infiniteautomation/ma-core-public/commit/00e98dae4a0828df295254e5c5559a907d67f425
https://github.com/infiniteautomation/ma-modules-public/commit/5e2ffb9cf06923421082e6e5a3785807b00cccf8
https://github.com/infiniteautomation/ma-modules-private/commit/4633ff517f984897e78694a0094b146327f03eff
https://github.com/infiniteautomation/ma-core-private/commit/c64c858ccfa8f404bba2d4e651c7f1170d6dbcf4
