### ISSUE TITLE
Polling Data Source RT - Each poll will return events to normal

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#1033]
A more efficient solution would be to track the state of the alarms and only return them to normal if they are active.  

We should probably look at all other polling data sources to see if this is happening elsewhere.

**Comment by Puckfist** [comment]
This is incredibly common. Almost all of the return an event to normal every poll.

**Comment by terrypacker** [comment]
Closing as released in 3.6.0
