### ISSUE TITLE
Excel Reports dropdown for named rages does not open

### ISSUE THREAD

**Issue by Joelhaggar** [infiniteautomation/ma-core-public#1036]
It seems to work when creating a new report but then after saving and refreshing the page it doesn't work.  Editing existing reports also have the same issue

**Comment by terrypacker** [comment]
Jared I've replicated it and there is no output in the dev tools that indicates something is wrong.   I'm guessing the backing store isn't getting initialized when a report is loaded, I figured you wrote this code so it might be easier for you to trace it.
