### ISSUE TITLE
MangoES Configuration license needs to be updated

### ISSUE THREAD

**Issue by Joelhaggar** [infiniteautomation/ma-core-public#1039]
This module should only show up available for install if the core is licensed with MangoES or Brewers Dashboard.

**Comment by Puckfist** [comment]
The store has the ability to restrict things based on module and account tags. I have a bandaid solution to prevent people from accidentally downloading it applied. Issues may exist if we transfer the license to their account and they delete the module one way or another.

**Comment by Puckfist** [comment]
Removing ready for testing as the requested feature, having the restriction structured into the license type, isn't done yet. But, i'm not sure it will be. This issue could probably considered whenever the deployment of the full semver store is.

**Comment by Puckfist** [comment]
I fit this in. Module tags for accounts now also factors in the core license type, such that it appears the account also has the tag that is the type of the license for that instance.
