### ISSUE TITLE
H2 database restore does nothing

### ISSUE THREAD

**Issue by jazdw** [infiniteautomation/ma-core-public#1042]
Windows
H2 database
Running restore from REST API which calls
`ProcessResult result = DatabaseBackupWorkItem.restore(filename);`

Nothing in my console. REST returns HTTP OK but the database is not restored.

**Comment by Puckfist** [comment]
I tested it, seems to work to me. I assume this was through the /v2/actions/trigger/{action} endpoint. One thing I found weird is that DatabaseBackupWorkItem.restore is expecting a filename within the configured backup directory. So, it took an object like this one in the body for me: {"filename":"core-database-H2-Jul-10-2017_132152.zip"}

**Comment by Puckfist** [comment]
Kinda interesting one cannot get the type of system action back out of a system action object.

**Comment by jazdw** [comment]
Yeah you need to supply the filename to restore and this works, I traced the filename getting from the REST end point through to the DatabaseBackupWorkItem.restore(filename) but it just didn't seem to do anything.

**Comment by Puckfist** [comment]
I just tested the modules page again a few times. It's working. I'm closing.
