### ISSUE TITLE
Add Limits to PointValueDao

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#1043]
We have implemented limits for Point Value Queries via the REST api but they are not as efficient as they could be.  To properly implement the limits we will need to modify the NoSQL and SQL PointValueDao's to accept a limit and use it in the queries.

**Comment by Puckfist** [comment]
If we do #813 in adding the delete between, it would seem we may want to get this at the same time since it'll be all the same places.
