### ISSUE TITLE
Excel Reports - New report instance on wrong end of list

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#1045]
New report instances are added to the list without consideration to any user specified sort ordering. This can be very confusing, as the newest reports can appear at the bottom even if the newest report is sorted to be at the top!

**Comment by jazdw** [comment]
Yeah can confirm this, as you say it is quite confusing. I'll see if I can fix it quickly, I'm working on this module atm.

**Comment by jazdw** [comment]
I'm going to re-open this, that didn't seem to fix it. Seems like it is an intermittent problem in dgrid/dstore.

**Comment by Puckfist** [comment]
Yeah, not fixed yet.

**Comment by Puckfist** [comment]
Fixed in the new UI, newest report to the top of the list!
