### ISSUE TITLE
NoSQL - retry delete / purge / all on a shard basis, not query basis

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#1047]
Because data can be chronologically disordered and a callback must be abandoned, it was made possible for a delete or a purge to fail because a point will have this retry error. A delete or a purge should probably always be retried, and only the number from the second count should be totaled.

**Comment by Puckfist** [comment]
The current solution could be improved slightly, as the notion of retries is directed more toward retrying the same shard several times whereas in the nosql dao the retries is for the whole query, so if two or more shards in the query period have disordering corruption, the exception will still make it back out to the user.

**Comment by terrypacker** [comment]
Likely fixed by: 3d0ab3029dc651ca709d9540e0f1f27586207a44

**Comment by terrypacker** [comment]
Closing as fixed until we see another problem from this.
