### ISSUE TITLE
Controller Trends

### ISSUE THREAD

**Issue by tinyhazeleyes** [infiniteautomation/ma-core-public#1052]
Add the ability to edit and view local controller trends and schedules.  Trends seem like a must have feature for medium to large sites.

Backup and restore controller databases would be nice.

Creating points in controllers would be sweet but that seems like it might be difficult.

**Comment by Puckfist** [comment]
Hi tinyhazeleyes!

Are you talking about BACnet? Can I got a -v on that?

Also, opening an issue is not really the right place for a new feature. If you're hoping for a new feature, a good place to suggest it is the wishlist on our forum: https://forum.infiniteautomation.com/category/6/wishlist

If on the other hand you're desiring to pay to have those features added, you're best contacting us directly at sales@infiniteautomation.com
