### ISSUE TITLE
Meta Data - return without new value

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#1061]
Currently, if you are in a meta point and you call "return;" you will get the casting of a null into your data type as a default value. The only way to not get a value is to throw "an error that prevents a value."; but this forces you to ignore script errors or you get spammed in regular operation. It would be nice if there was a way for meta points (or point links or set point handlers) to assess at runtime not to generate a new value.

**Comment by Puckfist** [comment]
I implemented this with a static data value in the context signifying a unchanged result.

**Comment by Puckfist** [comment]
I will probably add something like this to the point links too

**Comment by Puckfist** [comment]
This is in the meta module currently, but the way it works was refactored to the core so that the set point handler and point links could also do the same thing. The meta module will want to get updated for the 3.3 release to get this functionality from the core (which is also when it will be added to point links)

**Comment by Puckfist** [comment]
This should be ready for any final testing.

**Comment by jazdw** [comment]
Could also check if the result of the function is undefined - https://stackoverflow.com/questions/29277606/differ-null-and-undefined-values-in-nashorn
