### ISSUE TITLE
Able to delete module dependency

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#1066]
I found that I can delete the mangoUI module even when I have modules that depend on it.  This should be fixed for REST and DWR.

**Comment by Puckfist** [comment]
I was not able to add a message that makes it back to the page easily, but I did make it such that marking a module for deletion that can't be deleted from a dependency standpoint logs a warning and doesn't mark it.

**Comment by Puckfist** [comment]
It is not a 400 response in that situation, with a relevant message in the "localizedMessage" attribute of the response

**Comment by terrypacker** [comment]
The backend code works but the new UI doesn't tell you it won't delete it.  However it also doesn't show that it's marked for deletion.  The Rest controller throws:

```
com.infiniteautomation.mango.rest.v2.exception.ModuleRestV2Exception: Dependencies prevented marking for deletion
```

**Comment by terrypacker** [comment]
Closing this and opened an issue in the dashboards repo.
