### ISSUE TITLE
HTTP Json Retriever - new data source type

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#1070]
We do not have a way to retrieve an HTTP page, then parse values out of it using JSON accessors currently

**Comment by jazdw** [comment]
Doesn't really need to be a new data source type, just another option on the point locator perhaps.

From what I understand the data source specifies the URL which is a bit odd IMO, could the URL not be a part of the point locator? You would of course need to check each data point and get a set of URLs to retrieve so you don't make the same HTTP request 10 times but that should be pretty easy to do.

**Comment by Puckfist** [comment]
An upgrade of a previous HTTP Retriever should definitely be done.

I decided not to rewrite the data source, so the json retriever is another data source that behaves in much the same way, i.e. specify a URL and use points to identify content within that resource.

**Comment by Puckfist** [comment]
This was released in October
