### ISSUE TITLE
Create Common Interfaces

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#1077]
To aid in testing we should use Interfaces for the Common members for the 3.3 release:

- [x] ReloadingProperties
- [x] RuntimeManager
- [x] DatabaseProxy
- [x] BackgroundProcessing
- [x] EventManager
- [x] SerialPortManager

**Comment by terrypacker** [comment]
Do we want to add the ILifecycle interface into the DatabaseProxy (enabling safe mode support)?

**Comment by Puckfist** [comment]
While ultimately it's the same value, I think the things that currently refer to RuntimeManagerImpl.RUNNING should refer to RuntimeManager.RUNNING

Other than that I feel contented closing this as tested through every other avenue.

**Comment by terrypacker** [comment]
I don't see that in the RuntimeManagerImpl?  The only place RUNNING is defined is in the ILifecycle.  Were you referencing a different interface?
