### ISSUE TITLE
MangoNoSql - basically broken by task queue

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#1078]
The Merge item is essentially broken. All merge tasks share a task id, their unchangeable default queue size is 0, and it attempts to launch 5 by default. This leads to 4 getting rejected (silently) which means the MangoNoSqlMergeManager never reports finished and no second merge can be started. Only the first task did any work. It would probably work as intended with only 1 task.

Fix by removing the task id as these merges are not ordered in that sense and you cannot run multiple via the manager's enforcement?

**Comment by terrypacker** [comment]
Agreed by removing the ID you will be able to run many work items in parallel and the Manager enforces that only 1 merge can run at a time.
