### ISSUE TITLE
Event Detector Rest - Name and alias bad behavior

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#1079]
"name" is not something you can set for an event detector anywhere in the UI. AbstractVOs have names. Event Detectors have aliases. This is apparent in the setAlias method for AbstractEventDetectorVO:

public void setAlias(String alias) {
		this.name = alias;
	}

but for some reason both name and alias are in the models returned from the API. There is validation that only seems to apply to the API that the alias / name cannot be blank. So, you can create a very basic event detector in the ui, GET it, try to PUT it, and you won't be able to because it will fail this validation.

**Comment by jazdw** [comment]
Adding @JsonIgnoreProperties({"name"}) to AbstractEventDetectorModel will probably solve this.

**Comment by terrypacker** [comment]
I'd like to get away from alias in the new UI and just use name.  Since we aren't using these endpoints yet we should rework the model to only have a name and then remove the alias from the VO (with an upgrade) or set both name and alias to the same thing.

**Comment by jazdw** [comment]
I've removed the alias from the model and deprecated the getAlias() setAlias() methods of the VO 221ced183a0aab878f0625bd16fc611e5f9327b1

**Comment by terrypacker** [comment]
AbstractEventHandlerVO has the same problem.

**Comment by terrypacker** [comment]
One remaining question is how to handle the JSON emports.  I suggest that we begin writing out 'name' instead of alias and provide the ability to read in 'alias' and 'name' with 'name' taking priority if they are both there.

**Comment by terrypacker** [comment]
I have updated AbstractEventHandlerVO to deprecate alias and removed it from the model.

**Comment by Puckfist** [comment]
https://github.com/infiniteautomation/ma-core-public/commit/c4411ec18d83bea03b267c26b01a297512c12235
