### ISSUE TITLE
Reset your password email option

### ISSUE THREAD

**Issue by jazdw** [infiniteautomation/ma-core-public#1089]
We should add a "forgot your password?" option. It should email a link to the user which they can click to reset their password. This could be implemented easily using a JWT with a short expiry time.

**Comment by Puckfist** [comment]
I think we need to give them the option to supply an SMTP server at the same time, probably.

**Comment by Puckfist** [comment]
Agreed, bad idea to let them supply the server. We should probably hardcode a server it uses if there isn't one configured?

**Comment by terrypacker** [comment]
Maybe we only show the option to reset password if a mail server is configured in the system settings?

**Comment by terrypacker** [comment]
Also we probably want to think around the logic of how this works if the server fails to send an email, especially if its an admin.  For example if the only admin tries to reset their password but the smtp configuration is bad we don’t want them to end up unable to login...

**Comment by jazdw** [comment]
> We should probably hardcode a server it uses if there isn't one configured?

Nope, that's a bad idea. The user has to configure their own, every SMTP server out there requires authentication.

> Also we probably want to think around the logic of how this works if the server fails to send an email, especially if its an admin. For example if the only admin tries to reset their password but the smtp configuration is bad we don’t want them to end up unable to login...

We are not running a web service, the administrator is ultimately responsible for their own instance of Mango and should have access to the backend.

**Comment by Puckfist** [comment]
With access to the backend you can already reset your password

**Comment by terrypacker** [comment]
I'm seeing this a needing some core API changes that we should put into 3.3.0 and then we can implement a v2 REST endpoint to allow the reset/send the email.

1.  Write up an HTML and Text FTL template for the email
2.  Create a work Item in the core that will send the email.
3.  Create the backing logic/storage for generating random single-use token that is tied to a specific user account that will have its password reset.

The main question is to use a new database table for the token storage or should we simply us a map in memory that goes away if Mango is reset.  Generally these are stored in a database table.

**Comment by jazdw** [comment]
> The main question is to use a new database table for the token storage or should we simply us a map in memory that goes away if Mango is reset.

The nice thing about using JWT for this is that the tokens do not need to be stored anywhere. They are cryptographically signed and have an expiration time. When the user clicks the link containing the token as a query param the server reads the token and verifies its signature and expiration date then resets the password.

**Comment by terrypacker** [comment]
This is very nice.  Tested using the reset link in the email and also via entering the token into the box.
