### ISSUE TITLE
Editing Pages the "New" button is right next to "Save" which is dangerous

### ISSUE THREAD

**Issue by Joelhaggar** [infiniteautomation/ma-core-public#1101]
You can easily click the New button by accident rather than save and loose your work.  Maybe New can only work if it's first been saved?

**Comment by jazdw** [comment]
@Joelhaggar It should ask you if you want to discard your changes if you click new. If there are no changes it will just go ahead and create a new page.

**Comment by jazdw** [comment]
Closing this after talking to @Joelhaggar Please re-open if we encounter this problem again.
