### ISSUE TITLE
Remove unnecessary @Override methods

### ISSUE THREAD

**Issue by jazdw** [infiniteautomation/ma-core-public#1111]
e.g. EventDetectorDao and AbstractEventDetectorVO from 5aca48a52b5e695e9c3f09bd64c075f2bbe93110
AbstractMangoRestV2Controller from 103f45738b91ccf55e8ef3cbd50b9a66ea03c0df

**Comment by jazdw** [comment]
Also remove this hack infiniteautomation/ma-modules-public@980522b8742dea55c13b89be407a0bbacc19441f

**Comment by Puckfist** [comment]
This issue is probably related to that hack: https://github.com/infiniteautomation/ma-core-public/issues/1079

**Comment by jazdw** [comment]
These have all been fixed up. Commits -
221ced183a0aab878f0625bd16fc611e5f9327b1
ba9f5498fee2c539cc4477b0927f0e5dd348a3b8
b7c5e2b34f9745b176775d4f0810d4af7873846b
infiniteautomation/ma-modules-public@adc481258f7cb2a7966662358886cdd4b87483bf
infiniteautomation/ma-modules-public@ffcbb1561bae3c734bac0804ea09ee0c5cb0f219
infiniteautomation/ma-modules-proprietary@f47ce5c119fa3cbc5f4c4f8629f869436bad3bf9
