### ISSUE TITLE
Add a threshold and duration to the "Change" point event detector

### ISSUE THREAD

**Issue by resotek** [infiniteautomation/ma-core-public#112]
It would be useful to select how much a numeric point value must change by to be deemed a "Change." 

Use cases: 
- The change in PV energy should always be positive. A detector would alert me of a negative change in energy. I would like to be able to generate an event alias message such as "the PV energy changed by -1kW since 1 minute ago.
- Depth sensors are used to measure tank levels. A change exceeding x amount within a certain time interval would alert of either a sensor removal for maintenance, or a malfunction, or a vessel leak.
- For a counter that should only count up, a negative change compared to the previous sample would alert us of a counter reset or malfunction.

**Solution:** add a "Difference" field to the Change Detector, and a time interval.
- Difference can be positive or negative, zero, or blank
- Time interval represents relative elapsed time. If blank or zero it compares to previous sample.

**Comment by Puckfist** [comment]
Closed, tracking in 875
