### ISSUE TITLE
AbstractDao doesn't raise deleted audit event

### ISSUE THREAD

**Issue by jazdw** [infiniteautomation/ma-core-public#1121]
AbstractDao raises an audit event for insert/update but not delete. Is this desired behavior?

**Comment by terrypacker** [comment]
I can't think of why we wouldn't do this, must have been an oversight.  

So to fix we will override the delete(T vo, String initiatorId) method from AbstractBasicDao in AbstractDao.

**Comment by terrypacker** [comment]
Looks good to me.  Deleted events for Data sources and Users work fine.  Not testing every single thing we can save.
