### ISSUE TITLE
Multiple DataPointRTs can be started for the same data point.

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#1123]
Due to the lack of locking the RuntimeManager.saveDataPoint() method it is possible to start 2 runtimes for the same data point if the requests are issued close enough together.

**Comment by terrypacker** [comment]
Investigate the possibility of locking on a data point's ID when entering the method or terminate/replace the existing runtime while starting a data point.

**Comment by Puckfist** [comment]
Here's an option, just replace the dataPoints.put(dataPoint.getId(), dataPoint); with...
```
                    dataPoints.compute(dataPoint.getId(), (k, rt) -> {
                    if(rt != null) {
                        try{
                            getRunningDataSource(rt.getDataSourceId()).removeDataPoint(rt);
                        }catch(Exception e){
                            LOG.error("Failed to stop point RT with ID: " + vo.getId()
                                    + " stopping point."
                                    , e);
                        }
                        DataPointListener l = getDataPointListeners(vo.getId());
                        if (l != null)
                            l.pointTerminated();
                        rt.terminate();
                    }
                    return dataPoint;
                });
```

Since you can't call stopDataPoint (don't make other changes to hashmap whilst computing) but you also don't need to redo the validation in saveDataPoint

**Comment by terrypacker** [comment]
One way to test this is by importing data points on a scripting data source that also generates the same points.
