### ISSUE TITLE
EventHandlersDwr - Delete Handler review

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#1126]
Since the method EventHandlerDao.getEventHandlerType(id) has been removed we need a different way to ensure permissions when calling EventHandlersDwr.deleteEventHandler(). 

I believe since we decoupled the handlers we should now be using EventHandlerDao.getEventTyepsForHandler(id) in some form or another.

**Comment by Puckfist** [comment]
Agreed, I changed it to only require permission to all event types. That method already existed!

https://github.com/infiniteautomation/ma-core-public/commit/72d9cbc7cf7058229c0850cc078fe1839f3a77e7
