### ISSUE TITLE
DataPointRT - Interval Logging with Average Rollup

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#1127]
Review the merged code in main to ensure the logic is as expected.  Especially around the end value logic.

**Comment by Puckfist** [comment]
I'm not sure what you mean, the end value logic. There's no end value jumping out at me (and nor does it make sense that there would be). So it looks good to me. I'll give it a test...

**Comment by Puckfist** [comment]
The interval average logging code looks good to me. I am wondering if I didn't understand the issue right, and you're saying something about the average rollup, like one would chart in the new UI? Or, if I did, and it was about doing an average interval log task
