### ISSUE TITLE
Wide Query Point Value Time Support

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#1129]
Add a method to the PointValueDao that performs a wide query.  This is a query with the value before the time range and the value after the time range returned with the values within the time range.

**Comment by terrypacker** [comment]
Modify PointValueFacade.getPointValues(long, boolean, boolean) to leverage this in 3.3.

**Comment by terrypacker** [comment]
We need to leverage this in the rollups for the REST api and Excel reports etc.

**Comment by jazdw** [comment]
What is the current status of the PointValueFacade? Is this still being used?

**Comment by terrypacker** [comment]
Yes its used in the legacy UI and also in the 'latest-*' REST endpoints.  It is also in the 'first-last' point values endpoint.

**Comment by terrypacker** [comment]
Closing this as we are now using 'bookend' queries which are different than a wide query.
