### ISSUE TITLE
API - Multiple points with long URLs

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#1139]
The existing multiple-points endpoints in the PointValuesRestController encode the xids array in the URL which can quickly (well, a few hundred) become too long for the request to be considered valid. There should probably be post endpoints for this functionality.

**Comment by jazdw** [comment]
The latest UI module uses the POST endpoints for getting values for multiple points. You can test via downloading point values from a watchlist.

**Comment by Puckfist** [comment]
I believe the watchlist is using the POST endpoints in the V1 controller. If that's amenable, then I think this issue can be closed.

**Comment by terrypacker** [comment]
Closing as released in 3.2.
