### ISSUE TITLE
Enable Data Point - Create dao method and path from UI

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#1141]
Currently to enable or disable a data point we must save the entire object into the database.  It would be much more efficient if we had a enable/disable methods that only updated the enabled column in the database.

**Comment by Puckfist** [comment]
Thinking this belongs in the RuntimeManagerRestController?

**Comment by Puckfist** [comment]
I have added this to the old data points table, but did not create a rest endpoint for it yet, not ensure all old calls to DataPointDwr.toggle(id) got converted to DataPointDwr.toggle(id, enabled) and then we can remove the old toggle method.

**Comment by Puckfist** [comment]
The /v1/data-points/enable-disable/{xid} endpoint uses this path now
