### ISSUE TITLE
Optionally output PointValueTime timestamps as custom formatted strings or epoch millis

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#1145]
Test the various endpoints used by the Watchlist download area.  The new parameter dateTimeFormat can be used to output the data in a String format or if left null it will output a millis since epoch number.

There is also a timezone parameter added to any endpoints that was missing one that will be used to render the String if necessary, if that is null then the server timezone is used.

**Comment by Puckfist** [comment]
It doesn't seem like the Simplify rollup option in the watchlist download data area did anything yet.

**Comment by terrypacker** [comment]
That is expected, the watch lists/data point details still use the v1 endpoint and do Simplify on the page.  The v2 endpoints will be leveraged after the release in a new UI module

**Comment by terrypacker** [comment]
Closing as tested but not actually used.
