### ISSUE TITLE
Persistent TCP datasource/publisher needs a folder prefix for hierarchy

### ISSUE THREAD

**Issue by jazdw** [infiniteautomation/ma-core-public#1148]
I'm not sure if this belongs on the datasource or the publisher but I would guess the datasource. When it receives the hierarchy from the publisher it should be able to prefix the hierarchy path.

e.g.
MangoES:
- Tank 1
- Tank 2

Server:
- Site A
    - Tank 1
    - Tank 2

**Comment by Puckfist** [comment]
I will add prefixing to both the publisher and the data source. The publisher because many-to-one publishing is possible, and the data source because being able to configure things on the larger, receiving end is often handy.
