### ISSUE TITLE
Expose context points as an array inside the meta data point script environment

### ISSUE THREAD

**Issue by jazdw** [infiniteautomation/ma-core-public#1149]
Currently I have to know the variable name for each context point in order to access it from a meta data point script. It is very useful to have an array of context points so I can use a re-use a script without modifying it and just change the context points.

I am currently working around it like this (totals the values of the context points)
```
var contextPoints = this.contextPoints;
if (!contextPoints) {
    var exported = JsonEmport.dataPointQuery('eq(xid,' + point.dataPointWrapper.xid + ')');
    var exportedPoint = JSON.parse(exported).dataPoints[0];
    var context = exportedPoint.pointLocator.context;
    contextPoints = this.contextPoints = context;
}

return contextPoints.map(function(ctxPt) {
    return this[ctxPt.varName].value;
}.bind(this)).reduce(function(sum, value) {
    return sum + value;
}, 0);
```

**Comment by Puckfist** [comment]
Went with the variable name 'VARIABLES' since 'POINTS' is in all contexts, and should have a list of context points' variable names in a scripting data source (but is probably an empty list elsewhere). This is ready.
