### ISSUE TITLE
Option for default user permissions when creating a datapoint

### ISSUE THREAD

**Issue by resotek** [infiniteautomation/ma-core-public#115]
With the current mango version, each time a new datapoint is created, the admin must go to the user page, select a user, locate the new point on that page, and update the read or write permission for that user, then select the next user, locate the point, change permissions, etc. This is *very* time consuming.

Can you please add an option on the point creation page to select what user access should be granted by default to all users for the new point?

**Comment by Puckfist** [comment]
Marking closed. While you cannot specify a default for new points, having user groups simplifies things considerably.
