### ISSUE TITLE
Add ability for admins to reassign user access from the point details page

### ISSUE THREAD

**Issue by resotek** [infiniteautomation/ma-core-public#116]
Often the admin wishes to change user access to a particular point for many or all users. This occurs either because the point was recently created, or the point has recently been verified to be accurate enough to be ready for use. Changing  AccessType to a single datapoint for multiple users is *very* time consuming when done on the user page. It is also easy to overlook users.

User access is displayed on data_point_details.shtm, but cannot be changed from there. It would be a great time saving feature to be able to update user access from data_point_details.shtm or from data_point_edit.shtm.

**Comment by Puckfist** [comment]
I am marking this closed. Mango now has a bulk permissions tool that can be used to update large sets of user permissions very quickly. The concept of user groups was also introduced since this issue was opened, which is far faster than the old bubble clicking in 2.3
