### ISSUE TITLE
Copy Data Source - fails when a point has event detectors

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#1163]
Previously event detector uniqueness was on a point id + detector xid basis. The current SQL constraint is xid uniqueness, which throws an error during copy.

**Comment by terrypacker** [comment]
This is similar to why the tests fail in #1154

**Comment by Puckfist** [comment]
cc725b3b0e19a6901b8be2a99e5114e8cd303eaa
