### ISSUE TITLE
Persistent TCP - Default settings too high

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#1171]
Make the default settings for the Publisher/DS more applicable to smaller systems, they currently default to enterprise level performance/machine size.

**Comment by Puckfist** [comment]
I changed the timeout to match the data source and lowered the number of threads for the sync in this commit: https://github.com/infiniteautomation/ma-modules-private/commit/c899d85faea808640a3a5645b376486fe7c9318e
