### ISSUE TITLE
Session listener in User should be moved elsewhere

### ISSUE THREAD

**Issue by jazdw** [infiniteautomation/ma-core-public#1182]
User.valueBound() and User.valueUnbound() contains code that raises login and logout events. Probably should move these some where else where login/logout is handled e.g. MangoLogoutHandler

**Comment by terrypacker** [comment]
Those methods get called when the User object is bound to the session, that is why it is on the User because it get's bound to the session upon successful login/logout.  Wouldn't the best place to move the logic of these methods to:

MangoAuthenticationSuccessHandler and MangoLogoutSuccessHandler?

**Comment by jazdw** [comment]
This was fixed in 34f9950d1bd20778d3a59eb3d9c7d1001d679f66
