### ISSUE TITLE
Persistent Publisher - Spams audit table

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#1188]
The persistent TCP data source will create new records in the audit table from point connection even if nothing changed - especially obvious with points that have range renderers. I was testing with the publisher and the data source in the same instance.

Test config:
[publisher-audit-events.txt](https://github.com/infiniteautomation/ma-core-public/files/1577214/publisher-audit-events.txt)

**Comment by terrypacker** [comment]
I think your test config is chopped off on the end.

**Comment by Puckfist** [comment]
Really? I just redownloaded it, no issue.

It's just a virtual data source with two points (one numeric with a range renderer, one binary) being published from a tcp publisher to a data source in the same instance.

**Comment by jazdw** [comment]
Probably something to do with the order of arrays then? How is the comparison done? Is it converted to JSON then the string compared?

I guess another question is why are points being saved if nothing changed...

**Comment by terrypacker** [comment]
Yes I've been meaning to comment on that.  We made a similar change somewhere else so that the table wouldn't get spammed.
See this commit: 389122eb3f40ad3568eec7c4b25a89a5c9c0e8e1
And this issue: #891

**Comment by terrypacker** [comment]
The JsonSerializableUtility does the heavy lifting of determining the changes between the Objects.  I can see some potential issues after reviewing the code as I think it should only focus on Sero JSON properties but it appears that the Map and Collections code also looks into the non-sero-json members.  The problem with that is there may be some runtime members set when the object is updated that don't actually represent a change to the object in the database.  

It will require a little more investigation though.

**Comment by terrypacker** [comment]
Fixed the RangeRenderer bug it wasn't comparing the values for the ranges, it was doing an Object to Object comparison.  I've modified the difference detection to evaluate the differences down to the Object.class level correctly.

**Comment by terrypacker** [comment]
Tested and no audit changes are detected when the publisher connects anymore, unless there really were changes.
