### ISSUE TITLE
Change Interval Logging - new logging type

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#1211]
Here's a branch with a mostly implemented new logging type: https://github.com/infiniteautomation/ma-core-public/commit/75abc3a297b4e735a1c436f55541ea0fbfdd9c75

This logging type is a hybrid between change logging and interval logging, where the interval logging occurs if the change logging didn't occur within the interval from the last value. The interval logging portion also moves the value, even if it was within the tolerance of the change detection, such that subsequent change detection would be done with the interval value (the instant value at the interval end). If a change is detected, then the interval is reset from the time of the change.

**Comment by resotek** [comment]
This would be very good, since sometimes when the value straddles a logging tolerance threshold, excessive data may be recorded, and the threshold value can lead to accumulated integration errors over extended periods.
