### ISSUE TITLE
Expose polling data source poll information as internal metrics

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#1212]
Some new internal metrics could easily exist for polling data sources, such that internal data sources could record this information if desired. Currently, the new internal metrics for every polling data source are,

1) Last successful poll duration
2) Sequential successful polls prior to the last aborted poll (-1 at data source startup, and until a poll aborts)
3) Quotient of successful polls to total polls

These changes are currently in the same branch as #1211 https://github.com/infiniteautomation/ma-core-public/tree/logging-change-interval

**Comment by terrypacker** [comment]
Closing as released.
