### ISSUE TITLE
Extensions Not Running on Restart

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#1214]
When Mango is restarted from the UI the enabled extensions do not run.

**Comment by Puckfist** [comment]
They run, but they are called with 'restart' instead of 'init', no? This is purposeful, so that you don't fill the JAVAOPTS with the same things twice. If you want to modify your ext-enabled you simply need to stop Mango or perform the proper modifications on the proper script lifecycle stage.

**Comment by terrypacker** [comment]
Makes sense, tried to modify the JVM memory on a system and restarted from the GUI, didn't pick up the changes as for the reason you say above.  Closing as not an issue.
