### ISSUE TITLE
Persistent TCP - Don't purge un-published point values

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#1218]
Devise a way to avoid purging data that has yet to be published.

**Comment by Puckfist** [comment]
https://github.com/infiniteautomation/ma-core-public/commit/6cd44e6a426c62a32307ac681af0513e8732db1e

**Comment by Puckfist** [comment]
Didn't tag these...
4a02fadefaca0952609d9c068499d8f483c3c5ea
fe3900f57f15df6deeabd96d03e92d5d6a737d21

**Comment by Puckfist** [comment]
This is finished, just waiting pull
