### ISSUE TITLE
Tags not exporting in JSON on Data Source

### ISSUE THREAD

**Issue by Joelhaggar** [infiniteautomation/ma-core-public#1228]
When exporting an individual data point as JSON on the Data Source page I get the tags.  If I export a group of points from the data point edit table or the upper data point table I only get “tags”:null, for all the data points even though there are tags on them

**Comment by terrypacker** [comment]
There was a special method on the DataPointDwr that used a Dojo query to return the filtered points list, the tags were not being set on the point.  Fixed.
