### ISSUE TITLE
Link documents to a data source or data point.

### ISSUE THREAD

**Issue by Joelhaggar** [infiniteautomation/ma-core-public#123]
Allow users to upload and link documents to data sources and data points.

**Comment by Puckfist** [comment]
Meaning a data source has some kind of 'file repository' pane you can upload to and download from?

**Comment by terrypacker** [comment]
Yes.  The idea is that you could put a user's manual for your Modbus device into the data source so that you could easily bring it up and look at it if you need to.

**Comment by Puckfist** [comment]
Also akin to #78
