### ISSUE TITLE
Restore Backup from Filesystem using UI

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#1233]
When Mango creates a backup it is stored in ma_home/backup but there is no way to access these files and restore using them without actually copying the file off of the server and uploading it to the UI.  A cleaner solution is to optionally allow loading a configuration file that is already in the backup folder.

This could be placed on the JSON configuration Import page.

**Comment by terrypacker** [comment]
Closing because I forgot we did this.

**Comment by terrypacker** [comment]
We should discuss opening this up to using our File browser UI to all mango directory files.

**Comment by Puckfist** [comment]
There is the JSON File Import, that does that.
