### ISSUE TITLE
Cannot create Event Handlers - Scripting fields create errors in the UI

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#1243]
I created an event detector, then went to add a Process handler, but saving results in an error about one of the new permissions fields in the UI.

I found that by switching between the various types of handlers the UI doesn't fully reload/refresh itself with the appropriate inputs.  So that is probably a place to start.

**Comment by Puckfist** [comment]
29f2e79a6a70932943f1c845911772f04b548604

**Comment by terrypacker** [comment]
I didn't test every possible permutation of inputs but I did create all 3 types with no problems.
