### ISSUE TITLE
Discarded Backdate Point Values via REST when Data Point is enabled.

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#1246]
From testing I believe I found that inserting values via the REST v1 endpoint that are backdated are discarded if the point is enabled.

**Comment by Puckfist** [comment]
It's important to have the points' JSON on this type of issue. Did you check the logging type?

**Comment by terrypacker** [comment]
Closing as we discussed this and it was the logging type set to ON_CHANGE.
