### ISSUE TITLE
Meta Data Source - Missing i18n Translations

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#1270]
The translations for the **Context event type** drop down reference the translations from the Scripting module.  We should either move these to the Core if they are used elsewhere or make a new set for the Meta Data source.

`
dsEdit.script.event.contextUpdate=Update
dsEdit.script.event.contextChange=Change
dsEdit.script.event.contextLogged=Logged
`

**Comment by Puckfist** [comment]
I added these keys to the core:

dsEdit.pointEvent.update=Update
dsEdit.pointEvent.change=Change
dsEdit.pointEvent.logged=Logged

In the next minor version bump we should unify the point links, scripting, meta, and anything else with these context events to use these keys. Until then, I'm content to say people will most likely have scripting installed or to add it to the meta module, either way.

**Comment by terrypacker** [comment]
Leave it for the next minor version bump.

**Comment by Puckfist** [comment]
The time is nigh, I will do this tomorrow
