### ISSUE TITLE
Change all REST API models to use Date objects

### ISSUE THREAD

**Issue by jazdw** [infiniteautomation/ma-core-public#1278]
Currently most of the REST API models use long integers to represent dates, we should change these to Date objects so that we can format them as we please when reading/writing the models via a Spring message converter (typically using Jackson).

The main use case for this currently is formatting dates correctly when outputting CSV so that Excel/OpenOffice/Libreoffice can interpret the date.

**Comment by terrypacker** [comment]
Should we consider Java Time's ZonedDateTime or some variant of the Java 8 time api?

**Comment by terrypacker** [comment]
Closing as we are not changing existing apis but will work to do this for new v2 and future v3 controllers.
