### ISSUE TITLE
Excel Report - only using Excel Reports filestore

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#1282]
Because I could not change the core and the excel reports filestore code was going to get used, we will need to switch it back to using the file store DAO to get file store definitions when we're doing the next minor release, essentially reverting everything in this commit: https://github.com/infiniteautomation/ma-modules-proprietary/commit/7c7de66f3b4b2384842a5f5f82d1841baab4dd52

**Comment by terrypacker** [comment]
Closing as fixed by this commit: 254c3c3393cf937a28d3bac72dfe9e8e41179cfb
