### ISSUE TITLE
 Can't seem to download the jar package

### ISSUE THREAD

**Issue by chinausers** [infiniteautomation/ma-core-public#1285]
![image](https://user-images.githubusercontent.com/27771529/41335926-1dc3e964-6f1d-11e8-8925-5aec4692a2e6.png) 
The information on the Internet is outdated. Can some examples be given?

**Comment by jazdw** [comment]
@chinausers You might need to give some more details on what you are trying to do and what the actual error is.

The jar file you referenced in the screenshot certainly seems to be in the maven central repo - http://search.maven.org/#artifactdetails%7Cdumbster%7Cdumbster%7C1.6%7Cjar

**Comment by chinausers** [comment]
谢谢
