### ISSUE TITLE
DataPointVO.getTags() unreliable

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#1287]
We cannot count on every place that updates tags placing them into DPRT objects. Therefore, we should never trust Common.runtimeManager.getDataPoint(id).getVO().getTags()

Is this true?

**Comment by jazdw** [comment]
Every place that does update tags should definitely replace the ones in the runtime. If this is not true it should be fixed. Have you noticed this somewhere?

**Comment by terrypacker** [comment]
Closing as this will be sorted by #1303
