### ISSUE TITLE
Advanced Scheduler - Queries for non admin not implemented

### ISSUE THREAD

**Issue by jazdw** [infiniteautomation/ma-core-public#1292]
Not sure why this wasn't implemented, Joel was asking why it wasn't working in Asana.

```
com.serotonin.ShouldNeverHappenException: Queries for non admin not implemented
	at com.infiniteautomation.mango.rest.v2.ScheduleRestV2Controller.queryRQL(ScheduleRestV2Controller.java:71) ~[advanced-scheduler-3.4.2-SNAPSHOT.jar:?]
```

**Comment by terrypacker** [comment]
Fixed using the new JOOQ conditions, super easy to use!  

https://github.com/infiniteautomation/ma-modules-proprietary/commit/cad10f5c7994c19a8bb3bea8b381ff5121332422

**Comment by terrypacker** [comment]
Released.
