### ISSUE TITLE
JFree charts default font language support

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#1294]
It was observed in a support email that the JFree charts that include legends do not render certain characters, like Chinese, properly. This is caused by the default font not supporting those characters. I was able to render Chinese characters upon adding the following to com.serotonin.m2m2.util.chart.ImageChartUtils in writeChart

Font font = new Font("Open Sans, Lucida Sans", Font.PLAIN, 12);
LegendTitle lt = chart.getLegend();
if(lt != null)
    lt.setItemFont(font);

and also,

anno.setFont(font);

Not sure if we want to use a system setting to set a preferred font or change the default to one with more language support?

**Comment by terrypacker** [comment]
I'm open to making it an env/system setting probably would be pretty easy.

**Comment by terrypacker** [comment]
If its a system setting you probably need an endpoint to return a list of available fonts to put into the drop down.
