### ISSUE TITLE
Data Point Tags - Odd behavior

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#1303]
I have noticed that:

1.  The name and device tags are not in the DataPointRT.vo.tags list. (This is getting set before scripting, when a point is updated, before email template generation and realtime data queries)

2.  I have name and device entries in my tags database table.

**Comment by jazdw** [comment]
This is by design. The name and device tags can be considered pseudo tags. They are updated by setting the name and deviceName properties of the data point itself.

**Comment by Puckfist** [comment]
This is why in several places for the tags you see it set into the DataPointVO and then the tag map returned from the function is the tag map returned from the DataPointVO's getTags

**Comment by terrypacker** [comment]
We should probably define the logic and place it into a common area for loading/saving the tags for a data point.

Currently the code I wrote won't have the name or device tags loaded into the map which I think is wrong.

**Comment by terrypacker** [comment]
Closing as fixed.  This is the logic to use when getting tags for a DataPointVO that has tags==null
```
DataPointVO vo = DataPointDao.instance.get(dataPointId);
            Map<String, String> tags = DataPointTagsDao.instance.getTagsForDataPointId(dataPointId);
            vo.setTags(tags);
            return vo.getTags();
```
