### ISSUE TITLE
Mango Javascript - Global Scripts out of Sync

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#1335]
It was found that if one updates a global script (or adds one) it is not available to currently running Meta and Scripting data points/sources.  We need to ensure that the global scripts are updated for every run.

**Comment by terrypacker** [comment]
We are not updating the scripts on every run, this is specifically warned about in the help.  However we will fix the problem at Import time by adding some code to the Importer so that Global Scripts are imported first.

**Comment by Puckfist** [comment]
I'm not sure about doing this in 3.5.1

I would think the right way would be giving a priority method to EmportDefintiion and then do the loop at ImportTask::261 before handling the importers list and only importing ImportItems that have the first priority. But maybe there is a simpler way....?

**Comment by terrypacker** [comment]
Adding a priority is the correct way to do that and should be done in Mango 3.6.0, until the I have implemented a solution that hard codes the JSON field name into the ImportTask.  

For 3.6 we should also consider adding a boolean to the EmportDefinition that will add the job as an ImportItem or Importer if it has no dependencies.

**Comment by Puckfist** [comment]
Seems to work. Not closing until permanent solution?

**Comment by terrypacker** [comment]
Agreed, moving to 3.6.

**Comment by terrypacker** [comment]
Calling this good.  The MangoJavaScriptService ensures that the scripts are added every run of a script.
