### ISSUE TITLE
/rest/v1/data-points/bulk-apply-read-permissions unmodifiable set issues

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#1348]
The class DataPointPermissionChangeCallback in DataPointDao seems to misuse its newPermissions member variable by attempting to add things to it after calling the methods that make it unmodifiable in permissions.

Perhaps other calls to explodePermissionGroups need to be checked for what's done with the returned set?

**Comment by Puckfist** [comment]
To reproduce, attempt to add a permission to a set of points that already has permissions

**Comment by terrypacker** [comment]
Fixed and added node-client test in api module.

**Comment by terrypacker** [comment]
Also fixing all references to that method that modify permissions.
