### ISSUE TITLE
Upgrade to Spring Framework 5.1

### ISSUE THREAD

**Issue by jazdw** [infiniteautomation/ma-core-public#1349]
[See upgrade guide](https://github.com/spring-projects/spring-framework/wiki/Upgrading-to-Spring-Framework-5.x)

**Comment by terrypacker** [comment]
This is done, no code changes were required from what I could tell.  My testing proved things are still working.  Leaving open until we finalize the release.

**Comment by jazdw** [comment]
Fixed in c6096566a044ae763c73d28b4c1f1087db3fef18
