### ISSUE TITLE
Interval logging alignment imperfect.

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#1359]
The initializeIntervalLogging(long nextPollTime) method in DataPointRT computes its delay if quantizing and sends that into a TimeTrigger. But, AbstractTimeTrigger will use timer.currentTimeMillis() in getFirstExecutionTime, making the quantize effort for naught! It could pass a Date instead in the constructor?

Giving this the bug label since the LOG on DPRT 396 seems to not correctly describe the situation. Isn't the intention that the first interval log should be at the nextPollTime + loggingPeriodMillis ?

**Comment by terrypacker** [comment]
Leaving open until we write tests around both normal polling and quantized polling accuracy.
