### ISSUE TITLE
Remove Jetty thread queue limit, implement QoS/DoS filter

### ISSUE THREAD

**Issue by jazdw** [infiniteautomation/ma-core-public#1360]
As per https://www.eclipse.org/lists/jetty-users/msg07972.html and https://github.com/eclipse/jetty.project/issues/2503

Jetty documentation for filters
https://www.eclipse.org/jetty/documentation/9.4.x/qos-filter.html
https://www.eclipse.org/jetty/documentation/9.4.x/dos-filter.html
https://www.eclipse.org/jetty/documentation/9.4.x/limit-load.html

**Comment by terrypacker** [comment]
QoS Filter is implemented on a branch as of this commit https://github.com/infiniteautomation/ma-core-private/commit/027b05ce37e03b1466c01df99c0af3a6016014fe 

Below are the corresponding env properties

#Jetty QoS settings
#The maximum number of requests to be serviced at a time. The default is 10.
web.qos.maxRequests=
#The length of time, in milliseconds, to wait while trying to accept a new request. Used when the maxRequests limit is reached. Default is 50 ms
web.qos.waitMs=
#Length of time, in milliseconds, that the request will be suspended if it is not accepted immediately. If not set, the container\u2019s default suspend period applies. Default is -1 ms.
web.qos.suspendMs=

**Comment by terrypacker** [comment]
DoS Filter is implemented on a branch as of this commit https://github.com/infiniteautomation/ma-core-private/commit/34c2bbf1be40d5455d5aea0cb923ae7a3ced2347

Below are the corresponding env properties, the defaults should be reviewed as they are from the Jetty documentation but I don't think all apply to our situation:

```
#Jetty DoS Settings
#Maximum number of requests from a connection per second. Requests in excess of this are first delayed, then throttled. Default is 25.
web.dos.maxRequestsPerSec=
#Delay imposed on all requests over the rate limit, before they are considered at all
#  100ms default, -1 = Reject request, 0 = no delay, any other value is delay in ms
web.dos.delayMs=
#Length of time, in ms, to blocking wait for the throttle semaphore. Default is 50 ms.
web.dos.maxWaitMs=
#Number of requests over the rate limit able to be considered at once. Default is 5.
web.dos.throttledRequests=
#Length of time, in ms, to async wait for semaphore. Default is 30000L.
web.dos.throttleMs=
#Length of time, in ms, to keep track of request rates for a connection, before deciding that the user has gone away, and discarding it. Default is 30000L.
web.dos.maxIdleTrackerMs=
#If true, insert the DoSFilter headers into the response. Defaults to true.
web.dos.insertHeaders=
#If true, usage rate is tracked by session if a session exists. Defaults to true.
web.dos.trackSessions=
#If true and session tracking is not used, then rate is tracked by IP and port (effectively connection). Defaults to false.
web.dos.remotePort=
#A comma-separated list of IP addresses that will not be rate limited.
web.dos.ipWhitelist=
```

**Comment by terrypacker** [comment]
It is probably worth noting that when delayed do to the DoS filter you receive this header: 

`DoSFilter: delayed`

**Comment by terrypacker** [comment]
Low resource management has been added with this commit: https://github.com/infiniteautomation/ma-core-private/commit/2732f9454c7fc629f809364f8895c2534cfebf6e

Here are the relevant env.properties, again we should review the defaults.
```
#Jetty Low Resource Management (Used to attempt to free resources when under heavy load)
#Period in ms to check for a low resource condition default 1000
web.lowResource.checkPeriod=
#In low resource condition all existing connection idle timeouts are set to this value default 1000
web.lowResource.lowResourcesIdleTimeout=
#check connectors executors to see if their ThreadPool instances that are low on threads default true
web.lowResource.monitorThreads=
#Maximum number of allowed connections default 5000
web.lowResource.connectionLimit=
#The maximum memory in MB in use before low resources is triggered default to 90% JVM memory, 0 means don't check
web.lowResource.maxMemoryMB=
#The time in milliseconds that a low resource state can persist before the low resource idle timeout is reapplied to all connections default 5000
web.lowResource.maxLowResourceTime=
```

**Comment by terrypacker** [comment]
The only remaining item is to remove the thread pool limits in the Lifecycle.  Just not 100% sure how that should end up looking.

**Comment by jazdw** [comment]
We should probably look at removing com.serotonin.m2m2.web.mvc.spring.security.RateLimitingFilter when we merge this. At least the per IP rate limiter.

**Comment by terrypacker** [comment]
The filters and settings are in main now.  I will need help with the final 2 outstanding parts of this:

- [ ] `com.serotonin.m2m2.web.mvc.spring.security.RateLimitingFilter` changes
- [ ] Remove Jetty Thread Pool maximum queue size for it's thread queue

**Comment by terrypacker** [comment]
A few notes about removing the `RateLimitingFilter` completely, both the ip and user based limiting:

**DoS Filter**
The DoS filter does essentially the same thing but doesn't allow a 'burst rate` setting or allowing different rate limits for authenticated users vs. anonymous requests.  From the docs:

> Jetty places throttled requests in a priority queue, giving priority first to authenticated users and users with an HttpSession, then to connections identified by their IP addresses. Connections with no way to identify them have lowest priority.

Potential additions to the DoS filter setup as it sits now:

1.  Separate it into 2 filters, one for web requests and another for REST requests so the limits can be configured separately.
2. Override the RateTracker use so that we can allow different rates for authenticated users vs. anonymous requests.

**QoS Filter**
The QoS filter allows us to prioritize requests based on criteria. 
>The default request priorities assigned by the QoSFilter are:
>2 — For any authenticated request
>1 — For any request with a non-new valid session
>0 — For all other requests

This allows us to prioritize requests for logged in users but we may want to take this further and prioritize superadmin users higher etc.

**Comment by terrypacker** [comment]
Another enhancement that isn't necessary but likely make splitting these filters into web vs. rest variants easier is to make them Spring managed beans.

**Comment by jazdw** [comment]
Increased the max thread limit -
infiniteautomation/ma-core-private@7f8815f536959b8e05a89b54a2b13c319f56d463

**Comment by jazdw** [comment]
I get a butt load of `DOS ALERT` messages in my log (approx 132 of them) when loading the legacy UI /login.htm page. Only 3-4 requests are actually being made to the server, the rest of the resources are being loaded from the browser cache so I am not sure why it is generating so many messages.

**Comment by jazdw** [comment]
OK, figured it out. It was only happening when I had the dev tools open. It was trying to load the JS and CSS source maps, but the requests were not shown on the network tab.

**Comment by terrypacker** [comment]
@jazdw do you think we should provide an env property to enable/disable these filters?

**Comment by terrypacker** [comment]
@jazdw I also have made the DoS Filter for only type REQUEST as per the JavaDoc:

This filter should be configured for {@link DispatcherType#REQUEST} and {@link DispatcherType#ASYNC} and with
 * <code>&lt;async-supported&gt;true&lt;/async-supported&gt;</code>.

**Comment by terrypacker** [comment]
@jazdw I'm ready to close this but I think we should at least discuss the default for `web.dos.maxRequestsPerSec=25` This is going to make a lot of people ask questions when they first look at the logs as it will contain many of these messages:

`WARN  2019-11-20T12:12:21,262 (org.eclipse.jetty.servlets.DoSFilter.doFilter:356) - DOS ALERT: Request delayed=100ms, ip=127.0.0.1,...`

But I guess it is doing its job so not really confident on changing it either.

**Comment by jazdw** [comment]
No I agree, we should make the default higher so we don't see it under normal usage.

**Comment by terrypacker** [comment]
Setting it to 50 you see a few on first login, after I set it to 75 I have not seen any after navigating around most of the UI with a fresh cache.

**Comment by jazdw** [comment]
That's quite high, we should really get all the module JS bundled into a single file. However for now lets just raise the limit, we can lower it back down again once we get that sorted.
