### ISSUE TITLE
Data point limit prevents Mango from starting at all

### ISSUE THREAD

**Issue by jazdw** [infiniteautomation/ma-core-public#1362]
I don't think this is how we want Mango to behave, I'm not sure how you get into this situation but I think we should give a 10 minute grace period so the admin can login and delete points.

https://forum.infiniteautomation.com/topic/3913/mango-wont-start-with-300-data-points

**Comment by terrypacker** [comment]
Agreed, we can start a timer task for 10 minutes after startup.  Another option is to disable the ability to start data sources via the Runtime Manager so that no more data can be collected.

**Comment by Puckfist** [comment]
I made it use the timer that would be used if you violated that restriction while Mango was running, which is an hour
