### ISSUE TITLE
UsersService - Permissions/Validation Logic Review

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#1380]
For 3.6.0 we are adding a UsersService to provide the logic to allow/deny the various restrictions on User access for CRUD operations.  

The proposed logic for creation:
1. Only admin users can create other users

The proposed logic for update:
1.   Cannot make yourself not admin
2.  Cannot disable yourself
3.  Only administrators can update privileges
4.  Cannot rename a user to an existing user
5.  A non admin user can only update themselves if they have the global user.edit.self permission.

**Comment by terrypacker** [comment]
We need to consider the MangoSessionRegistry when modifying Users and how to update the sessions/expire them.  For example that currently happens inside the v1 REST controller and Dao but could be moved to account for JSON Config Imports, Javascript executed updates via Dao etc.

**Comment by terrypacker** [comment]
@jazdw can an admin user lock their own password?  Only admins are allowed to lock passwords.

**Comment by jazdw** [comment]
>  can an admin user lock their own password?

No they should not be able to lock themselves out.

**Comment by terrypacker** [comment]
Note that users are currently allowed to change their username.

**Comment by terrypacker** [comment]
There is a fairly comprehensive test userV2.spec.js in the api module to prove all is working.  We should review and see if I missed any conditions that should be tested

**Comment by jazdw** [comment]
> Note that users are currently allowed to change their username.

Probably should add a permission for this.

**Comment by terrypacker** [comment]
Created an issue for the username change permission feature. #1516
