### ISSUE TITLE
Cloud connect timeout not configurable

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#1383]
Revealed in support ticket # 38569, it would appear a user is getting 504 status codes while trying to do long running requests through a cloud connect proxy. Specifically, he was trying to export the data points on the new import / export page.

**Comment by jazdw** [comment]
Fixed for 3.6.x
https://github.com/infiniteautomation/ma-modules-proprietary/commit/7d4835b9a93e63ae46b3f042733d5dc1b6d9a3da
