### ISSUE TITLE
Default REST API format is CSV rather than JSON

### ISSUE THREAD

**Issue by jazdw** [infiniteautomation/ma-core-public#1386]
Order of Spring converters needs to be changed to restore behavior that was present prior to splitting Spring contexts.

**Comment by terrypacker** [comment]
So these are now defined separately for each context in the 'configureMessageConverters()' method:

[v1](https://github.com/infiniteautomation/ma-modules-public/blob/main/Mango%20API/src/com/infiniteautomation/mango/rest/v2/MangoRestDispatcherConfiguration.java)

 [v2](https://github.com/infiniteautomation/ma-modules-public/blob/main/Mango%20API/src/com/infiniteautomation/mango/rest/v2/MangoRestDispatcherConfiguration.java)

From what I can tell this is the last version of the original file for the combined contexts:

[original](https://github.com/infiniteautomation/ma-core-public/blob/de12119ed9eb05987c43343ece1dfd8c2c3f0ba9/Core/src/com/serotonin/m2m2/web/mvc/spring/MangoRestDispatcherConfiguration.java)
