### ISSUE TITLE
Mulitstate Statistics Are Buggy

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#141]
When reviewing the Starts and Runtime for the Statistics they don't seem correct for my data set while importing from the Persistent TCP Data source.

This has been confirmed.  The Runtime for the statistics seems to contain one entry for a state that is much higher than the others and not possibly correct.

This will need a test upon completion.

**Comment by Puckfist** [comment]
In trying to track this down, I have the stack trace attached, but it seemed like i hadn't done anything I really shouldn't have.

[multistate tcppub.txt](https://github.com/infiniteautomation/ma-core-public/files/69045/multistate.tcppub.txt)

**Comment by Puckfist** [comment]
Testing revealed this was caused by discard ranges set to Infinity and -Infinity

**Comment by Puckfist** [comment]
Cannot duplicate. I have it publishing to the same system it's from and checking the statistics of the origin and the target against each other in a script. Seems to be working.
