### ISSUE TITLE
No change / update detectors initialization not so consistent

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#1411]
If a point has a five minute no change detector, and the point got a value exactly four minute ago and then was stopped and started again, then line 56 of DifferenceDetectorRT is not met, so call scheduleJob(), but that schedules the task for five minutes from now, even though the update was four minutes ago!

**Comment by terrypacker** [comment]
With the new changes I'm working on in the event-detectors-bugs branch we need to review the timestamp with which we are raising/RTN the events during initializeState()
