### ISSUE TITLE
JavaScript context points use context's runtime

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#1419]
Should a meta point, for instance, execute with some delay (maybe it's the second meta point in the context update and the first slept, maybe garbage collection), then the timestamp and the runtime passed to the javascript service will be different (or maybe if an execution delay is used, didn't look). Then, calls to statistics functions in the various extenders of AbstractPointWrapper will use the delayed runtime for the range of the point values to compute over, while the timestamp will be used to log the resulting value. Perhaps this is misleading? I would recommend either changing it to use the timestamp or using the "compute" time in WrapperContext (which would need to be exposed), which should maybe default to the timestamp in the WrapperContext.

**Comment by terrypacker** [comment]
This work is done on the java-script-optimization branch.
