### ISSUE TITLE
Numeric Point Statistics - Average changing

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#142]
When logging a numeric point on change, the average value continually (but very slightly) decreases when recomputed on the point details page.  This indicates that the average might be including a extra value of 0 or something?

**Comment by Puckfist** [comment]
This is probably still an issue stemming from the last point in the series, whose duration would be judged to be everything from its inception to now. The integral also displays this. I'm not sure it's a bug, but it doesn't seem like 'average' means 'sum of point values over quantity of values' and instead weights the average by the duration at the value.

**Comment by Puckfist** [comment]
A possible way to clarify this is to offer a second kind of statistics generator that operates under discreet quantity conditions rather than treating everything like it occurs continuously over time.

**Comment by terrypacker** [comment]
Closing this as acceptable the way it is.
