### ISSUE TITLE
TCP/IP data source retries don't really retry

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#1423]
My testing was against a Linux machine using netcat.

TcpIpDataSourceRT

I found if I ctrl+C'ed a poll to close the connection, then the next time the data source attempted to poll the channel.write(command) call was draining the command by the buffer into the old channel. The channel did not realize it was closed until it attempts to read from the stream a few lines later, only to get an IOException. It then closes the connection and reopens it, but it does not have the command in the 'command' ByteBuffer any more! So, it does not resend the command.

**Comment by Puckfist** [comment]
Found working this thread: https://forum.infiniteautomation.com/topic/4188/timeout-processing-with-tcp-ip-data-source

And additional recommendation involved checking for the termination character as the alleged "EOF" during reading.

**Comment by terrypacker** [comment]
Released with Mango 3.6
