### ISSUE TITLE
PointValueCache not thread safe

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#1427]
If multiple threads call savePointValueDirectToCache or the regular savePointValue in DataPointRT at the same time, the cache updating done in PointValueCache updatePointValue and savePointValue have no synchronization mechanism, but they avoid causing concurrent modification errors.

**Comment by terrypacker** [comment]
This was fixed in 1bbf5919281ca477de3666de8d8412aadebef84a
