### ISSUE TITLE
User defined file locations

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#1439]
Allow all application generated data and configuration file locations to be user defined.  Many locations used by Mango are based on MA_HOME, this is not ideal for being able to separate the application from its data.

Some things to review:

- [x]  logfiles
- [x] SQL backups
- [x] Config file backups
- [x] Mango NoSQL module backup
- [x] overrides
- [x] module persist paths
- [x] m2m2.licence.xml location
- [ ] bin/ma.pid file for Linux start script
- [x] Common.TEMP_PATH defaults to the work directory (See https://github.com/infiniteautomation/ma-core-public/issues/1538)
- [x] Excel Reports (Generated Reports are in module's `web/report-data` folder)
- [x] Safe mode trigger file is located at MA_HOME/SAFE
- [x] Restart mode trigger file is located at MA_HOME/RESTART
- [x] H2Proxy creates backup at MA_HOME/backup when upgrading H2 page store
- [x] Consider the use of File.newTempFile (or whatever that is) System property `java.io.tmpdir`
- [x] Specify log4j2.xml path without putting it on classpath
- [ ] Update start scripts and installer scripts (also check for new SAFE/RESTART/DELETE flag locations)
- [ ] Update bootstrap and windows service
- [ ] Update documentation
- [x] Remove overrides/classes and overrides/properties from classpath in services and scripts
- [x] Way to disable module/core upgrades via UI

**Comment by jazdw** [comment]
We should get rid of the MA_HOME environment variable and start mango by pointing the process at the env.properties configuration file.

**Comment by jazdw** [comment]
Another thing we should do as a part of this is to remove `overrides/properties` and just user `overrides/classes`

**Comment by terrypacker** [comment]
I'm not sure that the FTL templates being at MA_HOME/ftl matters.  Those are packaged with the core and should not be modified.  The overridden files should be at `OVERRIDES/ftl`

**Comment by terrypacker** [comment]
Ah nope never mind.  I'll leave that comment for reference but module FTLs are placed there on installation.

**Comment by jazdw** [comment]
We should load the freemarker FTL files from the classpath, see this stack trace provided by @Pacane 
```
java.io.FileNotFoundException: /data/ftl does not exist.
	at freemarker.cache.FileTemplateLoader$1.run(FileTemplateLoader.java:122) ~[freemarker-2.3.28.jar:2.3.28]
	at freemarker.cache.FileTemplateLoader$1.run(FileTemplateLoader.java:119) ~[freemarker-2.3.28.jar:2.3.28]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at freemarker.cache.FileTemplateLoader.<init>(FileTemplateLoader.java:119) ~[freemarker-2.3.28.jar:2.3.28]
	at freemarker.cache.FileTemplateLoader.<init>(FileTemplateLoader.java:98) ~[freemarker-2.3.28.jar:2.3.28]
	at com.serotonin.m2m2.Lifecycle.freemarkerInitialize(Lifecycle.java:716) ~[ma-priv-4.0.0-SNAPSHOT.jar:?]
	at com.serotonin.m2m2.Lifecycle.initialize(Lifecycle.java:285) ~[ma-priv-4.0.0-SNAPSHOT.jar:?]
	at com.serotonin.m2m2.Main.main(Main.java:144) ~[ma-priv-4.0.0-SNAPSHOT.jar:?]
```

**Comment by jazdw** [comment]
There's now a `paths.data` property which controls the variable data root, all databases, filestores etc are created under this directory. This defaults to `$MA_HOME` so the upgrade path is seamless.

**Comment by jazdw** [comment]
Closing this, opened new issue for remaining tasks #1706
