### ISSUE TITLE
JSON File Importer - Out of Memory Exception

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#145]
The importer can run out of memory when importing large amounts of Data source/data points.  This is most likely due to storing the parsed information (or Json Objects) in a list prior to inserting into the database.  

The correct approach will use streaming logic to push the data into the database as the import is running, never at any time should all the data from the import exist in memory.

**Comment by Puckfist** [comment]
I was able to import a 190Mb configuration (100000 points), which yielded some other issues, but this one seems handled.

**Comment by Puckfist** [comment]
This is not actually resolved. I was unable to import the attached on a system set Xms2g Xmx10g
[config.zip](https://github.com/infiniteautomation/ma-core-public/files/409489/config.zip)

**Comment by Puckfist** [comment]
Re-opening this was possibly in error. I noticed the system being set to Xmx10g was odd... it only has 8Gb!

Will retest

**Comment by Puckfist** [comment]
Yes, the poor memory setting was the cause
