### ISSUE TITLE
Simply rollup returns too simple a data set for chart?

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#1461]
I found on a point that had no values in the period that I was attempting to chart that using the simplify rollup returned an empty point value array with no bookends to set the chart boundaries.

**Comment by terrypacker** [comment]
This is a bug in the API.  However you must have `bookend:true` on the request to make it return bookends.

**Comment by terrypacker** [comment]
The tests prove this works.
