### ISSUE TITLE
Scripting Event Handler

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#1479]
Create a new event handler type that executes javascript.  This will probably have a set of context points and also leverage the additional info that we add to the context via #1478

**Comment by jazdw** [comment]
Largely complete
- Script engines are pluggable via JSR223 interfaces
- Scripts can also be run from the file store
- Services are exposed to scripting environment
- Scripts can load other scripts from the file store

**Comment by jazdw** [comment]
- [ ] Help and documentation
- [ ] Javadoc should be made available on website or inside of Mango
- [ ] Need script test functionality
