### ISSUE TITLE
Add a role/position field to users

### ISSUE THREAD

**Issue by jazdw** [infiniteautomation/ma-core-public#1485]
We have added a organization field to users, we also need a role/position field.

One thing we need to decide with this is what to label this new field as. The user's page already displays an input labeled "Roles (permission groups)". Perhaps we should label it as "Organizational role" or "Role within organization"? Please comment @Joelhaggar @terrypacker

**Comment by terrypacker** [comment]
I'll make the backend field named `organizationRole` and then the translation can be either of those mentioned above.  I'm leaning towards 'Role within organization', but either should be fine.

**Comment by terrypacker** [comment]
Also add JSON field for custom info that can be assigned to a user.
