### ISSUE TITLE
Implement CSV import/export function for event detectors

### ISSUE THREAD

**Issue by jazdw** [infiniteautomation/ma-core-public#1486]
We have no good way of bulk editing event detectors, we should allow CSV import/export of event detectors.

Columns needed:
- Data point XID (for linking detector to point)
- Data point name (display only)
- Data point device name (display only)
- Data point tags (display only)
- All event detector properties

We can use the GenericCSVMessageConverter for this.

Other avenues to explore later down the line include
- Allow storing high/low limits in data point itself and attaching a detector to multiple data points

**Comment by Craig-IAS** [comment]
I like the idea of adding high/low limits to the DP itself.  This is a common feature in most SCADAs. For binaries and mutlistate we could add an alarm state.
