### ISSUE TITLE
REST Controllers v2 Conversion

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#1522]
This is the list of REST controllers and UI code that will be ported to v2 for Mango 4.0

Excel Reports
- [x] GET `/rest/v1/excel-report-templates/email-templates`
- [x] GET `/rest/v1/excel-reports/download/{xid}`
- [x] GET `/rest/v1/excel-reports/view/{xid}`

AuditRestController
- [x] GET `/rest/v1/audit`

DeviceNameRestController
- [x] GET `/rest/v1/device-names`
- [x] GET `/rest/v1/device-names/by-data-source-id`
- [x] GET `/rest/v1/device-names/by-data-source-xid`

MangoIO Tools
- [ ] GET `/rest/v1/data-points/' + dataPoint.xid`
- [ ] GET `/rest/v1/data-points/data-source/' + dataSourceXid`
- [ ] All endpoints in v1 MangoIO controller
- [ ] POST `/rest/v1/modbus/serial/locator`
- [ ] POST `/rest/v1/modbus/serial/write`
- [ ] POST `/rest/v1/modbus/serial/read`
- [ ] 

ExampleRestControllerv2
- [x] move all methods to TestRestController

JsonDataRestController
- [x] fix v1 tests to pass in v2

LoggingRestController
- [x] fix v1 tests to pass in v2

ModulesRestController
- [x] ensure v2 controller has all the same endpoints

Point Value Rest Controller
- [x] PUT /rest/v1/point-values/{xid} no v2 variant

RuntimeManagerRestController
- [ ] no v1 tests need v2 tests

ThreadsRestController
- [x] move endpoints to server v2 controller

UI 
- [ ] scriptingEditor.html contains a reference to a v1 explain endpoint for data points
- [ ] `/v1/logging` needs to be converted to v2
- [ ] `/v1/modules` needs to be converted to v2
- [ ] `v1/json-data` needs to be converted to v2
- [ ] `/rest/v1/device-names` needs to be converted to v2
- [ ] `/rest/v1/audit` needs to be converted to v2
- [ ] PUT `/rest/v1/point-values` needs to be converted to v2
- [ ] `/rest/v2/realtime` has been removed for 4.0
- [ ] `/rest/v1/system-metrics` needs to be converted to v2
- [ ] `/rest/v1/system-settings` needs to be converted to v2
- [ ] `/rest/v1/threads` moved to `/rest/v2/server/threads`
- [ ] `/rest/v1/translations` needs to be converted to v2
- [ ] `/rest/v1/comments` needs to be converted to v2
- [ ] `/rest/v1/users` needs to use v2 and update to pickup model changes
- [ ] `/rest/v1/watch-lists` needs to be converted to v2
- [ ] `/rest/v1/work-items` needs to be converted to v2 

WatchlistRestController
- [ ] add v2 tests

Stallion
- [x] POST `/rest/v1/events/module-defined-query` for Maintenance Events will need to change URL to post to new MaintenanceEvents controller 
- [ ] GET `/rest/v2/realtime` this has been removed and we will need an alternate solution

Maintenance Events
- [ ] POST `/rest/v1/events/module-defined-query` for Maintenance Events will need to change URL to post to new MaintenanceEvents controller

**Comment by jazdw** [comment]
I have added auto generated tests for the following v1 APIs:
- audit-rest-controller
- device-name-controller
- json-data-rest-controller
- logging-rest-controller
- modules-rest-controller
- runtime-manager-rest-controller
- system-metrics-rest-controller
- system-settings-rest-controller
- thread-monitor-rest-controller
- translations-rest-controller
- user-comment-rest-controller
- work-item-rest-controller

**Comment by jazdw** [comment]
V2 events issues that need to be addressed / or comments added to release notes about changes:
- [ ] Can no longer query on dataPointId
- [ ] Model eventType no longer has a dataPointId property (but confusingly still has a dataSourceId property)
- [ ] Model no longer has an active property

**Comment by terrypacker** [comment]
@jazdw as for the watchlist monitor point, the dao changed packages and that needed to be updated in the Internal data source module. Keep an eye out for others that are missing, I did a quick check and didn't see any others yet.

**Comment by terrypacker** [comment]
@jazdw 

> Model eventType no longer has a dataPointId property (but confusingly still has a dataSourceId property)

This is how the new event types in v2 work.  The data point event type as a data source ID in addition to the reference1 = data point and reference2 = point event detector.  We designed the event types endpoint to work this way.

**Comment by jazdw** [comment]
> This is how the new event types in v2 work. The data point event type as a data source ID in addition to the reference1 = data point and reference2 = point event detector. We designed the event types endpoint to work this way.

Ah I was thinking that ref2 was the dataSourceId. That makes more sense.

**Comment by terrypacker** [comment]
Thanks, we removed that module and Reports.  So these 2 will also be gone: 

`internal_mango_num_reports`
`internal_mango_num_report_instances`

**Comment by jazdw** [comment]
Still seeing the duplicate events come through on the WebSocket and on the REST API, same timestamp, message etc but different ID.
![image](https://user-images.githubusercontent.com/3579645/73373452-e0e60800-4275-11ea-989d-8a582a8602b4.png)

**Comment by terrypacker** [comment]
The script context variable model that was previously used in v1 is gone and the pre-existing v2 model is slightly different, the `dataPointXid` field is now `xid`.  We need to update the UI code for these 2 modules:

- [ ]  Meta Data Source (Point locator)
- [ ]  Scripting Data Source

**Comment by terrypacker** [comment]
- [ ] User permissions are a Set<String> in v2.  @jazdw The model existed before the upgrade so I think we will need to modify the UI.

**Comment by terrypacker** [comment]
Released and in production
