### ISSUE TITLE
Mango 4.0 Query Optimization

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#1525]
For Mango 4.0 I have identified these RQL queries from the UI that will need optimization:

- [ ] Watchlist loading of points for new list https://localhost:8443/rest/v2/data-points?limit(10000) the bulk of the time is spent loading the tags via loadRelationalData(). Do we really need 10,000 points here? Pagination?

- [ ] Data source point tab GET https://localhost:8443/rest/v2/data-points?eq(dataSourceXid,tuna-melt8-1000-points)&limit(100000) 100k?  Should pagenate.

- [x] Data Sources GET https://localhost:8443/rest/v2/data-sources?limit(1000) What if you have > 1000 data sources?

- [ ] Event Handlers listing data point event types GET https://localhost:8443/rest/v2/event-types/DATA_POINT/null should implement pagination in the UI.  This is supported by supplying RQL.

- [ ] Event Handlers listing data source event types GET https://localhost:8443/rest/v2/event-types/DATA_SOURCE/null should implement pagination in the UI.  This is supported by supplying RQL.

- [x] Bulk data point edit https://localhost:8443/rest/v2/device-names should implement a specific query and not get the entire data point inside the REST controller

- [ ] Watchlist builder when creating tag type list.  The unique tag values should be paginated as when you open a drop down it makes this type of query: GET https://localhost:8443/rest/v2/data-point-tags/values/name which for superadmin can return every point in the system.

- [ ] Watchlist view when displaying a list there is an events query made for every data point in the list.  GET https://localhost:8443/rest/v2/events?eq(eventType,DATA_POINT)&eq(referenceId1,31)&eq(active,true). 

- [ ] Data Point Details GET https://localhost:8443/rest/v2/data-point-tags/keys this could benefit from using a GROUP BY instead of SELECT DISTINCT.  Performance improvement there is minimal (1%) but this query can become slow on very large systems.  On my system with 2m tags this takes ~9.8s with DISTINCT and 9.5s with GROUP BY.  Ideally we can find a better solution.  NOTE this was done with a user who had permission to almost every point but was not superadmin.  

- [ ] Users GET http://localhost:8443/rest/v2/users?sort(username,id)&limit(50,50) is slow (15 seconds on our dev server with 100 or so users). This has to do with the `getGrantedPermissions()` call on the User.  It repeatedly makes call for all roles for every permission definition for every user.  I think the solution here is to perform a Query against the database instead of get all the roles and check them in code.

- [ ] Users GET http://localhost:8443/rest/v2/users/user-groups this will return every role that the user can see.  For superadmin this is everything, with 5M roles this crashes the browser.

**Comment by terrypacker** [comment]
@jazdw some of these should be simple UI changes to use a different limit, others might take sometime to use pagination if it isn't supported in the used component. 

Can you take a look at them.  Feel free to edit the description to add more info or make individual issues that I can pass on to our other developers.

**Comment by jazdw** [comment]
Data Source query for points like `/rest/v2/data-points?eq(dataSourceXid,tuna-melt8-1000-points)&limit(100000)` is done because I need all the data points for the data source in order to do the bulk edit functions.

Is the implicit limit of 100 still present for all REST queries?

**Comment by terrypacker** [comment]
Yes, but I would consider removing that...

https://github.com/infiniteautomation/ma-core-public/blob/35e6b8a2984c70da36f275dd9f80c5738402d6fa/Core/src/com/infiniteautomation/mango/db/query/ConditionSortLimit.java#L27

**Comment by terrypacker** [comment]
I took a crack at improving  http://localhost:8443/rest/v2/users?sort(username,id)&limit(50,50) by executing a count on the role mapping table to see if the user has any roles in a permission.  This did slightly improve performance.  However I think these queries are all fast but the fact that we make a query for every permission for every user then we end up making 50 * 45 = 2,250 queries to get only 50 users.  I think we are going to have to cache the roles for a permission definition inside the definition.  When I fix up this issue I'll re-visit this idea: #1523

**Comment by terrypacker** [comment]
Closing and will re-open as new performance issues are found.  Most of these queries have changed since this was open.
