### ISSUE TITLE
Load unsigned modules in development mode

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#1537]
Fix up the REST and lifecycle to only load unsigned modules in development mode.

**Comment by jazdw** [comment]
- The modules REST controller should stop you from uploading the module in the first place and tell you that it is unsigned
- The core should not unpack the module if the .zip is unsigned

**Comment by terrypacker** [comment]
Finished with this commit: 7b2fddc9299b747e8d7a99f90780e912936e2031

**Comment by terrypacker** [comment]
All 3 features added.  The endpoint will fail if no modules are installed and will return some feedback if some are.
