### ISSUE TITLE
Add Log location/tool to UI for all modules that use this setting

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#1545]
Any Data Source that has logging inputs should display the location of the log file and a way to view it.  This will use the concept from #319

Modules that require this change:
- [x] Scripting data source
- [x] Meta data source
- [x] ssh data source
- [x] modbus data source
- [x] serial data source
- [x] tcp ip data source

**Comment by jazdw** [comment]
You should link to the logging console page using a button or `<a>` element with a `ui-state` attribute like this - `ui-state="'ui.settings.systemStatus.loggingConsole'" ui-state-params="{logFileFilter: 'ma.log', displayLogFile: 'ma.log'}"`

**Comment by jazdw** [comment]
These are implemented now 
![image](https://user-images.githubusercontent.com/3579645/75849640-6e9ab180-5e39-11ea-92dd-9e4a7a7b755f.png)
![image](https://user-images.githubusercontent.com/3579645/75849672-8bcf8000-5e39-11ea-9ed0-0f042cf56858.png)

**Comment by terrypacker** [comment]
Confirmed all data sources look/work as expected.
