### ISSUE TITLE
Ability for User to send email to request account registration

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#1553]
This will be an endpoint that generates a token with this information to be used when the User is created upon registration:

Organization
Roles

When a publicly registered user registers an email is then sent to the User who generated the link/token/email.  If it is just a public registration then that information is not present in the registration token and no email is sent and the user just remains disabled.

This implies that we will be actioning a new user being created and automate the activation process by sending an email to whoever generated the link to send to the new user.

**Comment by Joelhaggar** [comment]
I think read & edit permissions and the creating users email also need to be in the token.

**Comment by terrypacker** [comment]
Not doing this, removed from project scope.
