### ISSUE TITLE
None level event label is confusing

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#1563]
We have 3 alarms levels that seem to cause confusion.

1.  None - Just a label for the lowest event level 
2.  Do Not Log - Does not go into DB, does not raise user events i.e. web socket messages, does get handled and does go into active events list 
3.  Ignore - Do absolutely nothing

We are proposing renaming 1 to 'Lowest' to indicate that it is definitely a normal event type that does not fall into a special class.

**Comment by Joelhaggar** [comment]
I kinds of like "Not Important", I don't think Lowest will really make sense.

**Comment by terrypacker** [comment]
@jazdw and @Joelhaggar how about "Low Importance" maybe a little more wordsmithy.

**Comment by jazdw** [comment]
I don't like including the word "important" in it. It conveys that there is a relationship with the important level. I think a level named "lowest" makes more sense.

**Comment by Joelhaggar** [comment]
What is wrong if someone sees a relationship with important and unimportant?  I think all the alarm levels relate to each other and Not Important or Low Importance would be logical to have if we also have Important, warning, etc.  Lowest doesn't assign the alarm a value and is more similar to "none"  in my mind.  From the user perspective, Not Important will create fewer questions than "Lowest"

**Comment by jazdw** [comment]
Your call.

**Comment by Craig-IAS** [comment]
I think "Minor" is descriptive and fits in with the rest of the levels

**Comment by terrypacker** [comment]
Changed to Minor
