### ISSUE TITLE
Script Context Variable Model

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#1564]
In the removal of the v1 REST api there are differences in the script context variable model.  Previously the model used `dataPointXid` to hold the xid of the context point.  In v2 we now use `xid`. I found that you cannot add context points to a meta data point because it is putting the xid into `dataPointXid` which does not end up on the backend.

We need to review the UI for:

- [x] Meta data source
- [ ] Scripting data source
- [ ] Email event handler
- [ ] Set point event handler

**Comment by guetteluis** [comment]
this is happening only in **Meta data source** and it is because of `context-var-xid-name` in here:

```
<ma-script-context 
            name="context"
            context-var-xid-name="'dataPointXid'" 
            updates-context="true" 
            ng-model="$ctrl.dataPoint.pointLocator.context" 
            ng-change="$ctrl.updateContext()"
            ma-get-ctrl="contextModelCtrl = $ngModel">
</ma-script-context>
```

I will create a branch and make PR to fix this

**Comment by terrypacker** [comment]
Fixed via https://github.com/infiniteautomation/ma-modules-private/pull/164 

The only problem was with meta points.

**Comment by pierpuccini** [comment]
Below showing that scripting validation already includes the xid key and not dataPointXid
<img width="2160" alt="Screen Shot 2020-04-07 at 4 26 04 PM" src="https://user-images.githubusercontent.com/46226655/78721083-7e039380-78ec-11ea-90bd-0e43cd204ad2.png">

**Comment by pierpuccini** [comment]
Below showing that Email event handler validation already includes the xid key and not dataPointXid

<img width="2160" alt="Screen Shot 2020-04-07 at 4 39 35 PM" src="https://user-images.githubusercontent.com/46226655/78722076-60372e00-78ee-11ea-9451-2cee24a3eda7.png">

**Comment by pierpuccini** [comment]
Below showing that Set point event handler validation already includes the xid key and not dataPointXid

<img width="2048" alt="Screen Shot 2020-04-07 at 4 56 19 PM" src="https://user-images.githubusercontent.com/46226655/78723240-b7d69900-78f0-11ea-9c1b-8ab6d1db161e.png">
