### ISSUE TITLE
Large Point Value Import Memory Usage - Mango NoSQL

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#157]
Due to the potential update/insert of backdated points using the Point Value Import Module  memory management techniques need to be implemented.  See the code for data Migration to throttle the import.

**Comment by terrypacker** [comment]
Not an immediate problem as no one is mentioning problems.

**Comment by Puckfist** [comment]
Closing. We implemented backdate batching which is tune-able and handles some serious insert loads.
