### ISSUE TITLE
Add DB upgrade for JsonDataVO publicData

### ISSUE THREAD

**Issue by jazdw** [infiniteautomation/ma-core-public#1584]
We need to upgrade all JsonDataVO with publicData = true and add the anonymous role to their read permissions.

**Comment by jazdw** [comment]
We also need to handle legacy JSON configuration import for publicData.

**Comment by terrypacker** [comment]
Reference commit for JSON emport:

c160990f8fff9f5a76a3472f1b5a143eaae62d6f
