### ISSUE TITLE
null tag value not being returned from REST

### ISSUE THREAD

**Issue by jazdw** [infiniteautomation/ma-core-public#1591]
A null value should be returned by the tags REST API if there are datapoints present/visible to the user which do not have that tag.

It works for a query with restrictions, e.g.
`/rest/v2/data-point-tags/values/site?in(device,devA)`
But not for
`/rest/v2/data-point-tags/values/site`

**Comment by terrypacker** [comment]
- [ ] Test final solution as non-admin as the queries are different

**Comment by terrypacker** [comment]
Won't fix this
