### ISSUE TITLE
RQLUtils - DEFAULT_NODE can get modified

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#1592]
I just found that the RQL Utils class can end up with a corrupted default node which then makes all empty queries use the new restriction.  The only way to recover is to restart Mango.

On line 373 of UserRestController is a good example of how this happens:
```
        if (!service.getPermissionService().hasAdminRole(user)) {
            // Add some conditions to restrict based on user permissions
            rql = RQLUtils.addAndRestriction(rql, new ASTNode("eq", "id", user.getId()));
        }
```

One solution is to not keep a reference to this node and just create an new and node instead of using this.

**Comment by jazdw** [comment]
Probably should backport this and release for 3.7

**Comment by terrypacker** [comment]
@jazdw I don't think this can happen in 3.7.  I took a look yesterday and the default node is a limit node so those methods will always create a new node and not add an argument to it.

**Comment by jazdw** [comment]
OK cool, that's good then
