### ISSUE TITLE
Role REST Behavior 

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#1604]
- [x] expose inherited roles on a user in the model
- [x] send User web socket notification when a user's roles have changed UPDATE
- [x] Ensure that the Role websocket sends updates for any roles whose inherited roles have changed
- [x] change the User `permissions` field to `roles`

**Comment by terrypacker** [comment]
User model change: e2e7328f13735ff5152a8da850930eaca1981710

**Comment by jazdw** [comment]
FYI role WebSocket does not work at all. I do not get any create/update/delete notifications on it.

**Comment by terrypacker** [comment]
@jazdw I suspect the inherited roles in the model is wrong, we should discuss this.  It is labeled on the permission holder to be `The roles for this permission holder, including all inherited roles` which is likely not exactly what you wanted.
