### ISSUE TITLE
User - Sync User Handler with Roles and Inherited Roles

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#1608]
I just noticed the method on a user named `equalsImportExport`, this does not take roles or inherited roles into account.  I suspect you will need to synchronize the roles between the 2 systems for this to work.

**Comment by jazdw** [comment]
I made it only assign roles to a user which currently exist on the client. It made no sense to sync the roles as no permissions would have these roles anyway.

Reference
infiniteautomation/ma-modules-proprietary@ca855a04ceaecf5a38a7206816aa03fe226cad77
