### ISSUE TITLE
Upgrade from v3.7.8 to v4-snapshot

### ISSUE THREAD

**Issue by Craig-IAS** [infiniteautomation/ma-core-public#1611]
- Upgrade failed
`INFO  2020-08-12T21:05:50,712 (com.serotonin.m2m2.Main.createLifecycle:124) - Starting Mango 4.0.0-SNAPSHOT with Schema Version: 30
INFO  2020-08-12T21:05:50,719 (com.serotonin.m2m2.Main.createLifecycle:128) - Java VM: OpenJDK 64-Bit Server VM, version: 13.0.2+8, vendor: AdoptOpenJDK
INFO  2020-08-12T21:05:50,721 (com.serotonin.m2m2.Main.createLifecycle:129) - Java spec: Java Virtual Machine Specification, version: 13, vendor: Oracle Corporation
INFO  2020-08-12T21:05:50,722 (com.serotonin.m2m2.Main.createLifecycle:135) - Operating System: Mac OS X, arch: x86_64, version: 10.15.5
INFO  2020-08-12T21:05:50,826 (com.serotonin.m2m2.Main.openZipFiles:228) - Upgrading module dnp3
INFO  2020-08-12T21:05:50,853 (com.serotonin.m2m2.Main.openZipFiles:228) - Upgrading module zwave
INFO  2020-08-12T21:05:50,997 (com.serotonin.m2m2.Main.openZipFiles:228) - Upgrading module mbus
INFO  2020-08-12T21:05:51,022 (com.serotonin.m2m2.Main.openZipFiles:228) - Upgrading module snmp
INFO  2020-08-12T21:05:51,040 (com.serotonin.m2m2.Main.openZipFiles:228) - Upgrading module meta
INFO  2020-08-12T21:05:51,050 (com.serotonin.m2m2.Main.openZipFiles:228) - Upgrading module BACnet
INFO  2020-08-12T21:05:51,075 (com.serotonin.m2m2.Main.openZipFiles:228) - Upgrading module dataFile
INFO  2020-08-12T21:05:51,087 (com.serotonin.m2m2.Main.openZipFiles:228) - Upgrading module excelReports
INFO  2020-08-12T21:05:51,108 (com.serotonin.m2m2.Main.openZipFiles:228) - Upgrading module pid
INFO  2020-08-12T21:05:51,119 (com.serotonin.m2m2.Main.openZipFiles:228) - Upgrading module lang_es
INFO  2020-08-12T21:05:51,125 (com.serotonin.m2m2.Main.openZipFiles:228) - Upgrading module lang_fi
INFO  2020-08-12T21:05:51,131 (com.serotonin.m2m2.Main.openZipFiles:228) - Upgrading module watchlists
INFO  2020-08-12T21:05:51,146 (com.serotonin.m2m2.Main.openZipFiles:228) - Upgrading module lang_zh
INFO  2020-08-12T21:05:51,152 (com.serotonin.m2m2.Main.openZipFiles:228) - Upgrading module mangoNoSqlDatabase
INFO  2020-08-12T21:05:51,167 (com.serotonin.m2m2.Main.openZipFiles:228) - Upgrading module mangoESConfiguration
INFO  2020-08-12T21:05:51,183 (com.serotonin.m2m2.Main.openZipFiles:228) - Upgrading module MangoIOTools
INFO  2020-08-12T21:05:51,190 (com.serotonin.m2m2.Main.openZipFiles:228) - Upgrading module twilio
INFO  2020-08-12T21:05:51,235 (com.serotonin.m2m2.Main.openZipFiles:228) - Upgrading module lang_de
INFO  2020-08-12T21:05:51,240 (com.serotonin.m2m2.Main.openZipFiles:228) - Upgrading module vmstat
INFO  2020-08-12T21:05:51,248 (com.serotonin.m2m2.Main.openZipFiles:228) - Upgrading module maintenanceEvents
INFO  2020-08-12T21:05:51,257 (com.serotonin.m2m2.Main.openZipFiles:228) - Upgrading module egauge
INFO  2020-08-12T21:05:51,264 (com.serotonin.m2m2.Main.openZipFiles:228) - Upgrading module serial
INFO  2020-08-12T21:05:51,271 (com.serotonin.m2m2.Main.openZipFiles:228) - Upgrading module onewire
INFO  2020-08-12T21:05:51,283 (com.serotonin.m2m2.Main.openZipFiles:228) - Upgrading module mqttClientDataSource
INFO  2020-08-12T21:05:51,293 (com.serotonin.m2m2.Main.openZipFiles:228) - Upgrading module cloudConnect
INFO  2020-08-12T21:05:51,313 (com.serotonin.m2m2.Main.openZipFiles:228) - Upgrading module TCPIP
INFO  2020-08-12T21:05:51,319 (com.serotonin.m2m2.Main.openZipFiles:228) - Upgrading module http
INFO  2020-08-12T21:05:51,331 (com.serotonin.m2m2.Main.openZipFiles:228) - Upgrading module log4JReset
INFO  2020-08-12T21:05:51,336 (com.serotonin.m2m2.Main.openZipFiles:228) - Upgrading module lang_nl
INFO  2020-08-12T21:05:51,341 (com.serotonin.m2m2.Main.openZipFiles:228) - Upgrading module log4jDS
INFO  2020-08-12T21:05:51,346 (com.serotonin.m2m2.Main.openZipFiles:228) - Upgrading module ssh
INFO  2020-08-12T21:05:51,355 (com.serotonin.m2m2.Main.openZipFiles:228) - Upgrading module sqlds
INFO  2020-08-12T21:05:51,365 (com.serotonin.m2m2.Main.openZipFiles:228) - Upgrading module sstGlobalScripts
INFO  2020-08-12T21:05:51,371 (com.serotonin.m2m2.Main.openZipFiles:228) - Upgrading module lang_pt
INFO  2020-08-12T21:05:51,380 (com.serotonin.m2m2.Main.openZipFiles:228) - Upgrading module dashboardDesigner
INFO  2020-08-12T21:05:51,397 (com.serotonin.m2m2.Main.openZipFiles:228) - Upgrading module internal
INFO  2020-08-12T21:05:51,405 (com.serotonin.m2m2.Main.openZipFiles:228) - Upgrading module asciiFile
INFO  2020-08-12T21:05:51,411 (com.serotonin.m2m2.Main.openZipFiles:228) - Upgrading module mangoApi
INFO  2020-08-12T21:05:51,423 (com.serotonin.m2m2.Main.openZipFiles:228) - Upgrading module slackPublisher
INFO  2020-08-12T21:05:51,475 (com.serotonin.m2m2.Main.openZipFiles:228) - Upgrading module controlcore
INFO  2020-08-12T21:05:51,490 (com.serotonin.m2m2.Main.openZipFiles:228) - Upgrading module envcands
INFO  2020-08-12T21:05:51,506 (com.serotonin.m2m2.Main.openZipFiles:228) - Upgrading module lang_en
INFO  2020-08-12T21:05:51,516 (com.serotonin.m2m2.Main.openZipFiles:228) - Upgrading module opcda
INFO  2020-08-12T21:05:51,539 (com.serotonin.m2m2.Main.openZipFiles:228) - Upgrading module mangoUI
INFO  2020-08-12T21:05:51,943 (com.serotonin.m2m2.Main.openZipFiles:228) - Upgrading module deviceConfig
INFO  2020-08-12T21:05:51,965 (com.serotonin.m2m2.Main.openZipFiles:228) - Upgrading module Haystack
INFO  2020-08-12T21:05:52,007 (com.serotonin.m2m2.Main.openZipFiles:228) - Upgrading module virtualDS
INFO  2020-08-12T21:05:52,016 (com.serotonin.m2m2.Main.openZipFiles:228) - Upgrading module advancedScheduler
INFO  2020-08-12T21:05:52,024 (com.serotonin.m2m2.Main.openZipFiles:228) - Upgrading module sqlConsole
INFO  2020-08-12T21:05:52,032 (com.serotonin.m2m2.Main.openZipFiles:228) - Upgrading module scripting
INFO  2020-08-12T21:05:52,038 (com.serotonin.m2m2.Main.openZipFiles:228) - Upgrading module persistent
INFO  2020-08-12T21:05:52,048 (com.serotonin.m2m2.Main.openZipFiles:228) - Upgrading module modbus
INFO  2020-08-12T21:05:52,058 (com.serotonin.m2m2.Main.openZipFiles:228) - Upgrading module pop3
WARN  2020-08-12T21:05:52,080 (com.serotonin.m2m2.Main.loadModules:426) - Module jmxds: this module requires a core version of 3.7, which does not match the current core version of 4.0.0-SNAPSHOT. Module not loaded.
WARN  2020-08-12T21:05:52,088 (com.serotonin.m2m2.Main.loadModules:426) - Module graphicalViews: this module requires a core version of 3.7, which does not match the current core version of 4.0.0-SNAPSHOT. Module not loaded.
WARN  2020-08-12T21:05:52,089 (com.serotonin.m2m2.Main.loadModules:426) - Module pachube: this module requires a core version of 3.7, which does not match the current core version of 4.0.0-SNAPSHOT. Module not loaded.
WARN  2020-08-12T21:05:52,092 (com.serotonin.m2m2.Main.loadModules:426) - Module templateConfig: this module requires a core version of 3.7, which does not match the current core version of 4.0.0-SNAPSHOT. Module not loaded.
WARN  2020-08-12T21:05:52,096 (com.serotonin.m2m2.Main.loadModules:426) - Module galil: this module requires a core version of 3.7, which does not match the current core version of 4.0.0-SNAPSHOT. Module not loaded.
WARN  2020-08-12T21:05:52,102 (com.serotonin.m2m2.Main.loadModules:426) - Module loggingConsole: this module requires a core version of 3.7, which does not match the current core version of 4.0.0-SNAPSHOT. Module not loaded.
WARN  2020-08-12T21:05:52,103 (com.serotonin.m2m2.Main.loadModules:426) - Module sstGraphics: this module requires a core version of 3.7, which does not match the current core version of 4.0.0-SNAPSHOT. Module not loaded.
WARN  2020-08-12T21:05:52,104 (com.serotonin.m2m2.Main.loadModules:426) - Module advancedComponents: this module requires a core version of 3.7, which does not match the current core version of 4.0.0-SNAPSHOT. Module not loaded.
WARN  2020-08-12T21:05:52,110 (com.serotonin.m2m2.Main.loadModules:426) - Module openv4j: this module requires a core version of 3.7, which does not match the current core version of 4.0.0-SNAPSHOT. Module not loaded.
WARN  2020-08-12T21:05:52,115 (com.serotonin.m2m2.Main.loadModules:426) - Module dataImport: this module requires a core version of 3.7, which does not match the current core version of 4.0.0-SNAPSHOT. Module not loaded.
WARN  2020-08-12T21:05:52,116 (com.serotonin.m2m2.Main.loadModules:426) - Module brewersdashboard: this module requires a core version of 3.7, which does not match the current core version of 4.0.0-SNAPSHOT. Module not loaded.
WARN  2020-08-12T21:05:52,127 (com.serotonin.m2m2.Main.loadModules:426) - Module measurlogicDTSCell: this module requires a core version of 3.7, which does not match the current core version of 4.0.0-SNAPSHOT. Module not loaded.
WARN  2020-08-12T21:05:52,129 (com.serotonin.m2m2.Main.loadModules:426) - Module jsonFileImport: this module requires a core version of 3.7, which does not match the current core version of 4.0.0-SNAPSHOT. Module not loaded.
WARN  2020-08-12T21:05:52,139 (com.serotonin.m2m2.Main.loadModules:426) - Module scheduledEvents: this module requires a core version of 3.7, which does not match the current core version of 4.0.0-SNAPSHOT. Module not loaded.
WARN  2020-08-12T21:05:52,141 (com.serotonin.m2m2.Main.loadModules:426) - Module dataPointDetailsView: this module requires a core version of 3.7, which does not match the current core version of 4.0.0-SNAPSHOT. Module not loaded.
WARN  2020-08-12T21:05:52,142 (com.serotonin.m2m2.Main.loadModules:426) - Module pointLinks: this module requires a core version of 3.7, which does not match the current core version of 4.0.0-SNAPSHOT. Module not loaded.
WARN  2020-08-12T21:05:52,143 (com.serotonin.m2m2.Main.loadModules:426) - Module sstTheme: this module requires a core version of 3.7, which does not match the current core version of 4.0.0-SNAPSHOT. Module not loaded.
WARN  2020-08-12T21:05:52,148 (com.serotonin.m2m2.Main.loadModules:426) - Module pakbus: this module requires a core version of 3.7, which does not match the current core version of 4.0.0-SNAPSHOT. Module not loaded.
WARN  2020-08-12T21:05:52,152 (com.serotonin.m2m2.Main.loadModules:426) - Module reports: this module requires a core version of 3.7, which does not match the current core version of 4.0.0-SNAPSHOT. Module not loaded.
INFO  2020-08-12T21:05:52,197 (com.serotonin.m2m2.Main.loadModules:639) - Loading module 'advancedScheduler', v4.0.0-SNAPSHOT by IAS
INFO  2020-08-12T21:05:52,198 (com.serotonin.m2m2.Main.loadModules:639) - Loading module 'mangoApi', v4.0.0-SNAPSHOT by IAS
INFO  2020-08-12T21:05:52,198 (com.serotonin.m2m2.Main.loadModules:639) - Loading module 'mangoUI', v4.0.0-SNAPSHOT by IAS
INFO  2020-08-12T21:05:52,199 (com.serotonin.m2m2.Main.loadModules:639) - Loading module 'mangoESConfiguration', v4.0.0-SNAPSHOT by IAS
INFO  2020-08-12T21:05:52,199 (com.serotonin.m2m2.Main.loadModules:639) - Loading module 'lang_nl', v4.0.0-SNAPSHOT by IAS
INFO  2020-08-12T21:05:52,199 (com.serotonin.m2m2.Main.loadModules:639) - Loading module 'sstGlobalScripts', v4.0.0-SNAPSHOT by IAS
INFO  2020-08-12T21:05:52,200 (com.serotonin.m2m2.Main.loadModules:639) - Loading module 'lang_de', v4.0.0-SNAPSHOT by IAS
INFO  2020-08-12T21:05:52,200 (com.serotonin.m2m2.Main.loadModules:639) - Loading module 'scripting', v4.0.0-SNAPSHOT by IAS
INFO  2020-08-12T21:05:52,200 (com.serotonin.m2m2.Main.loadModules:639) - Loading module 'snmp', v4.0.0-SNAPSHOT by IAS
INFO  2020-08-12T21:05:52,201 (com.serotonin.m2m2.Main.loadModules:639) - Loading module 'lang_zh', v4.0.0-SNAPSHOT by IAS
INFO  2020-08-12T21:05:52,201 (com.serotonin.m2m2.Main.loadModules:639) - Loading module 'lang_pt', v4.0.0-SNAPSHOT by IAS
INFO  2020-08-12T21:05:52,201 (com.serotonin.m2m2.Main.loadModules:639) - Loading module 'persistent', v4.0.0-SNAPSHOT by IAS
INFO  2020-08-12T21:05:52,201 (com.serotonin.m2m2.Main.loadModules:639) - Loading module 'controlcore', v4.0.0-SNAPSHOT by IAS
INFO  2020-08-12T21:05:52,202 (com.serotonin.m2m2.Main.loadModules:639) - Loading module 'virtualDS', v4.0.0-SNAPSHOT by IAS
INFO  2020-08-12T21:05:52,202 (com.serotonin.m2m2.Main.loadModules:639) - Loading module 'BACnet', v4.0.0-SNAPSHOT by IAS
INFO  2020-08-12T21:05:52,203 (com.serotonin.m2m2.Main.loadModules:639) - Loading module 'sqlds', v4.0.0-SNAPSHOT by IAS
INFO  2020-08-12T21:05:52,203 (com.serotonin.m2m2.Main.loadModules:639) - Loading module 'opcda', v4.0.0-SNAPSHOT by IAS
INFO  2020-08-12T21:05:52,203 (com.serotonin.m2m2.Main.loadModules:639) - Loading module 'meta', v4.0.0-SNAPSHOT by IAS
INFO  2020-08-12T21:05:52,204 (com.serotonin.m2m2.Main.loadModules:639) - Loading module 'lang_fi', v4.0.0-SNAPSHOT by IAS
INFO  2020-08-12T21:05:52,204 (com.serotonin.m2m2.Main.loadModules:639) - Loading module 'lang_es', v4.0.0-SNAPSHOT by IAS
INFO  2020-08-12T21:05:52,204 (com.serotonin.m2m2.Main.loadModules:639) - Loading module 'mqttClientDataSource', v4.0.0-SNAPSHOT by IAS
INFO  2020-08-12T21:05:52,205 (com.serotonin.m2m2.Main.loadModules:639) - Loading module 'sqlConsole', v4.0.0-SNAPSHOT by IAS
INFO  2020-08-12T21:05:52,205 (com.serotonin.m2m2.Main.loadModules:639) - Loading module 'lang_en', v4.0.0-SNAPSHOT by IAS
INFO  2020-08-12T21:05:52,205 (com.serotonin.m2m2.Main.loadModules:639) - Loading module 'watchlists', v4.0.0-SNAPSHOT by IAS
INFO  2020-08-12T21:05:52,205 (com.serotonin.m2m2.Main.loadModules:639) - Loading module 'slackPublisher', v4.0.0-SNAPSHOT by IAS
INFO  2020-08-12T21:05:52,206 (com.serotonin.m2m2.Main.loadModules:639) - Loading module 'mangoNoSqlDatabase', v4.0.0-SNAPSHOT by IAS
INFO  2020-08-12T21:05:52,207 (com.serotonin.m2m2.Main.loadModules:639) - Loading module 'Haystack', v4.0.0-SNAPSHOT by IAS
INFO  2020-08-12T21:05:52,207 (com.serotonin.m2m2.Main.loadModules:639) - Loading module 'pid', v4.0.0-SNAPSHOT by IAS
INFO  2020-08-12T21:05:52,207 (com.serotonin.m2m2.Main.loadModules:639) - Loading module 'ssh', v4.0.0-SNAPSHOT by IAS
INFO  2020-08-12T21:05:52,208 (com.serotonin.m2m2.Main.loadModules:639) - Loading module 'deviceConfig', v4.0.0-SNAPSHOT by IAS
INFO  2020-08-12T21:05:52,208 (com.serotonin.m2m2.Main.loadModules:639) - Loading module 'MangoIOTools', v4.0.0 by IAS
INFO  2020-08-12T21:05:52,208 (com.serotonin.m2m2.Main.loadModules:639) - Loading module 'http', v4.0.0-SNAPSHOT by IAS
INFO  2020-08-12T21:05:52,209 (com.serotonin.m2m2.Main.loadModules:639) - Loading module 'dashboardDesigner', v4.0.0-SNAPSHOT by IAS
INFO  2020-08-12T21:05:52,209 (com.serotonin.m2m2.Main.loadModules:639) - Loading module 'pop3', v4.0.0-SNAPSHOT by IAS
INFO  2020-08-12T21:05:52,209 (com.serotonin.m2m2.Main.loadModules:639) - Loading module 'log4jDS', v4.0.0-SNAPSHOT by IAS
INFO  2020-08-12T21:05:52,210 (com.serotonin.m2m2.Main.loadModules:639) - Loading module 'log4JReset', v4.0.0-SNAPSHOT by IAS
INFO  2020-08-12T21:05:52,210 (com.serotonin.m2m2.Main.loadModules:639) - Loading module 'maintenanceEvents', v4.0.0-SNAPSHOT by IAS
INFO  2020-08-12T21:05:52,210 (com.serotonin.m2m2.Main.loadModules:639) - Loading module 'zwave', v4.0.0-SNAPSHOT by IAS
INFO  2020-08-12T21:05:52,211 (com.serotonin.m2m2.Main.loadModules:639) - Loading module 'cloudConnect', v4.0.0-SNAPSHOT by IAS
INFO  2020-08-12T21:05:52,211 (com.serotonin.m2m2.Main.loadModules:639) - Loading module 'dataFile', v4.0.0-SNAPSHOT by IAS
INFO  2020-08-12T21:05:52,211 (com.serotonin.m2m2.Main.loadModules:639) - Loading module 'onewire', v4.0.0-SNAPSHOT by IAS
INFO  2020-08-12T21:05:52,212 (com.serotonin.m2m2.Main.loadModules:639) - Loading module 'mbus', v4.0.0-SNAPSHOT by IAS
INFO  2020-08-12T21:05:52,212 (com.serotonin.m2m2.Main.loadModules:639) - Loading module 'egauge', v4.0.0-SNAPSHOT by IAS
INFO  2020-08-12T21:05:52,213 (com.serotonin.m2m2.Main.loadModules:639) - Loading module 'asciiFile', v4.0.0-SNAPSHOT by IAS
INFO  2020-08-12T21:05:52,213 (com.serotonin.m2m2.Main.loadModules:639) - Loading module 'vmstat', v4.0.0-SNAPSHOT by IAS
INFO  2020-08-12T21:05:52,213 (com.serotonin.m2m2.Main.loadModules:639) - Loading module 'modbus', v4.0.0-SNAPSHOT by IAS
INFO  2020-08-12T21:05:52,214 (com.serotonin.m2m2.Main.loadModules:639) - Loading module 'dnp3', v4.0.0-SNAPSHOT by IAS
INFO  2020-08-12T21:05:52,214 (com.serotonin.m2m2.Main.loadModules:639) - Loading module 'excelReports', v4.0.0-SNAPSHOT by IAS
INFO  2020-08-12T21:05:52,215 (com.serotonin.m2m2.Main.loadModules:639) - Loading module 'TCPIP', v4.0.0-SNAPSHOT by IAS
INFO  2020-08-12T21:05:52,215 (com.serotonin.m2m2.Main.loadModules:639) - Loading module 'envcands', v4.0.0-SNAPSHOT by IAS
INFO  2020-08-12T21:05:52,216 (com.serotonin.m2m2.Main.loadModules:639) - Loading module 'serial', v4.0.0-SNAPSHOT by IAS
INFO  2020-08-12T21:05:52,216 (com.serotonin.m2m2.Main.loadModules:639) - Loading module 'twilio', v4.0.0-SNAPSHOT by IAS
INFO  2020-08-12T21:05:52,217 (com.serotonin.m2m2.Main.loadModules:639) - Loading module 'internal', v4.0.0-SNAPSHOT by IAS
INFO  2020-08-12T21:05:53,730 (com.serotonin.m2m2.Lifecycle.loadLic:607) - Checking license...
INFO  2020-08-12T21:05:53,731 (com.serotonin.m2m2.Lifecycle.loadLic:691) - License file not found
WARN  2020-08-12T21:05:53,865 (com.serotonin.m2m2.TimedLicenseRegistrar.checkLicenses:65) - Mango NoSQL database is running in free mode, Mango will shutdown at 5:05:53 13/08/2020.
INFO  2020-08-12T21:05:54,015 (com.serotonin.m2m2.db.H2Proxy.initializeImpl:64) - Initializing H2 connection manager
WARN  2020-08-12T21:05:54,918 (com.serotonin.m2m2.db.upgrade.DBUpgrade.checkUpgrade:96) - Upgrading 'core' from 29 to 30
INFO  2020-08-12T21:05:54,918 (com.serotonin.m2m2.db.AbstractDatabaseProxy.createLogOutputStream:311) - Writing upgrade log to /Users/craigsweb/Documents/IAS/v4 testing/3.7.8/logs/com.serotonin.m2m2.db.upgrade.Upgrade29.log
INFO  2020-08-12T21:05:56,783 (com.serotonin.m2m2.db.upgrade.DBUpgrade.checkUpgrade:36) - Starting instance with core version 4.0.0-SNAPSHOT, schema v30
INFO  2020-08-12T21:05:56,786 (com.infiniteautomation.nosql.MangoNoSqlProxy.initialize:69) - Starting MangoNoSql Database
INFO  2020-08-12T21:05:56,817 (com.infiniteautomation.tsdb.impl.IasTsdbImpl.<init>:144) - Database at /Users/craigsweb/Documents/IAS/v4 testing/3.7.8/databases/mangoTSDB started
INFO  2020-08-12T21:05:56,856 (com.infiniteautomation.tsdb.impl.IasTsdbImpl.<init>:173) - Empty dir delete for database at /Users/craigsweb/Documents/IAS/v4 testing/3.7.8/databases/mangoTSDB took 7ms
INFO  2020-08-12T21:05:56,860 (com.infiniteautomation.tsdb.impl.IasTsdbImpl.<init>:144) - Database at /Users/craigsweb/Documents/IAS/v4 testing/3.7.8/databases/mangoTSDBAux started
INFO  2020-08-12T21:05:56,888 (com.infiniteautomation.tsdb.impl.IasTsdbImpl.<init>:173) - Empty dir delete for database at /Users/craigsweb/Documents/IAS/v4 testing/3.7.8/databases/mangoTSDBAux took 0ms
WARN  2020-08-12T21:05:56,891 (com.serotonin.m2m2.db.upgrade.DBUpgrade.checkUpgrade:96) - Upgrading 'advancedScheduler' from 6 to 7
INFO  2020-08-12T21:05:56,891 (com.serotonin.m2m2.db.AbstractDatabaseProxy.createLogOutputStream:311) - Writing upgrade log to /Users/craigsweb/Documents/IAS/v4 testing/3.7.8/logs/com.infiniteautomation.mango.scheduling.db.upgrade.Upgrade6.log
ERROR 2020-08-12T21:05:57,150 (com.serotonin.m2m2.Lifecycle.initialize:387) - Error during initialization
com.serotonin.ShouldNeverHappenException: org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [ ALTER TABLE advancedScheduleCalendarRuleSets ADD CONSTRAINT advancedScheduleCalendarRuleSetsFk1 FOREIGN KEY (editPermissionId) REFERENCES permissions(id) ON DELETE RESTRICT; ]; nested exception is org.h2.jdbc.JdbcSQLSyntaxErrorException: Constraint "ADVANCEDSCHEDULECALENDARRULESETSFK1" already exists; SQL statement:
 ALTER TABLE advancedScheduleCalendarRuleSets ADD CONSTRAINT advancedScheduleCalendarRuleSetsFk1 FOREIGN KEY (editPermissionId) REFERENCES permissions(id) ON DELETE RESTRICT; [90045-200]
	at com.serotonin.m2m2.db.upgrade.DBUpgrade.checkUpgrade(DBUpgrade.java:102) ~[mango-4.0.0-SNAPSHOT.jar:?]
	at com.serotonin.m2m2.db.upgrade.DBUpgrade.checkUpgrade(DBUpgrade.java:42) ~[mango-4.0.0-SNAPSHOT.jar:?]
	at com.serotonin.m2m2.db.AbstractDatabaseProxy.initialize(AbstractDatabaseProxy.java:160) ~[mango-4.0.0-SNAPSHOT.jar:?]
	at com.serotonin.m2m2.Lifecycle.databaseInitialize(Lifecycle.java:749) ~[ma-priv-4.0.0-SNAPSHOT.jar:?]
	at com.serotonin.m2m2.Lifecycle.initialize(Lifecycle.java:301) ~[ma-priv-4.0.0-SNAPSHOT.jar:?]
	at com.serotonin.m2m2.Main.main(Main.java:107) ~[ma-priv-4.0.0-SNAPSHOT.jar:?]
Caused by: org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [ ALTER TABLE advancedScheduleCalendarRuleSets ADD CONSTRAINT advancedScheduleCalendarRuleSetsFk1 FOREIGN KEY (editPermissionId) REFERENCES permissions(id) ON DELETE RESTRICT; ]; nested exception is org.h2.jdbc.JdbcSQLSyntaxErrorException: Constraint "ADVANCEDSCHEDULECALENDARRULESETSFK1" already exists; SQL statement:
 ALTER TABLE advancedScheduleCalendarRuleSets ADD CONSTRAINT advancedScheduleCalendarRuleSetsFk1 FOREIGN KEY (editPermissionId) REFERENCES permissions(id) ON DELETE RESTRICT; [90045-200]
	at org.springframework.jdbc.support.SQLExceptionSubclassTranslator.doTranslate(SQLExceptionSubclassTranslator.java:93) ~[spring-jdbc-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72) ~[spring-jdbc-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81) ~[spring-jdbc-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1443) ~[spring-jdbc-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:388) ~[spring-jdbc-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:418) ~[spring-jdbc-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at com.serotonin.m2m2.db.H2Proxy.runScript(H2Proxy.java:282) ~[mango-4.0.0-SNAPSHOT.jar:?]
	at com.serotonin.m2m2.db.upgrade.DBUpgrade.runScript(DBUpgrade.java:129) ~[mango-4.0.0-SNAPSHOT.jar:?]
	at com.serotonin.m2m2.db.upgrade.DBUpgrade.runScript(DBUpgrade.java:148) ~[mango-4.0.0-SNAPSHOT.jar:?]
	at com.infiniteautomation.mango.scheduling.db.upgrade.Upgrade6.upgrade(Upgrade6.java:40) ~[?:?]
	at com.serotonin.m2m2.db.upgrade.DBUpgrade.checkUpgrade(DBUpgrade.java:98) ~[mango-4.0.0-SNAPSHOT.jar:?]
	... 5 more
Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Constraint "ADVANCEDSCHEDULECALENDARRULESETSFK1" already exists; SQL statement:
 ALTER TABLE advancedScheduleCalendarRuleSets ADD CONSTRAINT advancedScheduleCalendarRuleSetsFk1 FOREIGN KEY (editPermissionId) REFERENCES permissions(id) ON DELETE RESTRICT; [90045-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:576) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.message.DbException.get(DbException.java:205) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.message.DbException.get(DbException.java:181) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:114) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:78) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.command.CommandContainer.update(CommandContainer.java:198) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.command.Command.executeUpdate(Command.java:251) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:228) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:201) ~[h2-1.4.200.jar:1.4.200]
	at org.springframework.jdbc.core.JdbcTemplate$1ExecuteStatementCallback.doInStatement(JdbcTemplate.java:409) ~[spring-jdbc-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:376) ~[spring-jdbc-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:418) ~[spring-jdbc-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at com.serotonin.m2m2.db.H2Proxy.runScript(H2Proxy.java:282) ~[mango-4.0.0-SNAPSHOT.jar:?]
	at com.serotonin.m2m2.db.upgrade.DBUpgrade.runScript(DBUpgrade.java:129) ~[mango-4.0.0-SNAPSHOT.jar:?]
	at com.serotonin.m2m2.db.upgrade.DBUpgrade.runScript(DBUpgrade.java:148) ~[mango-4.0.0-SNAPSHOT.jar:?]
	at com.infiniteautomation.mango.scheduling.db.upgrade.Upgrade6.upgrade(Upgrade6.java:40) ~[?:?]
	at com.serotonin.m2m2.db.upgrade.DBUpgrade.checkUpgrade(DBUpgrade.java:98) ~[mango-4.0.0-SNAPSHOT.jar:?]
	... 5 more
INFO  2020-08-12T21:05:57,151 (com.serotonin.m2m2.Lifecycle.terminate:418) - Mango Lifecycle terminating...
INFO  2020-08-12T21:05:57,216 (com.infiniteautomation.nosql.MangoNoSqlProxy.postRuntimeManagerTerminate:114) - Terminating NoSQL Batch Write Manager.
INFO  2020-08-12T21:05:57,225 (com.serotonin.m2m2.db.H2Proxy.terminateImpl:401) - Terminating database.
INFO  2020-08-12T21:05:57,567 (com.infiniteautomation.nosql.MangoNoSqlProxy.shutdown:127) - Closing NoSQL Database: Point Values
INFO  2020-08-12T21:05:57,574 (com.infiniteautomation.nosql.MangoNoSqlProxy.shutdown:135) - Closing NoSQL Database: Point Data
FATAL 2020-08-12T21:05:57,578 (com.infiniteautomation.zwave.rt.ZwaveControlCenter.<init>:62) - Z-Wave Device configuration directory at: null does not exist!
FATAL 2020-08-12T21:05:57,578 (com.infiniteautomation.zwave.rt.ZwaveControlCenter.<init>:67) - Z-Wave user data directory at: null does not exist, Mango will shutodwn.!
INFO  2020-08-12T21:05:57,580 (com.serotonin.m2m2.Lifecycle.terminate:574) - Mango Lifecycle terminated: ERROR
`

**Comment by terrypacker** [comment]
@Craig-IAS thanks for testing!  Fixed.

**Comment by Craig-IAS** [comment]
Retested today and failed with 
[ma.log](https://github.com/infiniteautomation/ma-core-public/files/5068628/ma.log)
`com.infiniteautomation.mango.util.exception.ModuleUpgradeException: Module persistent failed to upgrade from 3.7.2-SNAPSHOT to 4.0.0-SNAPS`
