### ISSUE TITLE
Convert PermissionService role cache to Tree structure

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#1616]
This will make invalidating the cache when any of its hierarchy changes easier and more robust.

- [ ] convert to synchronized tree
- [ ] properly invalidate sections of the tree when any of the role itself or the inherited or inheritedBy roles change.

**Comment by jazdw** [comment]
Consider using weak references - https://github.com/ben-manes/caffeine/wiki/Eviction#reference-based

**Comment by terrypacker** [comment]
Won't fix
