### ISSUE TITLE
Data Source Edit - Source with 15k data points takes a long time to load points

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#1618]
Investigate if it is the query or the page that is the problem.

**Comment by terrypacker** [comment]
See #1629 and #1630

**Comment by jazdw** [comment]
It is the REST query that takes a long time, not the page rendering or anything like that. However we will also be making the data source page lazy load the datapoints as per infiniteautomation/ma-dashboards#342

**Comment by terrypacker** [comment]
Duplicate of #1629
