### ISSUE TITLE
OPC DA Data Source does not have Save Button for adding Data Points

### ISSUE THREAD

**Issue by Joelhaggar** [infiniteautomation/ma-core-public#162]
http://forum.infiniteautomation.com/forum/posts/list/1729.page

Also looks like the data point settings are not complete.

**Comment by Puckfist** [comment]
This issue was resolved some time ago. While the properties of the data point as pertains to OPC did not need saving nor are intended for direct creation, the other data point properties needed to be accessible. All OPC fields are now not editable.
