### ISSUE TITLE
Permissions remove hasAdminRole/ensureAdminRole

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#1623]
These methods should be removed and replaced with actual permission checks even if they are only against a permission that contains the single `superadmin` roles.

**Comment by jazdw** [comment]
I think one place where it might be valid to use `hasAdminRole()` is when deciding to joins on the permission table. It could also be argued that perhaps we should always do the join?

**Comment by terrypacker** [comment]
These were removed by this commit 93356dfb5c28b531d6b7862ec56d3bda7c447449
