### ISSUE TITLE
Script API - Don't allow PermissionService.runAsSystemAdmin

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#1625]
One way or another we need to prevent this method from being available in the new script context.  Either by not injecting this service or moving/shadowing the method.

**Comment by jazdw** [comment]
Another option is to stop allowing access to all public methods and manually annotate every method which scripts are allowed to access and use `HostAccess.Builder#allowAccessAnnotatedBy`.

**Comment by jazdw** [comment]
We should also disallow access to `com.infiniteautomation.mango.spring.service.UsersService#clearCaches`

**Comment by jazdw** [comment]
Removed via 0c02b7e243eb22bc01b0b0c49ca709fdc339019c and e598367579061e58f4717c24444f3215b943f8e0
