### ISSUE TITLE
Public File Store broken for logged in users

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#1633]
Public File Store is non accessible to logged in non-superadmin users.  This is because of the Anonymous role being required to read from the store and User's don't and cannot get that role.  Investigate possibly letting the User role inherit the Anonymous role.

**Comment by jazdw** [comment]
Decided to just add the users role to the public file store permission (and public JSON data on upgrade). I think its a bit confusing to display the "Anonymous" role nested under the "Users" role, and may be confusing to see that a authenticated user has the "Anonymous" role. Also allows for an anonymous user to be granted a permission that a authenticated user is not, but I don't know where this would ever be desirable.
