### ISSUE TITLE
EventManager - get all active users

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#1642]
The call on line 192 to get all active users will happen every time an event is raised.  This would benefit from caching. 

```
for (User user : userDao.getActiveUsers()) {
```

**Comment by jazdw** [comment]
Results in a deadlock / thread contention, see this thread dump -
[thread_dump.txt](https://github.com/infiniteautomation/ma-core-public/files/5639667/thread_dump.txt)

**Comment by jazdw** [comment]
Should have a lock that we try and lock and throw exception if someone is already acknowledging all events.

**Comment by jazdw** [comment]
@terrypacker This really should be converted to a JIRA issue, we should be caching this.

**Comment by terrypacker** [comment]
Moved to jira: https://radixiot.atlassian.net/browse/RAD-1002
