### ISSUE TITLE
Scripting Data Source - Add ability for any script point to update script context 

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#165]
See meta data module for assistance.

**Comment by Puckfist** [comment]
We could probably do this at any time without too much difficulty. I wonder if it's the right way to go about it.

I have only thought of one use case that really makes sense to me to have a scripting data source on context update, and that would be parsing values in a one-to-many way. many-to-many fails unless only one is the context updater. One-to-many could be achieved by adding more targets to a point link. What's the difference between a script on context update and a point link?

My inclination is turning toward changing point links to support one to many. But, it's not in a hurry.

**Comment by Puckfist** [comment]
I decided changing the point links to have many targets was not ideal. I thought about enabling the set() function in Meta points as a possibility, but I came around to having the script be able to do this. Here is a branch for this feature: https://github.com/infiniteautomation/ma-modules-private/tree/script-context-update
