### ISSUE TITLE
Move files from classes to resources

### ISSUE THREAD

**Issue by jazdw** [infiniteautomation/ma-core-public#1662]
Currently i18n.properties, env.properties etc are loaded from the classes directory rather than from the jar file. We should move these files to the resources directory so they are included in the jar instead. We should then implement some way to generate an empty config file.

**Comment by jazdw** [comment]
Leaving this open until we create a way to generate a env.properties on first start. This would look for the overrides/properties/env.properties file or the file specified by MA_ENV_PROPERTIES and create it if it doesn't exist (commenting out all lines).

**Comment by jazdw** [comment]
Module i18n.properties are still located in the classes directory but are no longer copied to zip file. We should move these files into resources.

**Comment by terrypacker** [comment]
We should change any documentation about copying this file from the classes folder to say that this file will be automatically copied across to the overrides.

- [ ] make this file r/w for the mango user

**Comment by terrypacker** [comment]
Note also that the log4j2.xml file has been moved to the jar, update documentation as necessary.

**Comment by terrypacker** [comment]
- [ ] Decide what to do about existing `classes` directory on upgrade.  It won't be on the class path

**Comment by terrypacker** [comment]
Released and in production
