### ISSUE TITLE
Mango does not terminate when OutOfMemoryError is thrown

### ISSUE THREAD

**Issue by jazdw** [infiniteautomation/ma-core-public#1702]
We should
- `Thread.setDefaultUncaughtExceptionHandler(new MangoUncaughtExceptionHandler());`
- Check if `Throwable` is an `Error` in `MangoUncaughtExceptionHandler` and call `System.exit()`?

**Comment by terrypacker** [comment]
Moved to Jira: https://radixiot.atlassian.net/browse/RAD-931
