### ISSUE TITLE
Update scripts to handle new configurable file locations

### ISSUE THREAD

**Issue by jazdw** [infiniteautomation/ma-core-public#1706]
- [ ] bin/ma.pid file for Linux start script
- [ ] Update start scripts and installer scripts (also check for new SAFE/RESTART/DELETE flag locations)
- [ ] Update bootstrap and windows service
- [ ] Update documentation

**Comment by terrypacker** [comment]
Moved to jira https://radixiot.atlassian.net/browse/RAD-938
