### ISSUE TITLE
Clean/Purge Orphaned DataPointVO.seriesId

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#1708]
The nightly data purge removes point values for orphaned series Ids but does nothing to maintain the timeSeries table.

- [x] Check to see if seriesId is removed when deleting a data point
- [ ] Potentially ensure no orphaned series Ids are in timeSeries table during purge.

**Comment by terrypacker** [comment]
The DataPointDao does delete the seriesId entry if possible when deleting post relational data (also in the bulk delete method).  So unless we feel the orphaned seriesId check is necessary during the nightly purge we can close this.

**Comment by terrypacker** [comment]
@jazdw any opinion here?  Otherwise we can close this.

**Comment by jazdw** [comment]
@terrypacker should be done at some point. Don't just close.

**Comment by terrypacker** [comment]
Moved to Jira.  https://radixiot.atlassian.net/browse/RAD-948
