### ISSUE TITLE
Mango 3.x Permission Imports into 4.x Need Checks

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#1723]
In Mango 3.x permissions are CSV strings and could be null.  In Mango 4.0 we now allow importing null JSON values and this will result in the permission being null and invalid.

We need to add code like this:

```
                if(dp.getDataPoint().getSetPermission() == null) {
                    dp.getDataPoint().setSetPermission(new MangoPermission());
                }
```

For any permission being imported.

The firs step is to identify all VOs with permissions in 3.x and modify the importers accordingly.

**Comment by pierpuccini** [comment]
ma-core-public
- [ ] DataPointSummary
- [ ] DataPointVo
- [ ] FileStore
- [ ] IDataPoint
- [ ] User
- [ ] BasicDataSourceVO
- [ ] DataSourceVO
- [ ] AbstractEventHandlerVO
- [ ] EventInstanceVO
- [ ] AbstractEventDetectorVO
- [ ] JsonDataVO
- [ ] MailingList

**Comment by terrypacker** [comment]
See this commit for how to fix this in the Importer classes:

f4216e27559b87019413ecdd451b04355ca654ef
