### ISSUE TITLE
BACnet data source - save Data Point Name source from tool as system settings

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#211]
Each time this selection is changed save the value as the system setting for that system.

**Comment by terrypacker** [comment]
When using the BACnet discovery tool you are given a drop down that sets what attribute from the discovered object will be used as the 'name' property of the data point when it is added.  Currently the drop down always opens as 'Use Object Name for new Points'.  We are proposing to add a system setting that will store the user's selection so that next time the page is opened the value will be set in the drop down.

What about multiple users using this?

**Comment by Puckfist** [comment]
Not implementing
