### ISSUE TITLE
BACNet Discovery Tool - Existing point comparisons

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#216]
When using the discovery tool it would be good to mark what points are already added into Mango.

This will require comparing each Object that is discovered with the existing points in Mango, using

From the Object:
1. Object Instance Number 
2. Object Type

From the Device:
1. Device Instance Number
2. MAC Address

Once the list is created ensure there is a way to import only new points.

**Comment by terrypacker** [comment]
Added an endpoint to get all object types supported by a BACnet data point and optionally the properties: https://github.com/infiniteautomation/ma-modules-private/commit/388fa9abc4ae26d42ec87feeb1d433eaddf13605

**Comment by jazdw** [comment]
@terrypacker added REST API here infiniteautomation/ma-modules-private@388fa9abc4ae26d42ec87feeb1d433eaddf13605 which enables me to easily map the property names returned from the tools end points to the property names used by the point locator REST API.
