### ISSUE TITLE
Meta Data Source - Access to non primitive numeric types causes problems

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#224]
The following example script fails:

var a = p1.past(MINUTE,10);
var b = p2.past(MINUTE,10);

return a.average + b.average;

Because a.average returns a java.lang.Double and the javascript engine views + of these types as String concatenation.

Solution, create a wrapper for the AnalogStatistics (and any others) that force a return of a java primitive type.  i.e. double instead of java.lang.Double.

**Comment by Puckfist** [comment]
It looks like this has been cleaned for many of these. Testing revealed this is still occurring for alphanumeric points, whose typeof(alpha.past(DAY).firstValue) == 'object'

Attached is a script that can help test this stuff.

[12-9-15 test script value types.txt](https://github.com/infiniteautomation/ma-core-public/files/57490/12-9-15.test.script.value.types.txt)

**Comment by Puckfist** [comment]
Perhaps solve at the same time as [issue 514](https://github.com/infiniteautomation/ma-core-public/issues/514)

**Comment by Puckfist** [comment]
Hmm. It seems the typoeof() test still fails.

**Comment by Puckfist** [comment]
It would also appear that this issue exists for multistates and binaries. typeof(multistate.past(DAY).firstValue) == 'object' such that + performs string concatenation. Perhaps this means binaries and multistates would want to be split so that the return type is right?

**Comment by terrypacker** [comment]
The code has been changed in the Core and String is now being returned.  It seems your test might be a little misleading, try this:

```
var first = alpha.past(DAY).firstValue;
typeof first --> object
typeof new String(first + '') --> object
typeof (first + '') --> string
typeof ('') --> string

```

There is a special case where in Javascript new String() returns a object instead of a string type.  My guess is that is what is happening here is that when we return a Java String which is not actually a primitive type but an Object it is being converted to the javascript object type.

**Comment by Puckfist** [comment]
I did see that change, and for alphanumerics that may be totally fine, but nobody should hinge mission critical logic on typeof(alpha.past(DAY).firstValue) in the present form, it would seem to me.

**Comment by terrypacker** [comment]
I agree but I'm not sure we can do any better, and by reading up on this it is ill advised to try and detect strings via the typeof method for this very reason.

**Comment by Puckfist** [comment]
I still reject this issue as being closed due to multistate.past(DAY).firstValue + otherMultistate.past(DAY).firstValue, lastValue, and the same two for binary points, do not behave as sought.

**Comment by terrypacker** [comment]
Agreed.  I've implemented your solution:

> Perhaps this means binaries and multistates would want to be split so that the return type is right?

Something to note here is that by doing this we are adding in the inconsistency that if there is no firstValue or lastValue they are required to be set as primitive types cannot be null.

**Comment by Puckfist** [comment]
Tested!
