### ISSUE TITLE
Meta Data Source - Script won't validate unless point saved and enabled

### ISSUE THREAD

**Issue by jeremyjhall** [infiniteautomation/ma-core-public#233]
In core 2.4.2 with meta module 2.0.7, a newly entered script will not validate (run when the green tick button is pressed) unless the point has first been both saved and enabled.

![screen shot 2014-09-06 at 11 46 58 pm](https://cloud.githubusercontent.com/assets/1190351/4175602/11a28a46-35dd-11e4-8366-ece55314629f.png)

**Comment by Puckfist** [comment]
It is indeed fixed.
