### ISSUE TITLE
Unix Startup Script fails if spaces are in the Mango Home path.

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#243]
When the ma.sh script assigns a value to MA_HOME there is no escaping of the path.

Workaround: pre-asign the path the MA_HOME with escaped string

**Comment by Puckfist** [comment]
Tested fix in [this commit](https://github.com/infiniteautomation/ma-core-public/commit/6e9923e3a504ab6f8e1327abe00e8577cf9eb298)

It starts, but it does not run any scripts from ext-enabled. It seems like you may have problems using the workaround in this issue with the changes in that commit, since your escaped string will be treated as a literal inside the quotes. Could we fix this by removing all quotes and just escaping spaces via something like:
MA_HOME=$(echo $MA_HOME | sed 's/ /\\ /g')

**Comment by Puckfist** [comment]
Seems to fix things for me:
line 46,133 ma-start.sh, line 29 ma-init.sh, line 16 ma-stop.sh:
if [ "$(ls -A $MA_HOME/bin/ext-enabled)" ]; then
            echo `date` 'ma-start: running restart extentions' >> "$MA_HOME"/logs/ma-script.log
            for f in "$MA_HOME"/bin/ext-enabled/*.sh
            do
                source $f restart
            done
        fi
--> #isn't bash lovely?
if [ "$(ls -A "$MA_HOME"/bin/ext-enabled)" ]; then
            echo `date` 'ma-start: running restart extentions' >> "$MA_HOME"/logs/ma-script.log
            for f in "$MA_HOME"/bin/ext-enabled/*.sh
            do
                source "$f" restart
            done
        fi

ma-start.sh line 93
echo `date` 'ma-start: starting MA' >> $MA_HOME/logs/ma-script.log
-->
echo `date` 'ma-start: starting MA' >> "$MA_HOME"/logs/ma-script.log

CONSIDER.... ma-start.sh:30
MA_CP="$MA_HOME"/overrides/classes
MA_CP=$MA_CP:"$MA_HOME"/classes
MA_CP=$MA_CP:"$MA_HOME"/overrides/properties
MA_CP="$MA_CP:$MA_HOME/overrides/lib/*"
MA_CP="$MA_CP:$MA_HOME/lib/*"
-->
MA_CP="$MA_HOME"/overrides/classes
MA_CP=$"MA_CP":"$MA_HOME"/classes
MA_CP="$MA_CP":"$MA_HOME"/overrides/properties
MA_CP="$MA_CP":"$MA_HOME"/overrides/lib/*
MA_CP="$MA_CP":"$MA_HOME"/lib/*
(But this seemed equivalent with the status quo)

hunted with: grep -H -n -e "[^\"]\$MA_HOME" *
from MA_HOME/bin/

**Comment by terrypacker** [comment]
Changes scripts as per your suggestions and things work better.  However the extensions still cannot be run if there are spaces in MA_HOME.  I didn't have time to figure out a fix but the problem is in this code:

```
    echo `date` 'ma-start: running init extensions...' >> "$MA_HOME"/logs/ma-script.log
    for f in "$MA_HOME"/bin/ext-enabled/*.sh
    do
        source $f init
    done
```
The problem is the
``` source $f init``` 
command  not working with spaces in $f.

This will be the same for the start/stop extension execution too.

**Comment by terrypacker** [comment]
Ok, I think we have it now.  I've added additional escaping for the error stream output and for running extensions.  Test by running mango with a space in the path and also should test running all extensions.

**Comment by terrypacker** [comment]
Also test an upgrade with enabled extensions to ensure they don't get clobbered.

**Comment by Puckfist** [comment]
Confirmed not clobbered, extensions running. Marking closed.
