### ISSUE TITLE
Point Value Import - Needs Improvement

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#277]
CSV Importer doesn't work with Watchlist or Data Point Details pages output.

Excel Importer is heavy on memory use.

**Comment by resotek** [comment]
I'm using core 2.7.3 now, so this is still not working. It also was not working under 2.5.2. Mango does not delete points using CSV point value import of points tagged with "delete" in the delete column. No error messages were displayed after CSV upload.

Summary of download / upload combinations where "delete" may have no effect:

* Download CSV from watch list, upload  as CSV with delete: does not delete
* Download CSV from watch list, upload as Excel with delete: does not delete
* Download Excel from watch list, upload as CSV with delete: not tested
* Download Excel from watch list, upload as Excel with delete: does delete

**Comment by terrypacker** [comment]
Fixed: Download CSV from watch list, upload as CSV with delete

Not Supported nor advised: Download CSV from watch list, upload as Excel with delete

- Modified the Excel importer to only add new points, this means that depending on the data store type the value could be updated or inserted as a duplicate.  (No duplicates in NoSQL)

- Provided more information as to how many items were added/removed.

**Comment by Puckfist** [comment]
I am willing to say this works. I did notice in my testing that the Excel Import is more persnickety about the headers than the CSV importer (my test was delete many, replace deletes with adds, bring them back (and some pathological things, like adding and deleting the same row). Other than that, seemed the same. Specifically Excel required the header to be 'Modify (add/delete)' where i got away in the CSV having it say 'Modify (add/add)' on accident

**Comment by terrypacker** [comment]
Found a bug with the new code that splits Excel files into sheets.  The SpreadsheetEmporter needs to know the exact name of the sheet to do its job.  This was fixed in FileUploadController to list the sheets first.

**Comment by terrypacker** [comment]
Uploaded CSV and Excel with add/delete marked.  Saw values get deleted and added didn't check for exactness of results.

**Comment by terrypacker** [comment]
Closing as ready for release.
