### ISSUE TITLE
Modbus TCP Keepalive - Slave connectivity at startup

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#283]
http://forum.infiniteautomation.com/forum/posts/list/0/1950.page#7964

**Comment by alvaro-oliver** [comment]
Hi Terry,
I don't mean to be rude or define your priorities, but I've seen how this milestone was constantly moved from one version to another, and I think it's a bug to pay more attention, since it generates an erroneous behavior that is very difficult to diagnose to most of the users.

**Comment by terrypacker** [comment]
Alvaro,

No worries, I don't mind a little reminder now and again.  I just tested this and it seems to be fixed in our 2.6.0 core.  From viewing the commit log in our repo it looks like from module version 1.5.4 this has been fixed.  If you can upgrade your module and let me know if the problem persists I will revisit the code again.

Thanks.

**Comment by alvaro-oliver** [comment]
Tested with modbus module version 1.5.6.
Bug solved.
Thanks!

**Comment by terrypacker** [comment]
Closing as fixed.
