### ISSUE TITLE
Module System Settings Not Being Exported

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#29]
When exporting the System Settings there is currently no way to export any settings that the modules have added to the system settings.  This can probably be done in the SystemSettingsDao.getSystemSettings() method by adding a new member to the SystemSettingsVO that is a hashMap of any extra system settings.  Or potentially just having one member in the VO that is a hash map that contains all settings in the DB.

**Comment by Puckfist** [comment]
I believe this may be resolved. They appear exported as moduleName.PROPERTY_NAME generally.

**Comment by terrypacker** [comment]
This should have been fixed within the last few releases of Mango, if you can confirm it works as expected please close this.

**Comment by Puckfist** [comment]
Confirmed.
