### ISSUE TITLE
Change Restart Task priority

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#293]
If a user is trying to restart the instance during times of high system load the priority of the restart task needs to be at its maximum.

**Comment by terrypacker** [comment]
I'm not sure that executing the shutdown immediately is wise as this doesn't give anyone time to finish their work after they are notified.  The best solution is to add in a time delay that the admin can provide when they schedule the shutdown.  A time of 0 would be to execute the work now.

Pushing off for discussion and a later release.

**Comment by Puckfist** [comment]
Thread will now run with max priority
