### ISSUE TITLE
Meta Data Source - Import of points with themselves in the context

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#297]
It is possible to get the source point into the context (in addition to the 'my' option now available).  This type of point cannot be imported because of the validation that all context points must be in Mango before the point can be imported.  

1. Can this still happen?  If so change so that it can't.
2. We need to let the users know this when it fails.  Which isn't easy to do as it can't be determined in the JSON import because the data point we are importing to isn't available at this point.

**Comment by Puckfist** [comment]
This has been resolved.
