### ISSUE TITLE
Improve Nightly Purges

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#299]
The nightly purges currently perform locking on the entire Point Values table, this causes excessive usage of the innodb buffer pool in MySQL and probably issues for other databases.  

Currently the Limit Delete methods for some of the Point Values do not have the wait time set > 0 this should be reviewed. To allow the deletes to be less aggressive.

deletePointValuesBefore
deletePointValues(datapointid)

**Comment by Puckfist** [comment]
Close as all systems of meaningful size will use NoSQL which is efficient?
