### ISSUE TITLE
Annotations not shown on Target point when Point Links 'write annotation' box is checked.

### ISSUE THREAD

**Issue by resotek** [infiniteautomation/ma-core-public#306]
When the Point Links 'write annotation' checkbox is enabled, the Target point should display an annotation indicating that it was set by the linked Source point. However, no annotations were seen on the Target point Annotation field in the History section of the data_point_details.shtm page. Core 2.4.2

**Comment by terrypacker** [comment]
I've updated the annotation but from my testing it was already working.
