### ISSUE TITLE
Add abort or cancel to MetaData 'Generate History'

### ISSUE THREAD

**Issue by resotek** [infiniteautomation/ma-core-public#318]
There is no way to abort a "Generate History" task once it has started. Changing the formula or context has no effect once generation has started. This is especially problematic when the history changes too often, as history generation could take hours.

Since the Generate History pop-up can be closed during history generation, this should be implemented by clicking a cancel icon next to the history generation icon in the "Data points" tab of the Metadata source.

**Comment by terrypacker** [comment]
Reference #443

**Comment by Puckfist** [comment]
This exists in the meta history generation api endpoints, released with the last meta module
