### ISSUE TITLE
Add Erase checkbox to Generate History dialog

### ISSUE THREAD

**Issue by resotek** [infiniteautomation/ma-core-public#319]
Usually when a point data history is regenerated, one must delete the points within the date range prior to history regeneration, either to avoid redundancies or to replace conflicting data. This involves downloading the point history, adding a delete tag to certain rows, saving the table, then performing a data import. This process both is redundant and time consuming, especially when erasing "all data" from the data_point_edit page is not a viable option.

An "Erase" checkbox in the "Generate History" pop-up dialog would resolve this by erasing all datapoints within the range, ensuring that the point values within that date range contain only newly created values.

**Comment by Puckfist** [comment]
This happened in #813
