### ISSUE TITLE
Datasource Tools - Unable to add points

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#323]
To recreate bug: 
1. Create data source
2. Use tool to add point
3.  Won't be able to add point ( Multiple tabs open warning)

**Comment by terrypacker** [comment]
Closing as fixed

**Comment by terrypacker** [comment]
See this post for more info: See this forum post: http://infiniteautomation.com/forum/topic/2035/data-point-save-due-to-wrong-point-referenced/2

**Comment by terrypacker** [comment]
The following code can be used as a starting point for the bug fix.  The existing code is overly complex.  We will wait until after the initial 2.7.0 release as this fix may introduce new bugs so this will require thorough testing when completed.

See DataSourceEditDwr.java 
```
    protected DataPointVO getPoint(int pointId, DataPointDefaulter defaulter) {
        //Added to allow saving point settings from data point edit view
        DataPointVO dp = Common.getUser().getEditPoint();
        DataSourceVO<?> ds = Common.getUser().getEditDataSource();

        if(pointId == Common.NEW_ID){
        	 dp = new DataPointVO();
             dp.setId(pointId);
             dp.setXid(DataPointDao.instance.generateUniqueXid());
             dp.setDataSourceId(ds.getId());
             dp.setDataSourceTypeName(ds.getDefinition().getDataSourceTypeName());
             dp.setDeviceName(ds.getName());
             dp.setPointLocator(ds.createPointLocator());
             dp.setEventDetectors(new ArrayList<PointEventDetectorVO>(0));
             dp.defaultTextRenderer();
        }else{
        	dp = DataPointDao.instance.getFull(pointId);
        }

        //Use the defaulter
        if (defaulter != null && dp != null) {
            if (dp.getId() == Common.NEW_ID)
                defaulter.setDefaultValues(dp);
            else
                defaulter.updateDefaultValues(dp);
        }

        //Ensure we don't assign points to the wrong data source type, basically ensure the editing source is the one we
        // should use for this point.  If not we must fail.
        if (!(dp.getDataSourceTypeName().equals(ds.getDefinition().getDataSourceTypeName()))
                || (dp.getDataSourceId() != ds.getId())) {
            throw new RuntimeException(
                    "Data point type mismatch to data source type, unable to save.  Are you working with multiple tabs open?");
        }
        
        Common.getUser().setEditPoint(dp);
        return dp;
    }
```

**Comment by terrypacker** [comment]
This happens from both the Modbus and BACnet I/P data sources for sure.

**Comment by Puckfist** [comment]
I have tested the methods Jeremy used in his videos to evince the issue, and not had a problem. Using the add point tools in BACnet and Modbus data sources through a single tab worked.

**Comment by terrypacker** [comment]
I can replicate this bug every time with the following process:

1.  Start mango (may not be required to always start from fresh) 
2.  Go to Data Source page and create a new ModbusIP data source
3. Click the Add point button in the 'Point locator test' area.
4. Popup with 'Data point type mismatch to data source type, unable to save.  Are you working with multiple tabs open?'

**Comment by terrypacker** [comment]
Also note that the code change in that commit is on a new branch for testing this.

**Comment by Puckfist** [comment]
I can confirm the new code prevents you from being able to trigger that message from the data source tools in modbus (BACnet gives a different alert, so it would seem to be a different bit of code at work). It would almost seem to me that if we're just addressing datasource tools that will give you access to adding data points before saving the datasource, perhaps we should solve that in the module's JSP and require the data source be saved?

**Comment by Puckfist** [comment]
I'm hesitant to mark this 'closed' when you can trigger a ShouldNeverHappen exception so easily from clicking the add point button in Modbus. It does prevent the user from getting that popup, but perhaps this also calls for disabling the button in the datasource so that ShouldNeverHappen remains something harder to generate?

**Comment by terrypacker** [comment]
Committing another change for Modbus to behave like BACnet.  Please re-test and if there are problems provide exact process used to produce error.

**Comment by terrypacker** [comment]
Also found that these changes have caused undesirable side effects of not all point properties being saved when editing a point.  Please do some thorough testing of editing data points and ensuring that all properties are being saved as desired.  This is only necessary to test in UI on the Data Source Page.

**Comment by Puckfist** [comment]
Two alerts, one accompanied by a ShouldNeverHappenException, are thrown when the add point button is pressed on an unsaved modbus data source.

I can confirm all properties are being saved in virtual points.

**Comment by terrypacker** [comment]
I found the bug in the javascript where the alert was being raised but not returning from the method and the dwr call was still being made.

**Comment by Puckfist** [comment]
Fixed
