### ISSUE TITLE
Change name of Modbus I/O log file to match xid instead of source number.

### ISSUE THREAD

**Issue by resotek** [infiniteautomation/ma-core-public#329]
In installations with many Modbus sources, determining which datasource to edit to disable the Modbus I/O log file can be quite tedious. A typical scenario is where the Admin sees growing log files (e.g. /opt/mango/logs/modbusIO-8.log), but has to check each datasource to determine which one corresponds to that log file. Another use case is where there are multiple log files enabled, and the admin has to correlate the numeric file name to the datasource for each file. This burdens the admin with an unnecessary layer of indirection.

If the log file name matched the xid, this process would be much less tedious, especially in cases where the xid was set to mimic the datasource name.

**Comment by Puckfist** [comment]
Closing, validation isn't performed on the XID to guarantee that the file will be valid, whereas the id is always valid.
