### ISSUE TITLE
previousPeriodType Element not Updating on Report Import

### ISSUE THREAD

**Issue by DaveFrazier** [infiniteautomation/ma-core-public#332]
Hi,

   I noticed while creating templates for our power meters that the 'previousPeriodType' element is not being updated when a report is imported.  It will either default to 'DAYS' if the report is imported from scratch, or it will remain at the previous value if an existing report is update via import.

**Comment by Joelhaggar** [comment]
To clarify by imported we mean imported from JSON

**Comment by terrypacker** [comment]
Fixed.  The previousPeriodType JSON was misspelled.  The code now accepts both previousPeriodType and perviousPeriodType but now correctly exports as previousPeriodType.
