### ISSUE TITLE
Internal metrics work items page has wrong hyperlink header

### ISSUE THREAD

**Issue by resotek** [infiniteautomation/ma-core-public#339]
The "Thread monitoring" hyperlink is not active on the Work items page:
/internal/workItems.shtm header =  [Internal metrics](/internal/status.shtm) | Thread monitoring | [Work items](/internal/workItems.shtm)

should be:
/internal/workItems.shtm header =   [Internal metrics](/internal/status.shtm) | [Thread monitoring](/internal/threads.shtm) | Work items

m2m2 core 2.5.2 build 6

**Comment by terrypacker** [comment]
Fixed in latest release of module.
