### ISSUE TITLE
Bash Scripts Updates can not update single mods 

### ISSUE THREAD

**Issue by JosephMillsAtWork** [infiniteautomation/ma-core-public#348]
The update script is not tailored to upgrade a number of packages (array) or a single package or all of them. ATM it looks like it updates all of them only.

**Comment by JosephMillsAtWork** [comment]
The framework for this has been implanted and needs to be worked on and testing needs to happen.,

**Comment by terrypacker** [comment]
Closing as complete enough for 2.6.0
