### ISSUE TITLE
Bash Scripts There is no verbose no help and other options

### ISSUE THREAD

**Issue by JosephMillsAtWork** [infiniteautomation/ma-core-public#349]
The switch statement for arguments passed in is not on a loop. 
There is no options that start with -- 
There is no real help page or option for help --help -h -?
There is no option to make the output verbose --verbose -v;
There is no option for upgrading and checking/

**Comment by JosephMillsAtWork** [comment]
This has been added, in a development bash branch.,

**Comment by terrypacker** [comment]
Closing as complete enough for 2.6.0
