### ISSUE TITLE
Feature to purge a given time range for a Data Source or Data Point.

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#355]
Add ranges to the purge now feature.

**Comment by resotek** [comment]
Can a "purge" checkbox be added to the "Generate History" Meta Data Source pop-up so that it will purge the "Generate History" range before or as the new history is generated?

**Comment by terrypacker** [comment]
The purge checkbox request for Meta Data history has been moved to issue #813 since that isn't what this issue is about.

**Comment by Puckfist** [comment]
Once #813 is completed this would be trivial... just loop over the points and call the points' delete between method. Giving it the +1hr

**Comment by Puckfist** [comment]
Exists!
