### ISSUE TITLE
Incremental NoSQL Backup - Versions to keep is deleting files even when using Incremental option

### ISSUE THREAD

**Issue by Joelhaggar** [infiniteautomation/ma-core-public#371]

**Comment by terrypacker** [comment]
I was aware this would happen and left it in on purpose.  I think just because you are doing incremental backups doesn't mean you want to keep all of your historical data.  I think it should be left in.  We could add an additional setting that disables this feature when checked.

**Comment by Joelhaggar** [comment]
I think you are right it makes sense to limit the number of backups to keep but it should probably be really high by default like 365 or 730 or something.  Main thing is that the user understands it so they don't think they have backups but in-fact they are being deleted.  Maybe rename it or put a warning sign by it with a popup explanation

**Comment by terrypacker** [comment]
Added red text comment when using incremental backups.
Also set the default number of backups to keep to 365.

Waiting to close this issue until we review this again.
