### ISSUE TITLE
Help on the users page has the wrong icon

### ISSUE THREAD

**Issue by Joelhaggar** [infiniteautomation/ma-core-public#379]
In this line there is the icon: 
![image](https://cloud.githubusercontent.com/assets/2327703/7222951/0829ca1a-e6d6-11e4-8072-6cd496f960e3.png)

and it should be 
![image](https://cloud.githubusercontent.com/assets/2327703/7222954/14466d9e-e6d6-11e4-9552-cb42646b6a6f.png)

Clicking on the  will present a list of permission groups that other users have, but the current user does not.

**Comment by terrypacker** [comment]
Fixed.
