### ISSUE TITLE
BACnet published points can not have their values set over BACnet from another system

### ISSUE THREAD

**Issue by Joelhaggar** [infiniteautomation/ma-core-public#387]
When publishing a settable datapoint as BACnet there is no option to allow the point to be set.

**Comment by terrypacker** [comment]
From what I can gather this is not an easy change.  Publishers are not designed for this type of use.

**Comment by Joelhaggar** [comment]
The Modbus publisher allows values to be set.  There are security issues with this that we will need to address at some point but as long as it's optional we should be fine for now. Either way this probably isn't a huge priority.

**Comment by Puckfist** [comment]
I believe this is in BACnet 3.0.1

**Comment by Puckfist** [comment]
This is indeed working
