### ISSUE TITLE
Scheduled Reports - Not all data is being deleted 

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#389]
Some of the tables are not cleaned.  There may be performance issues with doing this.  But it should be looked at.

See:
ReportDao.deleteReportInstance

**Comment by Puckfist** [comment]
Is this related to/a duplicate (prior duplicate...) of #687 ?

**Comment by terrypacker** [comment]
We could probably roll these into the same issue but we need to make sure that they include both the NoSQL and SQL data as I think this issue was created about SQL tables.

**Comment by Puckfist** [comment]
Looks good to me.
