### ISSUE TITLE
Add a 'refresh' button to Data Sources page that forces a new poll of entire data source

### ISSUE THREAD

**Issue by jeremyjhall** [infiniteautomation/ma-core-public#397]
Consider adding a 'refresh' button to each Data Source on the Data Sources list page. When clicked, the button would force a re-polling of all data points within the data source.

![screen shot 2015-06-03 at 10 27 09 am](https://cloud.githubusercontent.com/assets/1190351/7951541/346ec954-09db-11e5-99d1-1c75bc59fb11.png)

**Comment by Puckfist** [comment]
I just exposed this to the script environments: https://github.com/infiniteautomation/ma-core-public/commit/08ec4cee1ea27f23a2d6e0e2593f1de9f88bb3cd
