### ISSUE TITLE
Discard Ranges set to -Infinity and Infinite instead of numeric values

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#399]
It was found that a configuration had the discard data ranges set to -Infinity and Infinity

This causes problems for the Persistent TCP configuration publishing and potentially others.

They should be set to the max/min range for the Numeric value of a double.

**Comment by Puckfist** [comment]
This is relevant to issue #558, which is concerned with implementing the special double inbound instead of outbound, which is what is producing this problem in the TCP publisher. It is actually a problem on all json emports. I am closing this one in favor of #558
