### ISSUE TITLE
Avoid Cache on file download

### ISSUE THREAD

**Issue by satblip** [infiniteautomation/ma-core-public#400]
Hi,

Will it be possible to had those headers to the response when a download is requested (Excel files for example)?

```
Expires: {now} GMT
Last-Modified: {now} GMT
Cache-Control: no-store, no-cache, must-revalidate, max-age=0
Cache-Control: post-check=0, pre-check=0
Pragma: no-cache
```

That way, we’re sure that any proxies that we can use between mango and our NAT will not cache it. 

Thanks

**Comment by terrypacker** [comment]
This should be a simple addition so I'll try and slip this into the upcoming 2.6.0 release.

**Comment by terrypacker** [comment]
Added to core 2.6.0
