### ISSUE TITLE
Permissions problem in Graphic View

### ISSUE THREAD

**Issue by WoodyIAS** [infiniteautomation/ma-core-public#404]
Steps to repro:
1) Create a graphic view and add a point
2) Verify a non-admin user has read / set permission but not edit permission for the point in the graphic view
3) Verify the non-admin user can set the value in a watch list
4) Logged in as the non-admin user attempt to set the point's value from in the graphic view

Observe: Error message stating the user does not have permission to set the point.

Notes:
Running Core 2.6.0 Build 306, BrewersDashboard 1.1.0
If the non-admin user is given edit permission to the graphic view then they are able to set the value of the point in graphic view.

**Comment by terrypacker** [comment]
Thanks for the complete description/reproduction steps that made this an easy fix.  The wrong permission was being checked prior to setting the value.  Closing as fixed.
