### ISSUE TITLE
Meta data scripts cannot reference themselves  

### ISSUE THREAD

**Issue by WoodyIAS** [infiniteautomation/ma-core-public#405]
core 2.6.0 build 327

To Reproduce
1) Create a Meta Data Source
2) Add a Data Point
3) In the script reference the script with using its variable name (by default it will be "my")
4) Example: return my.value + 1;

Observe
Error msg if you click the green script check button
Script error: ReferenceError: "my" is not defined in at line number 1 in at line number 1

**Comment by terrypacker** [comment]
Closing as fixed.
