### ISSUE TITLE
Scripting Data Source csv export errors when the data source as data pionts

### ISSUE THREAD

**Issue by Joelhaggar** [infiniteautomation/ma-core-public#407]
"message","stackTrace"
"No model found to support class: com.serotonin.m2m2.scripting.ScriptPointLocatorModel","com.serotonin.m2m2.web.mvc.rest.v1.csv.CSVPojoHandler.findModelDefinition(CSVPojoHandler.java:92)
com.serotonin.m2m2.web.mvc.rest.v1.csv.CSVPojoHandler.initialize(CSVPojoHandler.java:62)
com.serotonin.m2m2.web.mvc.rest.v1.csv.CSVPojoHandler.buildMapping(CSVPojoHandler.java:582)
com.serotonin.m2m2.web.mvc.rest.v1.csv.CSVPojoHandler.initialize(CSVPojoHandler.java:68)
com.serotonin.m2m2.web.mvc.rest.v1.csv.CSVPojoWriter.writeNext(CSVPojoWriter.java:66)
com.serotonin.m2m2.web.mvc.rest.v1.csv.CSVPojoWriter.writeAll(CSVPojoWriter.java:100)
com.serotonin.m2m2.web.mvc.rest.v1.converters.CsvMessageConverter.writeInternal(CsvMessageConverter.java:76)
com.serotonin.m2m2.web.mvc.rest.v1.converters.CsvMessageConverter.writeInternal(CsvMessageConverter.java:31)
org.springframework.http.converter.AbstractHttpMessageConverter.write(AbstractHttpMessageConverter.java:208)
org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.writeWithMessageConverters(AbstractMessageConverterMethodProcessor.java:143)
org.springframework.web.servlet.mvc.method.annotation.HttpEntityMethodProcessor.handleReturnValue(HttpEntityMethodProcessor.java:125)
org.springframework.web.method.support.HandlerMethodReturnValueHandlerComposite.handleReturnValue(HandlerMethodReturnValueHandlerComposite.java:71)
org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:122)
org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:749)
org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:689)
org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:83)
org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:938)
org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:870)
org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:961)
org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:852)
javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:837)
javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:769)
org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1667)
org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83)
org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:364)
org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
org.eclipse.jetty.server.Server.handle(Server.java:485)
org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:290)
org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:606)
org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:535)
java.lang.Thread.run(Thread.java:745)
"

**Comment by terrypacker** [comment]
Closing as fixed.
