### ISSUE TITLE
Work on Event Detectors

### ISSUE THREAD

**Issue by Joelhaggar** [infiniteautomation/ma-core-public#414]
Make Event Detectors editable from the Event Handler page.
Be able to create a new Event Detector on the Event Hander page as well
Allow Event Detectors to be exported and imported via json and/or CSV

**Comment by Puckfist** [comment]
The JSON import/export exists. The other features were maybe influenced by the decoupling of event handlers but I can't say if that changed the UI desires

**Comment by terrypacker** [comment]
Closing this issue as it will be done in the new UI and should be opened in the ma-dashboards repo.  Creating new issue around event detector import #1142
