### ISSUE TITLE
Think about how to segment other user information.

### ISSUE THREAD

**Issue by Joelhaggar** [infiniteautomation/ma-core-public#415]
See this forum post: http://infiniteautomation.com/forum/topic/1939/creating-permission-groups/4

**Comment by terrypacker** [comment]
There are a few ways to handle this.

1. Do some pre-processing on the page based on the user who requested it's permissions to either show or not show this icon.  (Can you think of anywhere in mango this is already done?)

2. Limit the view of what's in the permissions list based on the User who is requesting it.

**Comment by terrypacker** [comment]
Option 2 was implemented and now the list only shows Users and thier permissions that overlap the current user.  Leaving open for Review.

**Comment by terrypacker** [comment]
Closing as complete.
