### ISSUE TITLE
Dojo dropdown not usable on Android (Chrome browser)

### ISSUE THREAD

**Issue by jeremyjhall** [infiniteautomation/ma-core-public#419]
The Dojo dropdown menu (used on the Watchlist page to select different watch lists, for example) cannot be used on Android using the current Chrome or Chrome Beta browsers.

The means mobile users cannot change watch lists.

Seems to affect releases after 2.4.2 (including current 2.6.0 beta)

**Comment by terrypacker** [comment]
Unfortunately Dojo isn't supported on mobile devices, for mobile pages we would need to use the dojo mobile package.  We went down that path some time ago but it became too expensive to create a mobile view and a desktop view.  At this point it would be easier to create a custom page with the functionality you want using the dashboards module.
