### ISSUE TITLE
Excel Reports Shut down message when unlicenced.

### ISSUE THREAD

**Issue by Joelhaggar** [infiniteautomation/ma-core-public#422]
Excel reports give this warning in the logs if it is unlicensed:

WARN 2015-09-08 09:47:18,221 (com.serotonin.m2m2.module.license.TimedModuleLicense.licenseCheck:72) - excelReports is unlicensed, system will shutdown at Sep 08 2015 17:47:18

This is on a clean install with no reports.  I'm not sure if it actually shuts down at that time or it's just a leftover warning that should be removed.  I have had several report of people upgrading from 2.5.2 to 2.6.0 beta where Mango would not start up until they removed the Excel Reports modules.

**Comment by terrypacker** [comment]
The log message was being written but then the timer was being stopped, the log message is now moved to only happen if the system is really going to shutdown.
