### ISSUE TITLE
Add API endpoint for watch-list's

### ISSUE THREAD

**Issue by stevededrick** [infiniteautomation/ma-core-public#437]
It would be very useful to be able to get the list of watch-list folders and then points within a folder through the API.  A watch list could then be used in creative ways to group points together for charts generated through custom dashboards.

**Comment by Puckfist** [comment]
When you say watch-list folders, you mean to get the points within a watchlist?

**Comment by stevededrick** [comment]
Yes, calling an individual watch-list a "folder" was in accurate.  Your interpretation is correct.

**Comment by Puckfist** [comment]
This has been done, one can query for watchlists through the API, and for a list of watchlists. Closing
