### ISSUE TITLE
Auto upgrade causes failure on windows systems.

### ISSUE THREAD

**Issue by Joelhaggar** [infiniteautomation/ma-core-public#438]
The ma-start.bat file does not detect the m2m2-core-x.x.x.zip file in the MA_HOME folder.  

All the modules and the core zip file are downloaded but when Mango reboots it upgrades all the modules but not the core which then causes the system to boot up with no modules as they are all for the newer core and not compatible with the old core.

Even if the ma-start.bat file did to the core upgrade this would still not work for systems running as a service using YAJSW.

**Comment by Puckfist** [comment]
This works using the scripts bundled since 2.6.2
