### ISSUE TITLE
Meta Data Point History Generator - No Feedback

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#443]
no good feedback from generate history window for Meta Data Points

**Comment by resotek** [comment]
I overlooked the start year on a "Generate History" entry, and the job created over 1 million and counting medium priority work items. My important metatdata points stopped updating, and there was no way to terminate the job, let alone assess its completion. I had to kill mango, and now I have to wait for it to clean the TSDB. Can you please display the time stamp every 1 or 5 seconds,  and more importantly, support a cancel button?

**Comment by resotek** [comment]
After the Meta Data Point History Generator completes a job, it displays in a pop-up window the number of points generated. However, that number is much greater than the number of points generated and added to the pointvalue log. Can the completion dialog list the number of points added to the log, and wording be made clearer regarding the meaning of the large number currently displayed in that dialog?

**Comment by terrypacker** [comment]
This issue should be dealt with at the same time:  #318

**Comment by terrypacker** [comment]
Also deal with #319

**Comment by Puckfist** [comment]
This and #318 are somewhat addressed in the rest controller I put into the Meta-history-generation-API branch of the private modules. It supports getting status by seeing the last processed update's timestamp and the number of points in the submitted request. It supports cancelling the task between generating points' histories

**Comment by Puckfist** [comment]
The history generation API is released in the latest meta module
