### ISSUE TITLE
Setup RequireJS to use the Version URL Mapping to auto-refresh Browser Cache

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#448]
All /resources can be accessed at the URL /{versionNumber}/resources which forces the browser to re-cache the files on version changes.  This isn't being used by RequireJS but it would be very nice if it was.

**Comment by jazdw** [comment]
Should be pretty trivial to setup, just modify the base url in the loader config file.

**Comment by terrypacker** [comment]
Do you have any slick ideas of how to dynamically do that so we don't have to update that file every release?

**Comment by jazdw** [comment]
Maybe using Maven's resource filtering? The web folder is not setup as a resource though so you might have to jump through some hoops.

**Comment by terrypacker** [comment]
Closing this as dealt with via Etags.
