### ISSUE TITLE
User Permissions Bulk Update DS.Name

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#450]
SQL syntax error, unknown column DS.Name in table dataPoints.

DataPoints has a DS ID column, but not a name column. To reproduce, attempt any bulk update of user permissions with anything in the data source name category.

**Comment by terrypacker** [comment]
Fixed with commit: 3cdaf0530e4d003190e74b3e4d8c8a2ec92bdc00 

Once this is tested and confirmed to fix the problem this issue can be closed.

**Comment by Puckfist** [comment]
Looks good.
