### ISSUE TITLE
Excel Reports Device Name Search not performing correct

### ISSUE THREAD

**Issue by Joelhaggar** [infiniteautomation/ma-core-public#454]
See forum post: http://infiniteautomation.com/forum/topic/2029/excel-reports-add-a-point-functionality

![image](https://cloud.githubusercontent.com/assets/2327703/11446534/637de022-94f5-11e5-8f66-d104162af1c4.png)

![image](https://cloud.githubusercontent.com/assets/2327703/11446537/8040e13c-94f5-11e5-8ee2-1799c6ff7ffb.png)

**Comment by Puckfist** [comment]
This is still an issue.

1. Filter by.... is editable. This means I can erase 'me' in Name and get silent server errors.

**Comment by Puckfist** [comment]
[excel reports stack trace.txt](https://github.com/infiniteautomation/ma-core-public/files/60348/excel.reports.stack.trace.txt)

**Comment by Puckfist** [comment]
Closed. It appears the search has changes to be name, device name, or XID, but only one at a time.
