### ISSUE TITLE
Duplicate User Names are possible and prevent login

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#459]
A duplicate username can be given by renaming an existing user. This prevents either user from logging in.

**Comment by terrypacker** [comment]
Also fixing the dropdown list so that it reflects the new Username.

**Comment by terrypacker** [comment]
This problem is specific to Admin users renaming a user to an existing user.  Normal users cannot edit others and no user can change their own username.

**Comment by terrypacker** [comment]
Also fixed to clear drop down when creating a new user.

**Comment by terrypacker** [comment]
Backend API Changes for duplicate usernames here: 9f6d6ec751787541d244c8baa494c32597a9b2f4

**Comment by terrypacker** [comment]
Fixing another introduced bug in creating new user with this commit: 82e777349ac84a382a43cc0f0861e34eb8a3828d

**Comment by Puckfist** [comment]
Looks good
