### ISSUE TITLE
Users Page not displaying Server Time Zone

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#461]
When set to 'use server time zone' it does not display that time zone's value beneath the select.

**Comment by terrypacker** [comment]
If I'm understanding this correctly I think this is supposed to work that way.

The 'use server time zone' is its own unique setting.  For example if all users are set to this and the server moves timezones then all the users move timezones too.  It doesn't auto-detect the timezone and set it to a specific zone.

**Comment by Puckfist** [comment]
Ah, perhaps I misunderstood what "Time zone label" meant in line 7 of our spreadsheet, for the issue at https://github.com/infiniteautomation/ma-core-public/commits/91953a502717dc901046ba70e69b9c9701f052b9

I was interpreting that to mean it would say Zone/City under the timezone, not that I think it should or shouldn't. Perhaps it just meant the label for the table section

**Comment by terrypacker** [comment]
yes I just wanted verification that when using the 'use server time zone' option everything still works.
