### ISSUE TITLE
Meta Point - 'return;' behavior

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#462]
If a Meta Point hits a 'return;' statement, it's equivalent to 'return null;' which is parsed
Binary=false
Multistate=0
Numeric=0.0
Alphanumeric=""

This means to prevent a meta point from getting a value for an execution, you must cause a value error in the return or a script error in that code path.

**Comment by terrypacker** [comment]
Not going to worry about this.
