### ISSUE TITLE
CSV Import Header length > row length

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#465]
An ArrayIndexOutOfBoundsException is thrown when there are more headers than columns in the data. It manifests as a 500 error printed stack trace to the page, but the ArrayIndexOutOfBoundsException line only displays the index at fault, which is not informative. To evince, do a CSV export of any data points, add a comma to the end of the headers and hit import.

**Comment by terrypacker** [comment]
Cleaned up the response messages a little and added checks for every row agains the length of the header.  Since the header is assumed to define the document the best we can do is let the user know that a row is different in length.  There is an error for row too long and one for row too short.

**Comment by Puckfist** [comment]
It still prints a stack trace, but it is more informative
