### ISSUE TITLE
New Data Point Details - Still refreshing after logout

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#469]
Using two tabs, login and view a point that updates with some regularity on the new Data Point Details view. Bring up any page in your other tab, and use it to log out. Values are still updating!

**Comment by Puckfist** [comment]
The same is true for other websocket powered pages as well, such as the pointValuesWebSocket

**Comment by terrypacker** [comment]
One option is SpringSession: https://github.com/spring-projects/spring-session/tree/1.0.2.RELEASE//samples/security

Still investigating why the web socket session isn't getting closed on logout though.

**Comment by terrypacker** [comment]
Added code to close WebSocket after HttpSession is invalidated, made this the default action but provided the option to create WebSockets that remain open after logout.

**Comment by Puckfist** [comment]
Confrimed
