### ISSUE TITLE
Permissions can be given to whitespace

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#471]
Not really a bug per se, but you can have a user group composed of only spaces. Since we're trimming, all user groups composed of only spaces are equivalent.

**Comment by terrypacker** [comment]
Added validation to check for empty permissions when saving a User.  

This will catch things like ``` , , ``` but not like ``` ,, ```

**Comment by Puckfist** [comment]
It seems like ,, doesn't have the issue since emptiness is discarded before the trim operation

**Comment by Puckfist** [comment]
Confirmed cannot save whitespace as a user's permission group, but whitespace can still be a group in other permissions fields.

**Comment by Puckfist** [comment]
Marking as closed since the issue cannot be evoked anymore, but there are still opportunities to clean up validation on other permissions fields.
