### ISSUE TITLE
New Data Point Details - Useless refresh button

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#476]
It's pretty, but it seems disconnected. With the way we're updating the page now, it doesn't have a purpose, does it?

**Comment by terrypacker** [comment]
That button refreshes the data point by calling DataSourceRT.forcePointRead().  This is not required to do anything for all data sources but some have this implemented.  So this button doesn't actually refresh the view it refreshing the backing data.  If implemented properly you could essentially request point values from a  data source with having it poll.

**Comment by terrypacker** [comment]
I'll double check that its actually wired up, it may not be as I can't remember so if not I will get it working if possible.

**Comment by terrypacker** [comment]
This should be ready to test now.

**Comment by Puckfist** [comment]
Confirmed the functionality is working, but the img is not in button mode (clickable but not giving me the button styled point, merely a standard cursor as I hover over it). Perhaps it needs the 'clickable' class?

**Comment by Puckfist** [comment]
Clearly clickable
