### ISSUE TITLE
help.shtm accessible without login

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#480]
It is a .shtm yet is accessible without a login. To repeat, change /login.htm to /help.shtm

**Comment by terrypacker** [comment]
Turns out this is by design.  The mappings for various URLs defined in the ModuleRegistry (line 500-ish) show that:
      preDefaults.add(createControllerMappingDefinition(Permission.ANONYMOUS, "/help.shtm", new HelpController()));

So any anonymous user can see this page.  Its probably ok since everyone could use a little help sometimes.

**Comment by terrypacker** [comment]
The fix will be to replace the .shtm post fix with .htm and check all references to this page.
