### ISSUE TITLE
Event Detectors not in CSV export from Data Sources page

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#481]
There is no difference between a CSV export of a data source's points when they have event detectors and when they do not.

**Comment by terrypacker** [comment]
The Event Detectors are not part of the CSV data that is exported mainly because they don't fit well into a flat file format.

**Comment by terrypacker** [comment]
We still want to test that the Event Detectors are not mangled by performing a CSV import/export.

**Comment by Puckfist** [comment]
Resolved

**Comment by Puckfist** [comment]
Resolved
