### ISSUE TITLE
Test Un-Escape of all TcpIp Data Source Messages.

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#490]
Code here: infiniteautomation/ma-modules-private@f1ecd02ccbf4d7510660f917f22dad38089237ef

**Comment by Puckfist** [comment]
Alphanumeric write commands are not escaped, TcpIpDataSourceRT:252

**Comment by terrypacker** [comment]
Fixed with commit: infiniteautomation/ma-modules-private@ 5e7fda238a75672fe7ae03ebb23d93f545d2bf2d

**Comment by Puckfist** [comment]
It looks like the logic is unescape( writeCommand.replace( %VALUE%, pointValue + DS_delimiter ) ) where it should be unescape( writeCommand.replace ( "%VALUE%", pointValue ) + DS_delimiter )

**Comment by terrypacker** [comment]
Yep you are correct.

**Comment by Puckfist** [comment]
Confirmed
