### ISSUE TITLE
JSP Views - Jasper Exception

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#497]
JSP Views do not seem to be compiling correctly. I'm guessing its connected to the enhancements that were made to render Graphical Views faster.

Placing either an empty file or a basically empty Hello World html page in MA_HOME/web/modules/jspViews/web/yourFile.jsp will yield a ClassNotFoundException when you try to open it at host:port/jsp-views/yourFile.shtm

**Comment by terrypacker** [comment]
Setting Jetty to use development mode as default.  See commit f1d3f5442b4f1b592e6230d2ca8dae577aebd6be

**Comment by Puckfist** [comment]
Resolved
