### ISSUE TITLE
Email Event Handler - Provide Custom FTL Mask

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#498]
it would be nice if individual email event handlers had the power to specify override FTL patterns to use in generating the email. This would be useful to help keep messages concise enough when necessary for text messages, or just to help differentiate event handler emails.

**Comment by Puckfist** [comment]
https://github.com/infiniteautomation/ma-core-public/commit/75654f851ec06c1aac9c0022d54336788b18f605

**Comment by Puckfist** [comment]
Reopening. Freemarker is such a pain to write that it may be really useful to have a validate / "Show me" button.

**Comment by terrypacker** [comment]
Works for me.  Closing as this will be added to the new UI.
