### ISSUE TITLE
New Data Point Details - Duplicate Events

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#501]
On two upgraded systems I've noticed duplicate events (same eventId) being displayed on the new Data Point Details page. For the chick coup, some events are doubled (but not all for even a single point), and on the lab rat some are displayed three times (more or less all of them). I haven't found the condition to evoke it in a clean system yet, though.

**Comment by terrypacker** [comment]
This could be related to a web socket session that has registered itself more than once.  If multiple sockets or sessions or registrations were made then one event for each would be sent.

**Comment by Puckfist** [comment]
Closing as i have not observed this in a long while
