### ISSUE TITLE
Scripting Data Source - Events from the past

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#506]
The Scripting data source permits you to specify a timestamp for an outgoing set. If an error occurs on that set, such as a value type error, the event will be raised with the timestamp provided to the set call.

**Comment by terrypacker** [comment]
This is now fixed to generate the event at the time the set was made.  It was obviously coded the other way for a reason and it would be good to understand why that was done.

**Comment by Puckfist** [comment]
Confirmed. Perhaps it was coded that way for the sake of running a simulation? Or perhaps people's scripts were expected to take a very long time to execute?

...Is there any other way to raise an event at an arbitrary point in time?
