### ISSUE TITLE
Swagger XSRF Token Broken

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#509]
Using the swagger page, the tools to post or put seem to have a security issue. You can get a point, then turn around and try to update it via XID to evoke.

**Comment by terrypacker** [comment]
This is fixed with: f4b624c3f23d73f2073107cf42ce62a557a73aa6

**Comment by Puckfist** [comment]
Confirmed, the security token seems to be working

**Comment by Puckfist** [comment]
Not working, cannot POST still

**Comment by terrypacker** [comment]
Seems ok to me.  Make sure you are logged in prior to posting any data.  I tested with a POST to /v1/users

Also note that the page isn't exceptionally resilient to errors so if something goes wrong its best to reload the page as sometimes additional requests won't be sent.
