### ISSUE TITLE
Data Sources - i18n key missing

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#520]
We're missing the i18n key to clear the error section. To evoke, type a squiggly brace { into the 'type' sort field, then mouse over the red X that clears the errors section.

**Comment by terrypacker** [comment]
Note that this same key was being used on the pointValueEmport.jsp snippet.

**Comment by Puckfist** [comment]
Confirmed. Is pointValueEmport.jsp used anywhere?
