### ISSUE TITLE
Import/Export - System Settings broken

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#522]
System settings on the import/export page seem generally broken. A clean Mango with no modules will output a system settings object it cannot import (seemingly). The errors appear as a read, bold " 'System Settings' : " but without any content. No stack trace is printed.

**Comment by terrypacker** [comment]
Does this relate to #29?  If so we should close it and move that into here.

**Comment by Puckfist** [comment]
output: 
'Import Success': saved
Import Complete

Should say 
System Settings: saved

**Comment by Puckfist** [comment]
Confirmed
