### ISSUE TITLE
Jetty Thread Pool env.properties inverted

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#523]
The following 2 env.properties are inverted.
#Jetty Thread Pool Tuning
web.threads.minimum=10
web.threads.maximum=200

Test by running up visualVM and seeing the qtp-xxx threads min pool size locked to the minimum value.

**Comment by Puckfist** [comment]
Confirmed that they have been unswitched. Minimum can exceed maximum currently, but maximum prevails. Marking as closed.
