### ISSUE TITLE
Email Settings no validation on "From" address

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#529]
This field is labeled with bold text indicating that it is required, although saving with nothing in the field is acceptable and causes email failures.

**Comment by terrypacker** [comment]
Adding validation for Smtp Host, Port, Email From Address and From name.

**Comment by Puckfist** [comment]
Not resolved. The field for From Name is not bolded to indicate that it is required. Also, I'm not sure non-blank is meaningful validation for a host. Why not just permit empty or have some other sort of option for SMTP disabled?

**Comment by Puckfist** [comment]
Resolved.
