### ISSUE TITLE
Brewer's Dashboard - missing i18n key

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#532]
The key for annotation.tankAlarm is not set. Visible on data point details for alarm points, set in MovementDetectorRT and ZoneRateOfChangeDifferenceDetectorRT.

**Comment by terrypacker** [comment]
Changing Movement detector to one of: 
```
annotation.alarm.temperatureRising=Temperature rising alarm set
annotation.alarm.temperatureFalling=Temperature falling alarm set
```

Changing Rate of change detector to:
```
annotation.alarm.temperatureZoneDeviation=Temperature zones deviation alarm set
```

Does that make sense?

**Comment by Puckfist** [comment]
I would almost be looking for DataSource: {0}
When admin sets, the annotations say: User: admin
Maybe: DS: {0}

**Comment by Puckfist** [comment]
Looks like MovementDetector is doing data source ID. Names?

**Comment by Puckfist** [comment]
Confirmed

![tank annotation](https://cloud.githubusercontent.com/assets/4428029/11903128/4e9afdc2-a574-11e5-86d1-62f65633662d.png)
