### ISSUE TITLE
Point Data Import - Invalid CSRF

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#533]
csvDataImport.shtm being denied from the dataImport.shtm when I try to submit a CSV export of a point's values.

**Comment by terrypacker** [comment]
This change is for HTML5 enabled browsers and also legacy browsers(untested).  It would be worth running up an old browser that isn't html 5 (if you have one) to test it.

We should probably test Excel imports too.

**Comment by Puckfist** [comment]
Confirmed fixed. I ran it up in the IE bundled with Windows 8, also.
