### ISSUE TITLE
Rest API - Toggle Mute throwing NPE

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#544]
I can't toggle mute from the API pages, I get a stack trace like the attached.

[mute stack trace.txt](https://github.com/infiniteautomation/ma-core-public/files/66197/mute.stack.trace.txt)

**Comment by terrypacker** [comment]
Fixed in core javascript and css and also api module backing method via commits:

8a0ad226894a7c7289dfb0fabb513837527a23ed

and 

infiniteautomation/ma-modules-private@ bd423dbe1e7561b22443b282d0ff7b319bbd3b76

**Comment by Puckfist** [comment]
I can confirm the toggle appears to be working, but there is no alarm sounds on those pages for me. I saw you opened issue #547 to address that. Closing.
