### ISSUE TITLE
HTML 5 Page Support for Audio Sounds

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#547]
Currently the HTML5 Pages do not support audio when an alarm is raised.

**Comment by terrypacker** [comment]
Wrong commit referenced, oops.

**Comment by Puckfist** [comment]
I believe this issue just got some action. Had to clear the browser cache to pick it up, but I confirmed the sounds are playing.

Bad behavior:
When muted again, the icon doesn't update to its muted state.

**Comment by Puckfist** [comment]
I have a feeling these changes also caused the legacy pages to play alarm sounds for all levels of active alarm when the page loads if the user has unmuted the alarms. Subsequent plays only play the highest level noise.

**Comment by Puckfist** [comment]
Looks good.
