### ISSUE TITLE
Excel Reports Swagger - Didn't parameterize templateFilename

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#552]
I was going to test downloading the excel report through the API through swagger, but the {templateFilename} isn't exposed and is always sent as {templateFilename}

**Comment by terrypacker** [comment]
I will need more information, specifically what endpoint are you attempting to use?

**Comment by Puckfist** [comment]
/v1/excel-report-templates/download/{templateFilename}

**Comment by terrypacker** [comment]
I see, these controllers were written prior to us being allowed to use .xxx extensions in our paths.  I'll correct the endpoints for these so swagger picks that up.
