### ISSUE TITLE
Excel Reports - License Improperly Checked

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#554]
On a system where your license type is paid you are still restricted to one template. I advise fixing by adding 

if(license != null && license.getLicenseType().equals("paid"))
			return Integer.MAX_VALUE;

to ExcelReportsCommon:getAllowedTemplateCount

**Comment by terrypacker** [comment]
It also looks like the license for 3 templates was only going to allow 1 template.

**Comment by Puckfist** [comment]
Paid working, three cannot be tested until placed in store but addressed
