### ISSUE TITLE
Mango returns scheduled event to normal on shut down

### ISSUE THREAD

**Issue by Joelhaggar** [infiniteautomation/ma-core-public#56]
This could be a bug or it could work this way on purpose, we probably need to evaluate the best way it should work.

**Comment by terrypacker** [comment]
Review the idea of a new schedule module instead of changing this.

**Comment by terrypacker** [comment]
This should be thoroughly tested in various scenarios as the code originally relied on the fact that the events would be returned to normal on every shutdown.

**Comment by Puckfist** [comment]
The code you changed in ScheduledEventRT:initialize was almost certainly the code handling the other condition (you made it "was active, inactive time passed while off, so inactivate it") but you stripped the complement of "was inactive, passed active time while off, so activate it."

**Comment by Puckfist** [comment]
i confirmed that the latest instance of the event is in the correct condition (active or inactive), and whether or not that is a change (in the form a new event) is governed by the state of the system prior.

i think this is what we want. The only odd seeming conditions to me is are...
1) event goes active. 2) Mango turns off, 3) passes inactivation time, 4) passes activation time, 5) Mango turns on, 6) result: the event from (1) is still active and only one event exists. It was not raised, and thus would not have been handled. I believe this case was considered an accepted?

**Comment by Puckfist** [comment]
The word has come that the events do need to be raised again, so the time simulation is probably necessary. However, only one new event should ever get raised at the boot, such that if Mango had a daily event and way turned off during the active period, then brought back online ten days later, only one event should be raised at the new boot.

**Comment by terrypacker** [comment]
Interesting, only 1.  I see how turning Mango on without that limit might cause the generation of many events.  So the next question is, what is the timestamp of the 1 alarm we are raising.

**Comment by Puckfist** [comment]
I can't think of any benefit to lying. Now seems like it'll behave best with all the things event handlers could do with it, and it seems like from a historical perspective it is better to have what really occurred recorded.

**Comment by Puckfist** [comment]
Confirmed, well behaved!
