### ISSUE TITLE
Point details page amCharts doesn't display on iOS devices

### ISSUE THREAD

**Issue by stevededrick** [infiniteautomation/ma-core-public#565]
I've tested an iPad mini running the latest iOS as well as iPhone 6. The plot doesn't show up - where same datapoint and time period does show on my PC. Tested Android phone where chart does show up. Also note that a custom dashboard using amCharts I'm working on has the same results when 1 point is added to the chart. If 2 points are added, the first point appears. If 3, the first 2 appear, and so on.

Mobile safari and chrome tested on both iOS devices.

**Comment by terrypacker** [comment]
Closing as fixed as per issue #653
