### ISSUE TITLE
Excel Reports - Table Column Ordering

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#566]
The ordering of the columns in the points list puts the deviceName as the third column. This is inconsistent with how deviceName is positioned for use around other pages. Approved column order is:
DeviceName, Name, Xid, Named Range, Controls

To fix, move excelReports.js:930 --> 928 and bump 928-9 down a line.

**Comment by terrypacker** [comment]
Fixed ordering, but found bug with adding to all time series where points were same for all time series.  Removed option to add to all time series.

**Comment by Puckfist** [comment]
Tis better to lack an option than to subtly err... confirmed.
