### ISSUE TITLE
New Data Point Details - Set Field Displayed too often

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#567]
The field to set a value to a point is displayed whenever the point in question is settable, where ideal behavior is it is only visible if the point is settable and the user has permissions to set it.

**Comment by terrypacker** [comment]
I thought this was fixed?

**Comment by Puckfist** [comment]
![settableerror](https://cloud.githubusercontent.com/assets/4428029/15681756/d3598ac2-2717-11e6-8389-861044864d9d.png)

I don't see it as fixed.

**Comment by Puckfist** [comment]
Closing as deprecated by new UI
