### ISSUE TITLE
User Statistics

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#57]
How can I find out how many users are logged in and where they're logged in from?  It would be nice to show this on the User page, as well as the total number of users as a numeric datapoint from the internal datasource.

**Comment by Puckfist** [comment]
This has been added to the internal metrics, but I have been informed it may all change soon (by Jared)

As written now, I observed two users logged in immediately after boot and login, but only found one event in the events table corresponding to a login

**Comment by terrypacker** [comment]
Closing this as working in 3.0.0 to track total number of sessions logged in.  Any new features or problems around this should be opened under a new issue.
