### ISSUE TITLE
Getting Started.txt file in Mango core zip needs to be updated

### ISSUE THREAD

**Issue by Joelhaggar** [infiniteautomation/ma-core-public#573]
The forum link is old and we should add in a link to the wiki.  Also we should recommend JDK 1.8

**Comment by Puckfist** [comment]
And add information about API coming into existence

**Comment by Joelhaggar** [comment]
Lets also include a recommendation to check for updates on the modules page after installation.

**Comment by Puckfist** [comment]
Updated
