### ISSUE TITLE
Core Security - Add the IP of the client when denied for security reasons

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#583]
It could be useful to have that information. After all, know thy enemy. Other identifying information such as origin and country and probably interesting too.

**Comment by resotek** [comment]
The login username, if known, should also be included in the error message that is printed to the log file.

**Comment by Puckfist** [comment]
Was the intention to only apply this to failed logins? That was the only place I found it. I would have expected from the issue description this to also be relevant to:

1. Non logged in user navigating to .shtm page. Produces message with session cookie at warn level, does not output IP
2. Logged in user navigating to shtm page they do not have permission for, redirects to /unauthorized.shtm, nothing logged at level > DEBUG

**Comment by terrypacker** [comment]
Good point, I didn't consider that and will add that code.

**Comment by Puckfist** [comment]
I saw it log that a user who isn't logged in navigating to an shtm page produced an IP log, but I did not see one when a logged in user went to a shtm page they did not have access to.
