### ISSUE TITLE
Core Scripting - RuntimeManagerScriptUtility enables and disables during validation

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#594]
Calls to the RuntimeManager from the scripting environment are applied immediately regardless of how they got generated. This means that when you're validating your scripts' RuntimeManager functionality it's assertions about enabled or disabling data points are what's actually going on, while your gets and sets depend on whether its a validation run or a real execution to perform their actions. The RuntimeManager should probably do likewise.

**Comment by terrypacker** [comment]
This will be accomplished by modifying the ScriptUtils.prepareUtilities method to allow a mock RuntimeManager to be passed in much like the PointValueSetter interface.  We will need to create a RuntimeManagerInterface or abstraction to allow this.

**Comment by terrypacker** [comment]
Verified to work as expected test script does not enable a data source.
