### ISSUE TITLE
Excel Reports - Update POI jars

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#595]
It has been observed that there are functions in Excel that are not supported in the version of POI that we're using (3.10-FINAL) (=PROPER(), for instance [from the forum](http://infiniteautomation.com/forum/topic/2071/excel-report-bug)) which have gained support in the current version, 3.13. We should consider updating.

**Comment by terrypacker** [comment]
This is a Core upgrade so won't be available until 2.7.4 but the libraries have been changed and my existing report seems to run ok still.

**Comment by Puckfist** [comment]
Confirmed PROPER is working. There is still a date format failing HTML rendering (Month 01, 1969) but the jar is in and working.
