### ISSUE TITLE
Core, Point Hierarchy - Multiple Data Points at the same path poorly handled

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#596]
Nothing enforces point folders to only contain uniquely named points. Since the path as it pertains to the point hierarchy is /root/folder1/folder2/pointName, functions like 'getPointByName' in pointFolder have an unspecified greedy return style (perhaps it's getPointsByName?). This caused issues troubleshooting a DGLux system, as the DGLux page seemed properly configured, the hierarchy seemed fine (They're displayed with their extended names, but not to DGLux!), but the history brought in for the point we were expecting was incorrect.

**Comment by terrypacker** [comment]
Note added to method signature and DGLux is removed from 3.0.0 so closing this as it is no longer an exposed bug.
