### ISSUE TITLE
Watch List and Graphical Views display Do Not Log as 'unknown alarm level -2'

### ISSUE THREAD

**Issue by resotek** [infiniteautomation/ma-core-public#602]
Watch List and Graphical Views display Do Not Log as "unknown alarm level -2"

When multiple Do Not Log events occur, multiple "unknown alarm level -2" events are shown, each with its time stamp and alias. Does this mean that Do Not Log events are being logged again?

**Comment by resotek** [comment]
I am hoping the screenshot below from Graphical Views would help get this issue resolved. There are many yellow warning rectangles on the graphical views and watch lists that should not be there because the events are configured to "Do Not Log."

![unknown alarm level -2](https://cloud.githubusercontent.com/assets/5695546/14726856/7e422848-07f3-11e6-8b48-c23a25f5686a.png)

And in the watch list:
![watch list do not log -2](https://cloud.githubusercontent.com/assets/5695546/14727007/bc25f634-07f4-11e6-83a0-0392ac9fe2e8.png)

**Comment by terrypacker** [comment]
I'm actually working in the area of this code right now. 

1.  Do Not Log events are missing labels for the Graphical View.
2.  Do Not Log events are still fired as normal events, they just do not go into the database.  So you should expect to see them in the UI.
3.  None Level events are logged in the database but not fired so you shouldn't expect to see them in the UI.

Fired events are events that make it into the UI and also get handled by event handlers.

I can see a disconnect here as you are probably looking for an event level that doesn't go into the database AND doesn't get handled.  We don't currently have that...

**Comment by resotek** [comment]
Thanks. If Do Not Log events do not go into the database, then where does the Graphical View get the displayed data from?

**Comment by terrypacker** [comment]
There is an in-memory cache of recent events that helps limit round trips to the database.  All events except None level events end up in this cache.

**Comment by resotek** [comment]
In addition to the "None" events levels, shouldn't the "Do Not Log" events levels also be left out of that cache?

**Comment by terrypacker** [comment]
We need to test:

1.  None level events are getting into the userEvents table but not being inserted into the memory cache.  They are also not being sent out on the web socket. (this is wrong). Perhaps we should re-label this to be more descriptive.

2.  Do Not Log level events are going into the cache but not the events or userEvents tables.  

3. Update help files to match whatever the new logic ends up being

**Comment by terrypacker** [comment]
Clean up code to be consistent and revisit just prior to release.

**Comment by Puckfist** [comment]
Not fully resolved, still showing up on the old Data Point Details page as unknown alarm level -2 under the point value.

**Comment by Puckfist** [comment]
I also cannot query for None level events on either events page

**Comment by terrypacker** [comment]
Review this after #892
