### ISSUE TITLE
Core - Module download may inadvertently cause a restart

### ISSUE THREAD

**Issue by resotek** [infiniteautomation/ma-core-public#603]
Problem: "Restart after download" should not be a hidden checkbox on the module page, as it may cause (has caused) an unintended restart.

Recommendation: either never hide the "Advanced options" section (keep it expanded), or eliminate the "Restart after download" option, and add a "Download and restart" button next to the Download button.

On another note, The modules.shtm page shows: "Download all upgrades" 
Shouldn't it instead be: "Download selected upgrades?"

**Comment by terrypacker** [comment]
Keep advanced section expanded on page load.
