### ISSUE TITLE
Core, users - Indicate when permissions queries are pending

### ISSUE THREAD

**Issue by resotek** [infiniteautomation/ma-core-public#604]
The Data point permissions page does not indicate when a filter query is pending/completed. Consequently, the user is left wondering whether the search filter is pending, or whether no points met the filter criteria. This is more problematic on slow or high latency links and on databases with a lot of points.

Recommendation: 

* indicate when a filter request has been submitted
* indicate when the response has been received, by indicating the end of the list or that no matches were found.

**Comment by terrypacker** [comment]
Closing as done in 2.7.12
