### ISSUE TITLE
Watchlist - Load watch list from URL: watch_list.shtm?list="name of list"

### ISSUE THREAD

**Issue by resotek** [infiniteautomation/ma-core-public#612]
Support direct list display from URL: watch_list.shtm?list="name of list"

This will enable someone to click on a URL or object within a graphical view and go straight to the relevant watch list. Currently the user has to read through the watch lists and select the relevant one each time.

**Comment by terrypacker** [comment]
Watchlists will be redone in the coming months.

**Comment by Puckfist** [comment]
I am closing this issue as watchlists are now URL addressable, whether they are constructed watchlists, device watchlists or data source watchlists.
