### ISSUE TITLE
Modbus Publisher - Errors sneaking to standard err

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#618]
ModbusIpSlave probably needs to "implements MessagingExceptionHandler" and call setExceptionHandler(this) around line 46. As it sits the DefaultMessagingExceptionHandler is printing the stack trace to stderr when an IOException is received in the publisher's thread.

**Comment by terrypacker** [comment]
One question is as to what to do with the exceptions?  The easiest solution is to log them, the most complex would be to raise publisher events.  The problem with raising events is that it may be difficult to determine what publisher the event is for since they all share the same slave.

**Comment by Puckfist** [comment]
I have confirmed that you caught the sneaky buggers. You raise a question, so I am removing the other labels and adding question as opposed to closing.

**Comment by terrypacker** [comment]
I think this should be closed.

**Comment by terrypacker** [comment]
Make sure these are all logged.
