### ISSUE TITLE
Graphical Views - Non-admin Editing & Permissions

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#626]
If you are editing a graphical view as a non-admin, you cannot save that graphical view if there are any user groups in the permissions fields you don't belong to, even if they were there to begin with. I understand no new permissions, but the old must be allowed to persist.

**Comment by Puckfist** [comment]
I have confirmed that you can save with the existing permissions. I am marking it a question because you can still delete the permissions for groups you don't belong to and save the item without the old groups permissions. Is that what we want?

**Comment by terrypacker** [comment]
No that is not what we want, I'll fix that to handle that case too.

**Comment by Puckfist** [comment]
Got the word that you shouldn't be able to remove a permissions group from an item if you do not have that permissions group.

**Comment by Puckfist** [comment]
Confirmed. One could nitpick whitespace (groups are not trimmed when checked here) issues, but it is well enough behaved.

**Comment by Puckfist** [comment]
Passing tests, well behaved. One thing I'm wondering, if we care, is how much sense it makes to restrict a person with edit permission's ability to modify read and set permissions for user groups but not for the anonymous user. Any user with edit permission could modify the anonymous read and set permission, and thereby extend or revoke permissions to some set of users they may not share groups with. Do we care?

**Comment by Puckfist** [comment]
The ruling came that we care, but currently only so far as including notes about things like this in an eventual security advisory to system admins.
