### ISSUE TITLE
Core - Data sources page icon callbacks

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#627]
I observed, while dealing while a big list of data sources and trying to enable them all, that I get alert messages from not being able to set the icon of datasource to enabled because in the time it took to do it I had changed the filter and was enabling other datasources. These are preventing me from doing this as quickly as I would have liked, as I have to acknowledge the alert boxes.

**Comment by terrypacker** [comment]
Closing as we will not have this problem in the new UI and we are not going to fix this.
