### ISSUE TITLE
Excel Reports - View as HTML deadend

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#628]
If an Excel Report is successfully run but contains something the Poi library isn't ready to deal with, attempting to view it as HTML will direct you to an entirely blank page. One method of causing this is in issue #595 and #594

At some point we should communicate that a parsing error occurred trying to build the HTML view

**Comment by terrypacker** [comment]
I think you meant to reference #595 and #584.

**Comment by Puckfist** [comment]
Check ToHtml.java:161 for its if condition. I think you meant == probably.

**Comment by terrypacker** [comment]
Oops, sorry that was just in there for testing to see what happens on an exception.  Removing it now.
