### ISSUE TITLE
Add new alarm levels: Warning, Important

### ISSUE THREAD

**Issue by resotek** [infiniteautomation/ma-core-public#63]
There is a wide psychological gap between current alarm levels. Specifically, the difference between Information and Urgent is much too big. Adding more alarm levels would greatly help our Mango installation:
- Information
- WARNING
- IMPORTANT
- Urgent
- Critical
- Life safety

Even if there is a long term goal to support customizable alarm levels, adding these two alarm levels should be relatively much simpler to implement, and immediately provide much greater utility to the users.

**Comment by jeremyjhall** [comment]
Perhaps allowing the admin user to add, define and set these themselves would be a better solution?

Or, at the least, provide a way for the admin user to change the name of the already-existing alarm levels.
