### ISSUE TITLE
Serial Data Source - All I/O logging is in Hex, regardless of DS setting.

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#635]
It looks like either the SerialDataSourceRT could call ioLog's String logging function, at cost to the "I: O:" style, or BaseIOLog could have a log(boolean input, String message)

**Comment by Puckfist** [comment]
I think these log statements are backwards (i.e. it's logging hex when it should log plaintext)

Also I was wrong about the presence of a colon in the hex logging output, it is just an I or an O followed by a space, if we want to match it.

**Comment by terrypacker** [comment]
Reversed logging output committed.
