### ISSUE TITLE
Brewers Dashboard multiple recipes with the same name

### ISSUE THREAD

**Issue by Joelhaggar** [infiniteautomation/ma-core-public#637]
It's possible to create multiple recipes with the same name in the database which cases a problem in the rest of the system.

**Comment by terrypacker** [comment]
What version are you using?  I've looked at the code and as far as I can tell the existing recipe should be updated if you try and create one with the same name.

**Comment by terrypacker** [comment]
That code has been there for a long time, so I guess it would be better to see how you are doing that.  Can you provide the steps to reproduce this?

**Comment by Puckfist** [comment]
Isn't there a very unlikely race? Two users could submit two new recipes with the same name at the same moment and it would fail as written. Could simply synchronize this block?

**Comment by Joelhaggar** [comment]
We don't know how this happened but we suspect it was from the user double clicking the button.

**Comment by Puckfist** [comment]
This shouldn't be possible any more.
