### ISSUE TITLE
Core - Non-admin Create Data Source, oops it's gone!

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#641]
A user with access to the Data Source page (but not an admin) has permissions to create a Data Source. By default, there are no edit data source permissions. If they click away from that edit pane, they cannot get it back. But, interestingly, they could save it a second time and give themselves permission if they haven't lost the edit pane yet.

**Comment by terrypacker** [comment]
We could add some code in the DWR that checks to see if the user is an admin and if the data source has their permission.  If not it could add a permission that they do have...

**Comment by Puckfist** [comment]
Required that the user saving a data source had edit permission to that data source after the save.
