### ISSUE TITLE
events.shtm column widths are inefficient

### ISSUE THREAD

**Issue by resotek** [infiniteautomation/ma-core-public#65]
The column widths on events.shtm are not consistent with the size of the content of their data fields. This results in wasted whitespace display area, and unnecessary or excessive scrolling due to multi-line events which could otherwise fit on a single line.

Recommendations: 
- Narrow column widths to match their content (ID, Alarm Level, Time, Duration)
- Delete the "sort" link in the column headers, and replace it with an up-triangle, down-triangle, or a circle, depending on the sort criteria.
- Allow the Message column to expand according to the page width
- Place the column field name above, rather than to the left of, the respective filter field.

**Comment by Puckfist** [comment]
There is a new events page, this could be a fruitful suggestion for that, or it could be closed.

**Comment by terrypacker** [comment]
Closing as we have a new UI.
