### ISSUE TITLE
DataProvider.js Bug in Safari Web Browser

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#653]
In DataProvider.js (2.0) in the onLoad method there is this code:

I’m seeing that Safari and Chrome show different values for the ‘arguments’ object used in this method and I think that since we are iterating over that via ‘in’ we are picking up some odd behaviour.  In chrome it seems to show as the object we are expecting but in Safari its an array of length 2.  It iterates over this array using 0,1,length for resolved on each corresponding pass. I’ve checked and it does this even without the development tools open in Safari.

Here is a screenshot of on Chrome:
![chrome](https://cloud.githubusercontent.com/assets/3905204/13191228/60599cc6-d706-11e5-92a1-7905b24f0fc9.png)

Here is one on Safari
![safari](https://cloud.githubusercontent.com/assets/3905204/13191235/6b4bbb96-d706-11e5-9879-c17dbb92522c.png)

**Comment by stevededrick** [comment]
see: Point details page amCharts doesn't display on iOS devices #565

**Comment by Puckfist** [comment]
In so far as this was the issue with the charts on the HTML5 pages, confirmed fixed. The title of the issue is very nonspecific.
