### ISSUE TITLE
HTML5 Toolbar not showing all tooltips

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#656]
It was noticed that not all of the icons show tooltips in the HTML5 toolbar.  To see this go to an HTML5 page (Data Point Details, Excel Reports, Users) and hover over the Mailing lists icon, nothing is displayed.

**Comment by Puckfist** [comment]
Confirmed fixed, but the styling is different.

**Comment by terrypacker** [comment]
The styling is different because the new HTML5 page uses the title attribute of an image rather than using Dojo to display a popup.  We could rework the styles to be the same, not sure if this is important?

**Comment by Puckfist** [comment]
I had observed them to be orange background on one, white on the other. I no longer observe this. Closing.
