### ISSUE TITLE
Excel Reports - Can't open edit template from URL

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#660]
If you load a page of excel reports, then open one for editing, you can see its ID in the parameters for the page. However, if you navigate directly to that URL, you won't get an open edit panel.

**Comment by Puckfist** [comment]
This does actually work, but not if the XLSX template for the excel reports template isn't in the module's templates directory.

**Comment by terrypacker** [comment]
This will only happen if the files were deleted by someone other than Mango.  We should probably add a message saying the file is gone.

**Comment by Puckfist** [comment]
I made the endpoint not 404 and respond in the model that the template is missing.
