### ISSUE TITLE
Data Point Details History should distinguish datasource history from logged history

### ISSUE THREAD

**Issue by resotek** [infiniteautomation/ma-core-public#67]
On data_point_details.shtm, it is unclear whether the History table, which contains the following columns:
Value   Time    Annotation

... is displaying recently received points or points from the pointvalues database. I think sometimes it could display either set of points. The source of the values displayed in the point history (i.e. received from a device poll or retrieved from the  pointValues database) should be displayed in the History table and made obvious to the user.

**Comment by terrypacker** [comment]
I have added this to the REST endpoint: /rest/v1/point-values/{DP_XID}/latest for use in the new UI.

The new model looks like this:

`{
    "cached": false,
    "dataType": "NUMERIC",
    "value": 2.1203519942559415,
    "timestamp": 1481847321173,
    "annotation": null
  }`
