### ISSUE TITLE
Change horizontal position of alarm flag in Event table according to alarm severity

### ISSUE THREAD

**Issue by resotek** [infiniteautomation/ma-core-public#68]
The event alarm level not obvious in event list. Unless we have memorized how the color of each flag corresponds to each alarm level, the only way to distinguish alarm levels in a long list is by mousing-over the alarm flag and looking at the writing in the tool tip. Occasionally there are events that result in a large number of alarms. It is useful to be able to look at the list and pick out alarms based on severity.

If the alarm flag for more severe alarms were preceded by whitespace, the higher the alarm level, the further to the right the alarm flag would be displayed. The horizontal position would stand out more than the color of the flag alone. Additionally, the alarm level severity would be more obvious due to the different horizontal position under the alarm level column.

**Comment by Puckfist** [comment]
The size of the column seems fixed currently at wide enough to accommodate the whole word. I do believe that having a colorblind friendly style is a nice-to-have.

**Comment by terrypacker** [comment]
Closing as we have a new UI.
