### ISSUE TITLE
Reports - Disk space leak

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#687]
There exist ways to orphan .data files in the reports NoSQL datastore.

It appears the issue is that the deleteReportInstance method deletes from the SQL database before the NoSQL database, so it has a difficult time getting a good points list back to delete. This affects deleting run reports from the reports page and reports configured for both schedule and email (which are auto-deleting).

To fix, move the ejt.update call in ReportDao::deleteReportInstance to after the logic for deleting from NoSQL.

**Comment by terrypacker** [comment]
What about the method deleteReport? I guess the idea is that report instances can exist past the time that a report is deleted?

**Comment by Puckfist** [comment]
Confirmed fixed, confirmed that idea you asked about is also correct, instances can outlive their template.
