### ISSUE TITLE
Enable Zoomable Value Axis in amCharts

### ISSUE THREAD

**Issue by resotek** [infiniteautomation/ma-core-public#688]
Often datapoint values fall within a range, but go to zero when the equipment is disconnected or configured for maintenance. This causes extreme scaling of the data because the vertical axis is scaled using min/max over the time period.

Implementing [Zoomable Value Axis](https://www.amcharts.com/demos/zoomable-value-axis/) can solve this problem, as it enables the user to ignore extreme, outliar values, by zooming only to the data value range of interest. This could be implemented on at least the point_details.shtm page.

**Comment by resotek** [comment]
Often datapoint values fall within a range, but go to zero when the equipment is disconnected or configured for maintenance. This causes extreme scaling of the data because the vertical axis is scaled using min/max over the time period.

Implementing [Zoomable Value Axis](https://www.amcharts.com/demos/zoomable-value-axis/) can solve this problem, as it enables the user to ignore extreme, outliar values, by zooming only to the data value range of interest. This could be implemented on at least the point_details.shtm page.

**Comment by resotek** [comment]
Zooming the vertical axis would also be useful on the watchlist page graph. The image below is a good use case:
![scaled_chart](https://cloud.githubusercontent.com/assets/5695546/14830895/127f58ca-0bc1-11e6-9f1b-aaaf3e0bb0e4.png)

We are interested in the value during normal conditions, but the extreme negative value from when the equipment was taken offline for maintenance scales the entire graph so that the ripple voltage is almost invisible.

**Comment by terrypacker** [comment]
Isn't this already implemented?  I can click and drag across the chart to zoom into a range.

**Comment by Puckfist** [comment]
He was requesting zoom on the vertical Axis, which isn't possible in any of our charting.

**Comment by terrypacker** [comment]
We need the latest 3.18 version of AmCharts to support this.

**Comment by terrypacker** [comment]
Closing and opened infiniteautomation/ma-dashboards#138
