### ISSUE TITLE
Add Name to MeasurelogicDTSCellConnectionServer Thread

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#693]
This will allow for easier detection and debugging.

**Comment by terrypacker** [comment]
Consider using a thread pool to spawn connection handlers in the protocol connection server.  Code written to name the threads but a new library is not in the data source yet.

**Comment by Puckfist** [comment]
I didn't see your naming of the threads in the 2.7.x branch. I have added this. I see how a connection pool could eliminate some Threads blinking to and fro in existence, but has this been an issue for a user?

**Comment by terrypacker** [comment]
It wasn't an issue for a user, its just generally I good idea to put a bound on the number of threads that can be generated by a server socket listener.

**Comment by Puckfist** [comment]
I have added a setting to restrict the client threads.

**Comment by Puckfist** [comment]
Bounced forward if testing is required for the thread limiting.
