### ISSUE TITLE
Allow Cron and Quantization for All Polling Data Sources

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#699]
For Polling Data Sources

This will allow cron patterns and quantization for all polling data sources.  The procedure is as follows:

VO Upgrade
1. Splice in PollingDataSourceVO by extending PollingDataSourceVO
2. remove private members pollPeriods and pollPeriodType and their getters
3. fix validate() method by removing 2 properties
4. fix readObject and writeObject to not use 2 properties
5. Fix JSONRead and JSONWrite to not use 2 properties

Model Upgrade
1. Extend AbstractPollingDataSourceModel
2. Remove pollPeriod getters

RT Upgrade
1. Use the following in constructor
`if(StringUtils.isEmpty(vo.getCronPattern()))
            setPollingPeriod(vo.getUpdatePeriodType(), vo.getUpdatePeriods(), vo.isQuantize());
        else
            setCronPattern(vo.getCronPattern());`
2. Ensure quantize is passed into setPollingPeriod()

JSP Upgrade
1. Replace dataSourceAttrs tag with pollingDataSourceAttrs tag
2. Ensure the javascript still ties it all together.
3. Ensure save dwr call collects the quantize and cronPattern parameters

DWR Upgrade
1. Change save method to capture new quantize and cronPattern parameters

Help Dox Update
1. Insert section about quantize, poll period, cron as done in the virtual-ds.htm file

Update RELEASE NOTES
- Adding Cron pattern polling option
- Adding optional quantization for polls

*\* The following is a prioritized list of datasources to convert: **

*\* High Priority
ASCII - DONE
Modbus - DONE
BACnet - DONE
SQL
Virtual - DONE

*\* Medium Priority
POP3
SNMP
SSH
TCPIP
HTTP
Serial [Not a true polling data source, uses Serial Port Events see #636 ]

*\* Low Priority
BrewersDB
TankDS
Data FIle
eGauge
HeartTransverter
PakBus
PID
EnvCan
Galil 
Internal
JMX
MBus
Modbus
OneWire
OPC DA
OpenV
Pachube
Scripting

**Comment by Joelhaggar** [comment]
These seem like the priority to me:
Modbus
BACnet
SQL
Virtual



These are less important but would be nice at some point in the future:
POP3
SNMP
SSH
TCPIP
HTTP
Serial

**Comment by terrypacker** [comment]
Moving to Bugs as they can be implemented after the release.  Most of the high priority sources have been converted.

**Comment by terrypacker** [comment]
I think we should do this before we implement the new Angular UI page for data sources.

**Comment by Puckfist** [comment]
Not that it solves the issue necessarily, but you can currently run a data source on a cron by using the RuntimeManager.refreshDataSource(xid) method in the script. So, you can use a script as a cron or event wrapper for forcing data source polls. The downside being the polling rate of the data source still exists.

You can disable/enable to cause a data source to be quantized.
