### ISSUE TITLE
Dashboards Module - Invalid JSON Import

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#703]
When importing the JSON demo configuration the following errors occurred:

Data source 'DS_997094': added
Data source 'vmeters': added
Data point 'temperature': added
Data point 'DP_119588': added
Data point 'DP_984239': added
Data point 'DP_698831': added
Data point 'DP_278103': added
Data point 'DP_686983': added
Data point 'DP_549856': added
Data point 'DP_331467': added
Data point 'DP_806477': added
Data point 'DP_596850': added
Data point 'DP_370045': added
Data point 'DP_348223': added
Data point 'DP_287036': added
Data point 'DP_394777': added
Data point 'DP_347418': added
Data point 'DP_924123': added
Data point 'DP_222324': added
Data point 'DP_077116': added
Data point 'DP_390622': added
Data point 'DP_992791': added
Data point 'DP_268535': added
Data point 'DP_033512': added
Data point 'DP_840606': added
Data point 'DP_916776': added
Data point 'DP_440955': added
Data point 'DP_100375': added
Data point 'DP_279767': added
Data point 'DP_077192': added
Data point 'voltage': added
Data point 'multistate': added
Data point 'binary': added
Data point 'DP_355369': Error parsing 'integralUnit'
Data point 'DP_614346': Error parsing 'unit'
Data point 'DP_368591': Error parsing 'integralUnit'
Data point 'DP_241169': Error parsing 'integralUnit'
Data point 'DP_556556': Error parsing 'integralUnit'
Data point 'DP_622129': Error parsing 'unit'
Data point 'DP_364171': Error parsing 'integralUnit'
Data point 'DP_422050': Error parsing 'integralUnit'
Data point 'DP_805604': Error parsing 'integralUnit'
Data point 'DP_399285': Error parsing 'unit'
Data point 'DP_029774': Error parsing 'integralUnit'
Data point 'DP_202333': Error parsing 'integralUnit'
Point hierarchy: 'JsonException writing property 'subfolders' of class java.util.List', caused by: 'JsonException writing property 'subfolders' of class java.util.List', caused by: 'Data point with XID 'DP_614346' not found'{1}
Import complete

**Comment by jazdw** [comment]
File needs to be opened as UTF-8 for copying into import window.
