### ISSUE TITLE
Create Base Publisher Model for Rest API

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#704]
In preparation for a publishers endpoint add this model to the core so its ready when we want to update the modules.

**Comment by terrypacker** [comment]
New endpoints for publishers
GET /rest/v1/publishers/list
PUT /rest/v1/publishers/{xid}

Model complete for Persistent TCP publisher only.

**Comment by Puckfist** [comment]
Seems like it's a thing, and working! Seems like there may be things that could be trimmed out, specifically the 'validationMessages' but since that empty list appears in many other models it's probably fine.

**Comment by terrypacker** [comment]
Closing as working as good as we need for this release.
