### ISSUE TITLE
DataSourceVO - Duplicate enabled member from superclass

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#707]
There is a member in DataSourceVO as well as in its superclass named enabled.  For proper audit trail tracking we need to remove it from the DataSourceVO. Think serialization.

This is also the case with DataPointVO

**Comment by Puckfist** [comment]
It looks like the variables were removed at some point, but there are still duplicate setter and getter methods.

**Comment by terrypacker** [comment]
Closing as fixed.
