### ISSUE TITLE
Graphical View, Shameless Promotion

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#714]
See WirelessTempHumSensor.java:34

This component creates an alert which proclaims itself to be a shameless promotion. It should be reviewed, and possibly removed entirely.

**Comment by terrypacker** [comment]
Remove this component.

**Comment by Puckfist** [comment]
I get an XHR failure on both systems I've tested, resulting in nothing being in the components list when I open a new view for editing. I have cleared my cache

**Comment by Puckfist** [comment]
That comment was invalid, it was caused by my incorrect build target on the dashboards module, so I had no dashboards module.

**Comment by Puckfist** [comment]
We probably only wish to remove the alert. Removing the whole component resulted in Stream Corruption at the Graphical Views page, the edit view page and the json export of the views for an upgraded system using the view.

**Comment by Puckfist** [comment]
Looking at it now, I wonder if we want this as a widget to advertise our ability to design custom components. In part because it wasn't made by us, in part because its impressiveness isn't so self-evident to me, and in part because it's using the deprecated (or deprecating, at least) method for creating components.

**Comment by Puckfist** [comment]
I have removed the alert from the component. It caused an alter whose first words are 'syntax error' The commit is here: https://github.com/infiniteautomation/ma-modules-public/commit/afc316b0409edca87f658afc1459673be5c9da94

Calling it closed.
