### ISSUE TITLE
MangoNoSQL Restore based on Last Modified Date - Should be filename

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#715]
We currently sort the backups by last modified date, although there is a timestamp in the name.

This could be problematic if someone copies files into this directory to restore or edits one of the zip files...

**Comment by Puckfist** [comment]
I believe this was done. Sure looks done in MangoNoSqlDwr getFilesToRestore with the FilenameDateComparator in the sort call.

**Comment by terrypacker** [comment]
Agreed.  Is done.
