### ISSUE TITLE
Generic NoSQL Storage Auto Conversion

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#720]
Currently the automatic conversion of NoSQL data doesn't happen when the new convert property is set to do a conversion.  Implement in MangoNoSQLProxy

**Comment by Puckfist** [comment]
I did not meet success with the reports database and the version of the NoSQL module in the 2.8x branch. Instead it did not convert, and i got an error trying to run reports after changing the reversibility from reversible --> unreversible.
