### ISSUE TITLE
Implement Publisher Models

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#730]
The following modules won't build in 2.8.x until these are implemented to some degree:

BACnet
HTTP
Pachube
Modbus
Squwk
Twillio

**Comment by terrypacker** [comment]
Adding all the necessary methods so the modules compile but pushing the model creation for after the 2.8 release as it is on a per module basis and can be released as module upgrades.

**Comment by Puckfist** [comment]
Through the power of time, Squwk and Pachube no longer need doing. The rest are done I believe.
