### ISSUE TITLE
Meta Points updating on Context multiple times.

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#734]
This is due to multiple context points set to update-on-context and causes data to be generated multiple times at the same timestamp and is inefficient.  This happens only if the context points update at the exact same timestamp which is likely if they are both on the same data source.

**Comment by terrypacker** [comment]
This change has been implemented to only run the script on the first time the point is notified at a given timestamp and disregard all other notifications at that exact timestamp.

We need to discuss it and see if that is really the desired behavior.

**Comment by terrypacker** [comment]
Currently there is a potential for a meta point to run on context and not all of its points to be updated to their current values in a data source poll.  Consider one virtual source with 3 points.  Point1 is update on context but the meta script uses all points.  When the first point is updated and the script is run, the other points still have the value from the previous poll.

**Comment by terrypacker** [comment]
Maybe imply that an execution delay should be set to allow the data source poll to finish?

**Comment by terrypacker** [comment]
We could also enforce a validation rule where if a point has context points from the same data source there must be some execution delay...

**Comment by Puckfist** [comment]
I still feel there is the possibility to solve this in in having a density limit. Maybe something like....

PLRT gets update notification 1, executes script, produces prospective value 1, schedules save value task for X ms from now

PLRT gets update notificatoin 2, executes script, produces prospective value 2, task is already scheduled for save, does nothing
....
PLRT gets update notification y --> propect value y, task is scheduled already

Task fires, saves value y.

PLRT gets update notification y+1 --> prospect value y+1, no task so schedules saveValueTask for X ms from now
....

Thoughts?

**Comment by Puckfist** [comment]
Removed volatile keyword as unnecessary: https://github.com/infiniteautomation/ma-modules-private/commit/16d83eab17173b22056d1874639941429712a293
