### ISSUE TITLE
Core - Polling data source model, object structure

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#738]
When exporting a polling data source on the emport page, you will have properties named "updatePeriods" and "updatePeriodType" while using the API (tested via swagger) you will receive a "polling" object with properties "periods" and "type"

In my opinion this needs to be consistent with the older version, the "updatePeriods" and "updatePeriodType"

**Comment by terrypacker** [comment]
The models are different from the JSON Export since they are not used the same way.  Also if we change the models it will break the code for anyone who uses them in javascript.

**Comment by Puckfist** [comment]
This makes me wonder how else one JSON representation of the object varies from the other. I feel strongly they should conform whenever possible.
