### ISSUE TITLE
Create API for modules to be able to add Event Handlers

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#74]

**Comment by Puckfist** [comment]
I am not sure what is actually testable right now about this. I have written a test module that attempts to define and new kind of event handler, but it doesn't appear in any menus such that i could see if it worked. The UI for the event handlers page is not modular, and I did not see how I would define a UI component or where that would show up when coding up my test module.

**Comment by terrypacker** [comment]
Closing this as it will be tested thoroughly when we build the new UI for Event Handlers.
