### ISSUE TITLE
None Level Events HTML5 Page

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#740]
It appears that the None level events are being sent out on the web socket but not when the EventsRestController.getActiveSummary endpoint is called.  It appears they are returning to normal and the message makes it back to the page and shows negative totals for these events.

**Comment by terrypacker** [comment]
Code changed to not send notifications about none level events returning to normal.  Not sure if this is what we want but will revisit after a discussion of this issue and #602

**Comment by terrypacker** [comment]
Something else to note here is that since we are not generating user events for NONE level events they are not returned via the events report page's queries.  The events report query joins events to the user event's table.

**Comment by Puckfist** [comment]
It still bothers me a little that the sort order on the html5 pages is flipped from that of the DWR pages (meaning highest alarm level at the top of the set of active alarms, while the DWR pages puts the highest alarm level at the bottom of the header

**Comment by Puckfist** [comment]
I have updated the ordering, and would be ready to close this. https://github.com/infiniteautomation/ma-core-public/commit/77e47eb34b52e1d997194e555f9432256a33f660

**Comment by terrypacker** [comment]
Looks good to me.
