### ISSUE TITLE
Units Help - Better Explain how to Build Units

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#749]
Explain what characters can be used to combine units and that the SI Prefixes do not require any operators to combine:

`kW*h`

**Comment by terrypacker** [comment]
Also provide a way to expand on unit labels and add our own.  Specifically add kWh and psi.

**Comment by Puckfist** [comment]
like #309

**Comment by Puckfist** [comment]
https://github.com/infiniteautomation/ma-core-public/commit/acf3afc8a4537fbb00847364e7f2a647f61d5079

Closing
