### ISSUE TITLE
Persistent TCP Publisher/Receiver - Disable during point init

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#762]
Disabling the receiver during point init doesn't seem possible.  Review the code and allow this to be possible.

**Comment by terrypacker** [comment]
It appears the TCPConnectionHandler class is never notified of termination and the loop during point init should check for this.

**Comment by Puckfist** [comment]
I think this was in response to massive point sets taking a very long time. It sounds like all you're talking about is adding something like,

if( serverSocket == null )
  throw new DoAbortException(new TranslatableMessage("event.rtn.dsDisabled"));

around line 569 in the PersistentDataSourceRT
