### ISSUE TITLE
Core - Database conversion issues

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#768]
The pointEventDetectors table needs to be removed from the list of core table names in the conversion tool, DBConvert:74

**Comment by Puckfist** [comment]
This problem probably also applies to the Graphical Views module, since the graphicalViewUsers table is not in the create tables but is added to the set of table names in the SchemaDefinition. This causes conversions to fail. We should remove it from GraphicalViewsSchemaDefinition:34

**Comment by Puckfist** [comment]
The createTables-MySQL for the publishers table is missing the "tags" column that is present in the createTables-H2

**Comment by Puckfist** [comment]
I have implemented the changes in these three comments.

**Comment by terrypacker** [comment]
Removing the tags column from MySQL and Derby schemas as this is not a column we use.

**Comment by terrypacker** [comment]
Closing and opening new issue about DBConvert missing tables.
