### ISSUE TITLE
the jsonData tables doesn't migrate from h2 to MySQL correctly

### ISSUE THREAD

**Issue by Joelhaggar** [infiniteautomation/ma-core-public#769]
From a customer:

The name of the key in the export interface is 'jsonData'.  It contains the Json store config which the dashboard uses.  When migrating H2 to MySQL you'll need to update the migration script to include whichever source location that info comes from and map to the desired MySQL table.

**Comment by Puckfist** [comment]
jsonData is definitely getting converted.
