### ISSUE TITLE
Core - PollingDataSource zealously returning aborted polls to normal

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#771]
The "if (lastPollSuccessful)" in PollingDataSource:incrementSuccessfulPolls:83 probably needs a negation. The getAndSet call above it is intending to get that the last successful poll is false in the return to normal condition. As written, it attempts to return aborted poll events to normal only on the second (and subsequent) successful polls, where the ideal behavior is first and no subsequent.

Good catch @jazdw

**Comment by jazdw** [comment]
Fixed by 56ac27f
