### ISSUE TITLE
Core - Email Handler, create un-save-able situation

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#773]
If one creates an email handler via the import/export page or any json import and that email handler does not send escalation emails, the resulting email handler will become un-save-able! You can't import it again!

The issue is that the escalation periods and period type are not set in the JSON importer, and nor is the escalation recipients, so their defaults (no defaults are specified) are used. Then, when the audit system attempts to compare the old event handler to the new one during a save, there is an unsupported time period problem and an NPE for a null escalation recipients list.

Class defaults or better handling of import new non-escalating email handlers?

[traces.txt](https://github.com/infiniteautomation/ma-core-public/files/360277/traces.txt)

**Comment by terrypacker** [comment]
Closing as fixed by adding default to time period type and period for escalation
