### ISSUE TITLE
Modify value Monitors to allow using a Translatable message as the name

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#779]
Value monitors are used to measure system metrics such as point values waiting to be written or used JVM memory.  Currently they can only have names that are i18n identifiers with no arguments.  There are some situations where dynamically creating monitors for a groups of items is useful, for example to monitor the various metrics on multiple nodes in a cluster.

**Comment by Puckfist** [comment]
Looks like a NoSQL class got removed in that last commit referenced. Things look alright, otherwise.

**Comment by terrypacker** [comment]
We also need to update the PTCP Data source to use this feature.

**Comment by Puckfist** [comment]
I believe this is all done. I just closed #872
