### ISSUE TITLE
CompiledScriptExecutor - Line numbers wrong for errors

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#790]
By appending the global scripts onto the beginning of a compiled script the line numbers generated for errors are off by the number of lines of the Global Scripts.  This can be remedied by changing line 36 from this:
`
script =  ScriptUtils.getGlobalFunctions() + SCRIPT_PREFIX + script + SCRIPT_SUFFIX ;
`

to this:
`
script =  SCRIPT_PREFIX + script + "\r\n" + ScriptUtils.getGlobalFunctions() +  SCRIPT_SUFFIX;
`

**Comment by Puckfist** [comment]
Corrected. Also had to put the squiggly brace in the middle segment. The only thing that seems funky now is that if you defined __scriptExecutor__ in a global script you'd be totally hosed! I could change the validation there to ensure __scriptExecutor__ is not defined....
