### ISSUE TITLE
Core, Users - Easy DWR Exceptions

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#795]
If one logs in as a user, navigates to the user's page, saves their user, then navigates to the data point details view, one will get a slew of DWR exceptions:
[userStackTraces.txt](https://github.com/infiniteautomation/ma-core-public/files/409230/userStackTraces.txt)

You must have at least one data point prior to logging in

**Comment by terrypacker** [comment]
Duplicate of #763

**Comment by Puckfist** [comment]
Confirmed fixed in 2.8
