### ISSUE TITLE
Virtual datapoint option to calculate values at display time to avoid bloating the database with pointvalues

### ISSUE THREAD

**Issue by resotek** [infiniteautomation/ma-core-public#80]
It is often desirable to have virtual datapoints that display with short update intervals. These are stored in a pointValues database and can take up a lot of space. It would be very useful to generate selected virtual datasource pointValues at display time rather than when defining the point via the Generate history function. Whenever a point query is made for the graph, the point history could be generated for the graph at that time. This would avoid bloating the pointvalue database with point values time intervals that have not been requested.

**Comment by terrypacker** [comment]
Closing as won't change.

**Comment by jazdw** [comment]
I'm just going to add that you could definitely write some directives to grab values from multiple points and combine them for display on our new UI.
