### ISSUE TITLE
Data Point Listeners - Put into Data Point Runtime

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#805]
Data point listeners are used to notify of a point's change.  They are kept in the Runtime Manager because listeners can exist before a point is running and has a Runtime.  Every time a point is updated the point's RT must get the listeners from the Runtime and then notify them.  It would be much more efficient if the listeners were also available in the point Runtime and kept in sync there.

**Comment by Puckfist** [comment]
This created concurrency concerns, where a listener can be added at the same time as what it listens to, and the listened point can proceed without ever adding the listener to its listeners.

**Comment by terrypacker** [comment]
Reverting changes for 2.8.0 and pushing to review for later release.

**Comment by Puckfist** [comment]
Closing as very complex and not directly established as anyone's problem
