### ISSUE TITLE
Publisher Events - Make alarm levels configurable.

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#809]
Currently they are hard coded in the PublisherRT and this prohibits not logging them.

**Comment by terrypacker** [comment]
This has been added for the 2.7.14 Release.  Test:

- Persistent TCP Publisher
- Modbus Publisher
- Twilio Publisher
- Http Publisher
- Pachube Publisher
- Squwk Publisher 
- BacNet Publisher

**Comment by Puckfist** [comment]
I notice on the modbus publisher edit page two of the event levels do not have flags displayed next to them for their alarm level.

**Comment by Puckfist** [comment]
Did not work for either events I generated for PTCP - connection refused and point disabled still came at level urgent, despite being set to safety.

**Comment by Puckfist** [comment]
A lot of these alarm levels are hardcoded, i.e. PublisherRT:148, 158

**Comment by Puckfist** [comment]
https://github.com/infiniteautomation/ma-modules-private/commit/4b939668fed34e4d1962725589a0af8fa88b85fd

**Comment by Puckfist** [comment]
Looks like the Twilio events aren't raised for anything, yet.

**Comment by Puckfist** [comment]
Looks good.
