### ISSUE TITLE
Meta Data - Purge before History Generation

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#813]
Can a "purge" checkbox be added to the "Generate History" Meta Data Source pop-up so that it will purge the "Generate History" range before or as the new history is generated?

This was taken from a comment on issue #355

**Comment by Puckfist** [comment]
Yes and no. Currently PointValueDao seems to only support delete before instead of delete between. So, we'd need to change that or someone will destroy their whole meta point's history prior to the prior, rather than just the period. That probably means this is a 3.3 issue?
