### ISSUE TITLE
Excel Reports - Page load issues

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#818]
Page load doesn't seem to work if there are parameters on the URL (sometimes).

**Comment by Puckfist** [comment]
Like #660 ? That was found to be related to the template being gone from the templates directory.

**Comment by Puckfist** [comment]
I've seen this sometimes after I clear my cache, especially if there are a few report instances on the page I'm loading. Then the first load won't displace any of the report templates, but if I refresh it will come up.

**Comment by Puckfist** [comment]
This is what was in my console: 
Uncaught Error: Load timeout for modules: mango-2.0/api
http://requirejs.org/docs/errors.html#timeout
    at B (require.js?v=1526413837:8)
    at D (require.js?v=1526413837:13)
    at require.js?v=1526413837:14

I am content to close this issue since it is being rewritten into the new UI at some point relatively soon, and it is relieved by refreshing the page.

**Comment by Puckfist** [comment]
Fixed by new UI
