### ISSUE TITLE
Dao Upgrades

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#826]
1.  Provide post-update, post-delete, and post-insert methods that happen **optionally** within a transaction and are protected methods of the WebSocketNotifyingDao
2.  Make the handler protected instead of package private
3.  Consider also creating pre-save methods

**Comment by Puckfist** [comment]
Was WebSocketNotifyingDao formerly a classname? This seemed related to some recent emails but I don't see that class
