### ISSUE TITLE
Watchlist - Chart legend only displays names

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#828]
It was observed [in the forum](http://infiniteautomation.com/forum/topic/2441/watchlist-chart-only-shows-names-in-legend-without-devicenames) that somewhere in 2.5 or after the watchlist chart's legend ceased displaying the device name of the point in the legend, and only displays the name.

**Comment by terrypacker** [comment]
This is because we moved from using the Asynchronous Image Chart Servlet to the Sync version.  The code for naming was different.  I don't see any reason not to make them both use the same naming convention.  So adding the change to the Core now.
