### ISSUE TITLE
Logs directory DNE on first Mango start so there is no script log output

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#829]
Ensure this directory is created either in the ma.init script or already packaged in the release.

**Comment by Puckfist** [comment]
This surprises me! I would think (this commit)[https://github.com/infiniteautomation/ma-core-public/commit/50523fac344d019f13bf1dd3792a01600d4624a4] addressed that

**Comment by terrypacker** [comment]
Closing as this seems like it should work fine according to the startup scripts.
