### ISSUE TITLE
Template Configuration Import Modules Errors with new Watch List

### ISSUE THREAD

**Issue by Joelhaggar** [infiniteautomation/ma-core-public#837]
Data source 'Demo-DS': saved
Data source 'Demo-meta': saved
Data source 'Demo-script': saved
Data point 'Demo-Temp': saved
Data point 'Demo-outsidetemp': saved
Data point 'Demo-setpoint': saved
Data point 'Demo-fan': saved
Data point 'Demo-amps': saved
Data point 'Demo-volts': saved
Data point 'Demo-watts': saved
Point hierarchy: saved
PreparedStatementCallback; bad SQL grammar [SELECT w.id,w.xid,w.userId,w.name,w.readPermission,w.editPermission,w.type,w.query,u.username FROM watchLists AS w join users u on u.id = w.userId WHERE w.xid=?]; nested exception is org.h2.jdbc.JdbcSQLException: Column "W.TYPE" not found; SQL statement: SELECT w.id,w.xid,w.userId,w.name,w.readPermission,w.editPermission,w.type,w.query,u.username FROM watchLists AS w join users u on u.id = w.userId WHERE w.xid=? [42122-181], caused by: 'Column "W.TYPE" not found; SQL statement: SELECT w.id,w.xid,w.userId,w.name,w.readPermission,w.editPermission,w.type,w.query,u.username FROM watchLists AS w join users u on u.id = w.userId WHERE w.xid=? [42122-181]'
PreparedStatementCallback; bad SQL grammar [SELECT w.id,w.xid,w.userId,w.name,w.readPermission,w.editPermission,w.type,w.query,u.username FROM watchLists AS w join users u on u.id = w.userId WHERE w.xid=?]; nested exception is org.h2.jdbc.JdbcSQLException: Column "W.TYPE" not found; SQL statement: SELECT w.id,w.xid,w.userId,w.name,w.readPermission,w.editPermission,w.type,w.query,u.username FROM watchLists AS w join users u on u.id = w.userId WHERE w.xid=? [42122-181], caused by: 'Column "W.TYPE" not found; SQL statement: SELECT w.id,w.xid,w.userId,w.name,w.readPermission,w.editPermission,w.type,w.query,u.username FROM watchLists AS w join users u on u.id = w.userId WHERE w.xid=? [42122-181]'
Import complete

**Comment by Puckfist** [comment]
This was most likely caused by a failed upgrade of the db of some sort. I have found that whatever error caused it has been fixed.
