### ISSUE TITLE
Review Meta TIMESTAMP bugfix

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#842]
Ensure this fix works on both Java 7 and 8.

Commit: a2a179729588d237924903ac69936a83a80e86b6

**Comment by Puckfist** [comment]
It's this one: https://github.com/infiniteautomation/ma-core-public/commit/e6982101e3c4531dbdd4f532276766745323ff30

**Comment by Puckfist** [comment]
Looks good.
