### ISSUE TITLE
Permissions.hasDataPointReadPermssion Utility methods are different

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#848]
The logic applied to checking data point permissions is not the same for all methods of the Permissions utility.  Decide on the right checking (see REST data point endpoint) for using pre-split sets.

**Comment by terrypacker** [comment]
Consider exploding permissions groups when extracting a User from the Database and doing more performant permissions checking via Collections class.  See DataPointFilter in the mangoAPI module on the logic for data point permissions.

**Comment by terrypacker** [comment]
Data points and Data Sources have Set<String> in them to use in the Permissions class.

**Comment by Puckfist** [comment]
I only found one method to probably be in error, it's the hadDataPointReadPermission around line 145. I think it should have also been checking set permission, but was not
