### ISSUE TITLE
Point copy or point add permissions not saved on new points

### ISSUE THREAD

**Issue by resotek** [infiniteautomation/ma-core-public#856]
When a new point is created and then saved, the data from the permission field is cleared (and not saved). The permission fields must be re-entered and then another save operation must be performed. This is an issue whenever the admin desires a non-blank permission field.

**Comment by Puckfist** [comment]
Duplicate of https://github.com/infiniteautomation/ma-core-public/issues/812 fixed in 2.8 or 2.7.14 when released
