### ISSUE TITLE
Test BCrypt Password Hashing

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#863]
See commits:

83be93fc66cd0a1cad64d4834e9b2e6b83ec3dd0

5cdbcc98e76bfcdda3bb38fb6716e8c7d9cbced1

6fdbc13574d6a92f3432eb813a2f9639cdba88ea

**Comment by Puckfist** [comment]
This is not working for me. I have created a new database and cannot log in using the default user and password.

**Comment by Puckfist** [comment]
Nor can I log into an already existing instance with its user and password.

**Comment by Puckfist** [comment]
This seems to be working nicely!

**Comment by Puckfist** [comment]
This needs handling for importing old users in the JSON, to prepend them with the digest key

**Comment by Puckfist** [comment]
fixed https://github.com/infiniteautomation/ma-core-public/commit/7f745ab7f502cb1cf0d0dfcaaadea5148858192f
