### ISSUE TITLE
Event Detector - Missing Definition Handling

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#869]
Ensure that the existing event detector types match the legacy types for JSON import and also reading from the DB.

Here is some code to perform checks at point init startup:
See commit: edc42f0e3eb128b7feff29c1373db066082f87ce

**Comment by Puckfist** [comment]
No detectors exist yet whose definitions could be missing.

**Comment by terrypacker** [comment]
Closing as done.
