### ISSUE TITLE
Publishers - Changes Only to Select of Export Codes

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#871]
Changes the boolean of Changes only to publish type one of:

ALL
CHANGES_ONLY
LOGGED_ONLY

This is in preparation for publishing only saved data via the Persistent TCP publisher.

**Comment by terrypacker** [comment]
Should test upgrade of db with existing publisher.
Emport from legacy system.
Cannot export to legacy system.

**Comment by terrypacker** [comment]
Modified all publishers to work:
Persistent
BACnet
Modbus
Pachube
Squwk

**Comment by terrypacker** [comment]
Test this when we test #861

**Comment by Puckfist** [comment]
I tested the import legacy and the various imports when I was switching it to use the export codes.

**Comment by Puckfist** [comment]
Tested upgrading all publishers
