### ISSUE TITLE
Event Detectors - no JSON import validation

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#876]
No validation is performed on imported event detectors, so it is possible to set things like negative durations and other undesirable properties in the import. Some of these, like setting the duration type to MILLISECONDS will not be reflected in the event detector on the point's edit page.

**Comment by terrypacker** [comment]
There is no validate method on the new Event Detector VOs since there wasn't any on the original.  This needs to be implemented.
