### ISSUE TITLE
When plotting multiple lines on a graph, skip yellow auto-color 

### ISSUE THREAD

**Issue by resotek** [infiniteautomation/ma-core-public#88]
When plotting multiple datasets on the same plot, the fifth plot-line color to be auto-selected is yellow, which is very hard to see on a white background. Yellow should be skipped as a color selection on the watchlist plot or the graphical view plot.

**Comment by Puckfist** [comment]
It was discovered and resolved that the Data Point's chart color setting was not being used at all. Now plotting multiple data sets should render all series in the color specified.
