### ISSUE TITLE
Data Point Queries - Improve with Join for Event Detectors

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#880]
There are several data point queries that still use the getRelationalData() method.  These can be improved to make 1 round trip call to the database.

See DataPointDao.DATA_POINT_SELECT_STARTUP for how to use this.

**Comment by Puckfist** [comment]
I noticed there were a great deal of opportunities to simply not fetch the relational data. Some, perhaps those in graphical views and watchlists, could still have the relational data excluded, but it was not immediately obvious so I didn't do them right now.

**Comment by Puckfist** [comment]
I think there's also a lot of room for gains in the getDataPoint( String xid ) method along these same lines. It unconditionally gets the relational data, but it's quite likely this is not always necessary.

**Comment by terrypacker** [comment]
Closing, not going to create a JOIN and try to extract the results.
