### ISSUE TITLE
Event Detectors - Blabber errors at creation

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#881]
There's a potentially annoying ERROR message printed when adding new event detectors or loading a point with event detectors, akin to:

ERROR 2016-11-02 16:56:48,476 (com.serotonin.m2m2.web.dwr.util.BlabberConverterManager.convertOutbound:188) - No converter found for 'com.serotonin.m2m2.module.definitions.event.detectors.PointChangeEventDetectorDefinition' 

No ill effects observed

**Comment by terrypacker** [comment]
Fixed by editing dwr.xml
