### ISSUE TITLE
Core - Cannot log in as a user with empty permissions.

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#883]
If a user has empty permissions, "", they will get an invalid response code for their login credentials, and a stack trace like the following will print to the console.

[empty-permission-stack-trace.txt](https://github.com/infiniteautomation/ma-core-public/files/569812/empty-permission-stack-trace.txt)

**Comment by terrypacker** [comment]
Fixed so the user can login, but they are only able to see the help page.
