### ISSUE TITLE
Core, Users - Not receiving own Audit events

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#890]
With the recent change to the audit events system, the checkbox for a user receiving their own audit events no longer does anything.

**Comment by terrypacker** [comment]
Not true see #892 and I can get my own Audit Event emails.  The events are also currently saved into the event table (as a mess) but they are still handled.  See #892 for the fix on the saving part.

**Comment by terrypacker** [comment]
Closing as not true.

**Comment by Puckfist** [comment]
We should discuss this.

**Comment by Puckfist** [comment]
Nevermind, I accept it as invalid. I am going to improve the help so that it is more easier to understand
