### ISSUE TITLE
Add JSON Changes to the Audit Event context for use in Emails/Handlers

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#893]
This would be trivial to implement but would require modifying the email templates or adding the JSON config as an attachment...

**Comment by Puckfist** [comment]
I think this is already a thing. I create an event handler on my data point audit event custom email template like:

<#list evt.context?keys as cxt>
${cxt} = ${evt.context[cxt]}
</#list>

and was able to see the properties that I had changed in the email content.

**Comment by terrypacker** [comment]
I would suggest adding something to help around this specifically for Audit Events.

**Comment by terrypacker** [comment]
I just reviewed the help in that section and it is a little confusing.  Perhaps an example section would be useful.  Plus it implies that some point information is always available, which is only true for point events.

**Comment by Puckfist** [comment]
fdc60d4d83646eaa6b74d468ce9fe0ec57291854
