### ISSUE TITLE
Event Handlers - EventType member change 

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#898]
The Dao has been modified to create the EventType when a handler is retrieved.  This was done to fix the Audit event for delete bug.

Test:

Emport,CRUD operations and Upgrade of DB.

Delete a data point with a detector and check to see it is removed from db.  Also test Emporting points with  detectors.

**Comment by Puckfist** [comment]
I have noticed that a SQL error for a duplicate event handler XID-DataPointId breaks the save button for the point and requires the page to be reloaded. This could be handled with a try-catch around DataSourceEditDwr:228:saveDataPoint(dp) but it seems the more consistent way would involve the validation of the detectors, but that isn't occurring in the back end currently.

**Comment by Puckfist** [comment]
Fixed: https://github.com/infiniteautomation/ma-core-public/commit/15ffa54be60e06f0861436270268b77487168867

**Comment by Puckfist** [comment]
Tested upgrade of old handlers

**Comment by Puckfist** [comment]
Works
