### ISSUE TITLE
EventManager - EventNotifyWorkItem Changes

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#904]
1.  This is the work item that fires events Currently it is set to LOW, this level should be configurable.
2.  Change the EventManager.userEventListeners to work like a DataPointEventMulticaster linked list.

**Comment by Puckfist** [comment]
I did #2 in this branch: https://github.com/infiniteautomation/ma-core-public/commit/8fb31cf6815eb3ac21dc7d195844390559c80870

Parts of it felt a little weird but we can explore if we want to do this.

**Comment by terrypacker** [comment]
Closing as this is implemented in 3.5
