### ISSUE TITLE
Core - Maximum password length

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#907]
There is no enforced maximum password length, but up until the referenced commit the limit on characters for the password field on the login.jsp was 20 characters. Experimenting determined a maximum form length of 200000 characters, so the limit was set above this because that error is somewhat informative. Probably not the long term solution. This should be reviewed for sanity.

Experimenting on using the /dashboards/login page put the maximum character length somewhere between 7776 and 8192. Should we enforce a maximum password length during saving?

https://github.com/infiniteautomation/ma-core-public/commit/805d0b8ac2c8847e875e3a1b1eadd899ebf979fb
https://github.com/infiniteautomation/ma-core-public/commit/ee307dad35c6f4a3f9f60651db9cf8e07e8e9d94

**Comment by terrypacker** [comment]
Closing as we have password length enforcement in the validation of a User now.
