### ISSUE TITLE
ScriptException - Improvements

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#909]
Improved handling for places where Errors are thrown from scripts and change them to throw ScriptError type exceptions.  Also improve the messages from Java 7 and Java 8 ScriptExceptions see ScriptExector.createScriptError and modify to return ScriptError instead of ScriptException.

1.  Handle potentially un-caught exceptions i.e. NPE
2.  Add utility to better get Line numbers during exception events.

Edits:

**Core**
Compiled Script Executor - Re-throw all exceptions as ScriptError
Compiled Script Executor - Catch all generic Exceptions
Compiled Script Executor - add timing code to execute method

Script Executor - Re-throw all exceptions as ScriptError
Script Executor - Catch all generic Exceptions
Script Executor - Remove prettyScriptMessage() replace with ScriptError.create(e)

**GraphicalViews** 
Script Component

**Meta Data Source**
Historical Meta Point LocatorRT

**Point Links**
PointLinksRT
PointLinksDWR

**Scripting Data Source**

**Comment by terrypacker** [comment]
See this reverted commit: cfeea3a3f05f9b9b4e42fe8b290389ebaa033a79 as to some potential code changes.

**Comment by Puckfist** [comment]
For 3 I imagine we only need to handle Java 8 style.

**Comment by Puckfist** [comment]
I think this could still use some attention. I think script errors may be printing out something like... "line number 41#30 on line 41"

**Comment by Puckfist** [comment]
ScriptExecutor.prettyScriptMessage is partially responsible for bad printing. It either needs something like: 

if(message.contains("at line number"))
            message = message.substring(0, message.indexOf("at line number"));

to cut that text off the first message, or it shouldn't even be called anymore since just returning e also renders desirably in simple cases (haven't for the unsimple case yet).

**Comment by terrypacker** [comment]
Closing this as it has been reworked in Mango 3.6.  Any additional issues can be opened for more specific problems.
