### ISSUE TITLE
Data Point Edit - Template Inputs Are Not Always Disabled

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#917]
1.  Create a new point
2.  Un-check the Use Property Template checkbox
3.  All Logging Properties fields are editable
4.  Check the Use Property Template checkbox (But do NOT select a
template)
5.  All Logging Properties fields are still editable
6.  Actually choose a template from the Template drop down
7.  All Logging Properties fields are no longer editable.

By simply checking the ‘Use Property Template’ checkbox it doesn’t disable the inputs.  We
can fix this by automatically selecting the first template in the
list.

**Comment by Puckfist** [comment]
Fix released in 2.8.4
