### ISSUE TITLE
Allow Logo Override via overrides folder

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#928]
This will require a core change and to fix references to:

Common.applicationLogo 
Common.applicationFavicon

So that they call a method (Or we can do something at startup to check for the existence of an override logo.

**Comment by Puckfist** [comment]
From my testing, logo override seems to work, favicon override does not.

**Comment by Puckfist** [comment]
I take that back. From my testing both work on the legacy pages but favicons have some crazy caching so I had to change the port of my Mango
