### ISSUE TITLE
Users - Locale

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#935]
A new member has been added to the User object and all database tables.  Ensure the SQL upgrade scripts work as well as saving/retrieving users with this value.

See commit: e5853e62491e7eb937110fd377114ff35b8ccc9b

**Comment by jazdw** [comment]
Please check if we should use NOT NULL DEFAULT '' in the .sql files and also modify Upgrade13.java to suit

**Comment by Puckfist** [comment]
This field does not exist on the legacy users page, so either there needs to be some handling, that page needs to be inaccessible, or it needs to get added to that page too.

**Comment by terrypacker** [comment]
I think we just need to add an input to the legacy page.

**Comment by Puckfist** [comment]
I will fix this using a hidden input such that you simply cannot change your locale on the legacy users page. One can generate that list if one truly desires

**Comment by terrypacker** [comment]
Closing as fixed.
