### ISSUE TITLE
Users - Name

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#936]
A new name member has been added to the User object.  Test the SQL upgrade and saving/retrieving a user.

See commit: d93120744a860eb912118f87ba78716895520f61

**Comment by jazdw** [comment]
Please check if we should use NOT NULL DEFAULT '' in the .sql files and also modify Upgrade13.java to suit

**Comment by jazdw** [comment]
At the moment the validation requires the name field to be set, this can be removed so the legacy users page will still work but this raises an additional issue - if a user is saved on the legacy user page the name and locale fields will be emptied.

**Comment by Puckfist** [comment]
The legacy users page supports the name input well and fine, the locale is hidden such that it is simply not editable on the legacy page. I would think that's preferably to a not null default of ''? Can close?

**Comment by terrypacker** [comment]
Closing as done.
