### ISSUE TITLE
System Settings - Validation

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#937]
Check validation for saving all Module's SystemSettingsDefinitions.  Basically try and update all the various settings and make sure they work.

**Comment by Puckfist** [comment]
This was somewhat done (I implemented validate in system settings definition derived classes) but system settings are not validated through SystemSettingsDwr.saveSettings()

**Comment by Puckfist** [comment]
Also there are many methods in SystemSettingsDwr that are called to save some specific properties. Because of the directness of the calling, validation was not added yet
