### ISSUE TITLE
Core 3.0.0 & Site Analytics

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#942]
Ensure that the new pages have a way to report Site Analytics.

**Comment by jazdw** [comment]
No this is not implemented, but should be easy. You are talking about Google Analytics yeah?

**Comment by terrypacker** [comment]
Yes pretty much, basically any analytics engine that works by inserted some HTML into the page.

**Comment by jazdw** [comment]
Hey @terrypacker I think this will be best implemented in a separate Mango module which has an AngularJSModuleDefinition. All it need to do is

- Insert the analytics script
- Get the analytics tracking code from system settings and set it on the analytics script
- Listen to state change events `$rootScope.$on('$stateChangeSuccess', function (event) {})`
- Call `$window.ga('set', 'page', $location.path())` and `$window.ga('send', 'pageview')`

**Comment by terrypacker** [comment]
I'm not sure I agree about it being in a separate module.  The system setting is part of the core so I would like to just add that AngularJSModuleDefinition from the Core. The trick will be to only apply it if the site analytics system setting is not empty.  Any thoughts on that one?

**Comment by jazdw** [comment]
It will be a new system setting, we can't just inject a script in the head for tracking our SPA (Single Page Application). So it will be a specific Google Analytics property ID setting.

**Comment by terrypacker** [comment]
Google analytics are already implemented. The tracking ID is set in the UI settings.
