### ISSUE TITLE
BACnet Upgrade Serialization - Test with new Generics

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#943]
In a previous version of BACnet (2.2.0) we had to manually deserialize and re-serialize the data in the database since there was no UUID.  In 3.0.0 we are changing the generics of the base classes PointLocatorVO and DataSourceVO which *may* cause this to break.

However since we are forcing people to upgrade to 2.8.6 before going to 3.0.0 we could potentially assume that this upgrade will never execute the conversion code...

**Comment by terrypacker** [comment]
Also test that the Serial Data Source is not effected...

**Comment by Puckfist** [comment]
I will test this one with upgrading directly from ancient BACnet and serial data sources
