### ISSUE TITLE
REST Emport /list endpoint needs to return translation keys

### ISSUE THREAD

**Issue by jazdw** [infiniteautomation/ma-core-public#945]
The REST end point for listing the available export items only returns the name of the export item but no translation key for displaying on the UI. It should return the translation key from EmportDefinition.getDescriptionKey()

**Comment by terrypacker** [comment]
Added.  See commit infiniteautomation/ma-modules-public@0b902d9a2846edd600d7917a62ae6a559379681b

**Comment by terrypacker** [comment]
Closing as completed
