### ISSUE TITLE
REST @PathVariable not being URL decoded

### ISSUE THREAD

**Issue by jazdw** [infiniteautomation/ma-core-public#951]
Given a data point with a XID of 'DP_69096/A' the following end points return 404 not found when they are hit from the "Data Point Details" page.

/rest/v1/hierarchy/path/DP_69096%2FA
/rest/v1/point-values/DP_69096%2FA/statistics?from=2016-11-20T19%3A31%3A50.314Z&to=2017-02-20T19%3A31%3A50.314Z&useRendered=true
/rest/v1/point-values/DP_69096%2FA?from=2016-11-20T19%3A31%3A50.314Z&to=2017-02-20T19%3A31%3A50.314Z&timezone=America%2FDenver&rollup=AVERAGE&timePeriodType=DAYS&timePeriods=1&useRendered=true
/rest/v1/point-values/DP_69096%2FA/latest?limit=100&useRendered=true

**Comment by jazdw** [comment]
This may be relevant
https://jira.spring.io/browse/SPR-11101

**Comment by Puckfist** [comment]
Sounds similar to #918 in that some characters in XIDs prevent endpoints from working in some cases

**Comment by terrypacker** [comment]
The configuration is a little odd as in that I had to disable URL Decoding on the Url Path Helper, which effectively then forces decoding of the path variables.  Probably want to test this change fairly thoroughly so we don't have any adverse effects on other URLs.

**Comment by terrypacker** [comment]
Closing since we have used this in the previous releases and found no problems.
