### ISSUE TITLE
Mailing Lists - Send all events over a level to a mailing list when active

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-core-public#960]
I have done this: 
https://github.com/infiniteautomation/ma-core-public/commit/d02d5286f1d14d4ded02d831086fe702cb614889
https://github.com/infiniteautomation/ma-core-public/commit/3cb565382e9f92991bd533cce6026e5d7225f3b5

**Comment by terrypacker** [comment]
Multiple issues found here:

1.  Can't save new mailing lists
2.  Creating fresh H2 database fails
3.  Probably should test upgrading H2 with existing Mailing List entries.

**Comment by terrypacker** [comment]
We will need to determine how to set the default value for MsSQL in both the Upgrade script and the create table script as this has not yet been done.

**Comment by Puckfist** [comment]
it has been done
