### ISSUE TITLE
Test Database Changes from 2.8 to 3.0.0

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#961]
This issue is to ensure we test the SQL upgrade Scripts AND create scripts for:

MySQL
Derby
H2
MSSQL

**Comment by Puckfist** [comment]
Upgrade14 fails for Derby guaranteed. It's not a big deal, since support is getting dropped. Alternatively we could write some Derby SQL to copy the whole table to a new table, then rename the tables.
