### ISSUE TITLE
Data point rollup types should be restricted based on data type

### ISSUE THREAD

**Issue by jazdw** [infiniteautomation/ma-core-public#968]
Currently the data point edit page allows selecting any type of rollup.

The rollup should be restricted to NONE, FIRST, LAST, and COUNT for non-NUMERIC data types. The ALL option should never be allowed.

At least that's the way the current UI works, technically I guess you could do MAXIMUM, AVERAGE etc for MULTISTATE points but that's a bit of a weird use case.

**Comment by jazdw** [comment]
@Puckfist how hard would it be to hide the items rather than disabling them?

**Comment by Puckfist** [comment]
easy and done

**Comment by jazdw** [comment]
Tested and working.
