### ISSUE TITLE
Internal Data Source - Automatically Generated Points Log on Average (Not always ideal)

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-core-public#977]
For example the points that do counts such as Data Sources or Data Points or User Sessions should all probably log on instant as it is weird to see .8 user sessions or 10.2 data points.

**Comment by jazdw** [comment]
Yeah I agree, logging on average for these is wrong. Another logging type and rollup type we may want to add is mean. Not sure how this would work for floating point values though, I wonder if we could add a integer numeric data type.

**Comment by terrypacker** [comment]
I've set all the Numeric type points to log on Change and not be linked to the default template since it does interval average logging.

**Comment by terrypacker** [comment]
I guess the remaining question is if we want interval logging or if just on change will suffice.  I prefer on change since there is less overhead.
