### ISSUE TITLE
Lengthen text field width in data_point_edit.shtm

### ISSUE THREAD

**Issue by resotek** [infiniteautomation/ma-core-public#98]
On data_point_edit.shtm the width of the editable text boxes is often not long enough for the text fields or the Event Detector alias. Consequently, the user cannot read the entire value of the text field unless they place they click in the field to edit it, and move the cursor left or right. 

The length of these text boxes should be doubled or tripled, or preferably, their width should be extended to the width of the box within which they are contained.

**Comment by Puckfist** [comment]
The new UI will exist, this should be consumed or closed by it
