### ISSUE TITLE
There are duplicate zip files being created of the H2 Backup

### ISSUE THREAD

**Issue by Joelhaggar** [infiniteautomation/ma-core-public#988]
![image](https://cloud.githubusercontent.com/assets/2327703/25055375/9386f904-211f-11e7-9d9b-6341aa8f9648.png)

**Comment by Puckfist** [comment]
Caused in this commit: https://github.com/infiniteautomation/ma-core-public/commit/1b0cff1f5ba2dfcdf08e8c258e543c1195ee6ca9

By lines 172-178 of DatabaseBackupWorkItem. Unclear what the ambition of that code is. Presumably it was going to zip compress the mysqldump? Could be excised, could be moved to the MySQL block and actually do something. Have to check out MySQL restore in that case
