### ISSUE TITLE
Update website on all our modules

### ISSUE THREAD

**Issue by jazdw** [infiniteautomation/ma-core-public#993]
We should link to the https version of our site and update all the modules so the company name is consistent ("Infinite Automation Systems, Inc.").

Also update ModuleRegistry.getCoreModule()

**Comment by Puckfist** [comment]
Changed to https in ma-core-public/pom.xml didn't change vendor name but it seems like that's the place

**Comment by jazdw** [comment]
I'll just add that the reason for this is that the modules page displays the vendor name and website. This is taken from the module.properties file which is populated from pom.xml.

**Comment by terrypacker** [comment]
Closing as done.
