### ISSUE TITLE
Inconsistencies between "System event alarm levels" and values in DB

### ISSUE THREAD

**Issue by jazdw** [infiniteautomation/ma-core-public#995]
While creating the new UI pages for system settings I noticed that the "System event alarm levels" section on the old UI was displaying values which were not consistent with what was stored in the database.

In particular the "System startup" setting was displaying "None" but the database key "systemEventAlarmLevel.SYSTEM_STARTUP" had a value of "1" which should be information. My new page displayed the correct value of "Information" which was retrieved over REST.

We also noticed that after changing some of the settings then deleting the rows from the DB the UI still displayed the previously set values instead of going back to the defaults.

**Comment by jazdw** [comment]
Seems to be due to the REST API using a different SystemSettingsDao instance (and hence cache). We should use a singleton instance of the Dao and make sure the cache is thread safe.

**Comment by terrypacker** [comment]
The dao is now a singleton but synchronization has not been taken into account yet.

**Comment by terrypacker** [comment]
The cache is now synchronized via ConcurrentHashMap

**Comment by jazdw** [comment]
Tested, seems to work fine now.
